### ISSUE TITLE
Property creation take more time if have large amount of records in the class

### ISSUE THREAD

**Issue by Aniket-Lonare** [orientechnologies/orientdb#10031]
## Expected behavior  
Should create property in minimum time

 

## Actual behavior  
Taking more time to create property if class has huge records

 

## Steps to reproduce  

 

- Create class with Name Parent
- Add some indexable properties inside Parent class.
- Create child Class with Name Child extending parent class.
- Create more than 200000 records inside the child class.
- Create link type property in the parent class
- e.g. CREATE PROPERTY child.property IF NOT EXISTS LINK
- Please observe it takes more time
- In the below scenario i have nearly 25000 records

 
![image](https://github.com/orientechnologies/orientdb/assets/53806566/4e9646c6-548c-4d05-b8e9-ca03d40e9f19)

Also observed that the property is taking time while first time creating. After deleting property and recreating once again it take less time
We have tested same with version 3.2.14 and it take less time compare to version 3.2.23
Please let us know if you need any more information.
Thank you.

**Comment by tglman** [comment]
Hi,

Because OrientDB has support for schema-less properties, when a property is created we need to check if all the records present have a compatible data with the specific property, and run a migration of all the records attaching the new property, this take more time the first time it runs because of the data conversion, and less time the second run because the data is already converted.

There have been changes between 3.2.14 and 3.2.23 to this logic in the specific the old query engine has been swapped with the new query engine, I will double check the performance for this change.

Anyway the property creation is a data migration in OrientDB so if you can consider to define property ahead of time, if you can't, be aware that some time may be need for the data migration, also be aware that the data migration happen for all the classes in the hierarchy.

Bye

**Comment by tglman** [comment]
Hi,

Checking this I noticed that the underlying query for checking and migrating data, that look like more or less ` select from Class where field.type() <> "TYPE"`  in case the field had a value link it would load the linked record for do the check of `link.type() <> "LINK"`  this is not needed so I did a couple of optimizations on the query engine (https://github.com/orientechnologies/orientdb/commit/1562d7a5674428797ea2c2961b453091db8b4f20 , https://github.com/orientechnologies/orientdb/commit/0825ad65e1c9183128c25201f0605e482cf47c94) to avoid linked record to load when not needed, this will improve the performance also of other queries not only of this use cases.

This change will be released in 3.2.24 and should bring the performance of this operations to the same level of 3.2.14

Regards

**Comment by tglman** [comment]
Hi,

3.2.24 has been released, closing

**Comment by Aniket-Lonare** [comment]
Hi @tglman,
I tried OrientDB version 3.2.24, and we experienced a performance improvement, but when using the same database and scenario mentioned above, it still took some more time to create a property compared to 3.2.14.
I captured the average time for creating a property.
  - On 3.2.14, it took 14.18 seconds.
  - On 3.2.24, it took 23.98 seconds.

Was this the expected time?
Thanks
