### ISSUE TITLE
Migrate enhancements implemented in caffeine into OrientDB disk cache

### ISSUE THREAD

**Issue by andrii0lomakin** [orientechnologies/orientdb#10070]
OrientDB uses a disk cache that represents the fork of the caffeine cache, which is changed to comply with our specific needs.
Caffeine introduced many changes to improve caffeine multicore scalability. We need to move those changes to our disk cache.

**Comment by ben-manes** [comment]
Offhand, I suspect the enhancements of interest are
- Cache-line optimized frequency sketch. This was mostly for fun as it reduces from four random memory reads down to one, for a possible gain of 2.5x in my benchmark for a large sketch. That had a very modest user-facing difference.
- Usage of hill climbing to adapt the window / main regions based on the workload
- Usage of jitter to protect against hash flooding or an otherwise hot victim causing excessive rejections.
- Improved handling an entry being updated to have a humungous weight that exceeds the region's capacity.
- Caffeine does not implement the proposals from the size-aware TinyLFU [paper](https://dl.acm.org/doi/10.1145/3507920?cid=99659224047), but that may be of interest for you to explore. It has been backlogged since it's less common / practical to bound by memory usage due to the GC, but may make more sense for a disk cache. A small change that concerned me in the paper was it switched from `candidateFreq > victimFreq` to `>=` which would negatively impact MRU loops. All of that would take a significant amount of time to validate and test so I punted on it, but their results looked very promising.
- Caffeine does not implement the doorkeeper (bloom filter) optimization. That was originally because it increased the frequency bias which was a concern prior to hill climbing. Also a in-memory Java cache is probably not enormous so the space savings seemed less valuable. It is in the simulator but I never explored it deeply.
- If you persist any of the LRU list then a common disk friendly alternative is the Clock policy to reduce I/O due to reordering. I don't think you do and I don't think it makes a lot of sense to persist that anyway, but fyi as it sometimes gets mentioned in papers.

Hope that helps somehow.

**Comment by andrii0lomakin** [comment]
Hi @ben-manes 
I do appreciate your help.
Thank you!
