### ISSUE TITLE
Connection Pool should be upgraded with functionality  [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1179]
This is [Issue 1179](http://code.google.com/p/orient/issues/detail?id=1179) moved from a Google Code project.
Added by 2012-11-22T17:21:31.000Z by [michael....@gmail.com](http://code.google.com/u/103127714742729236062/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low

### Original description

    Hi 
    
    The actual connection Pool in Orientdb lacks of some needed functionality in bigger environments: 
    
    Timeout for dbs not used 
    Timeout (true / false)
    
    Listeners / Hooks - you can operate with if a connection is established 
    (for example -> is the database available or should it be created) 
    
    Listeners - on Close of database - make operations necessary (cleanup - Format C:  or whatever you need) 
    
    Listeners - on Open of Database 
    
    Hope this is enough input -> Luca we send you our implementation - maybe you could reuse something ....

**Comment by laa** [comment]
Hi,
Are you sure that this issue is valid ?

1. Listeners - on Close of database  - already implemented.
2. Listeners - on Open of Database  - already implemented.
3. Timeout  is not needed any more because single db instance consumes very few of resources.
4. @markbigler comment. See com.orientechnologies.orient.core.db.OPartitionedDatabasePool#setAutoCreate.

**Comment by laa** [comment]
Well because no one minds, I will close the issue.
