### ISSUE TITLE
Reactive Query

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1227]
It would be cool having a way to provide streamable updates to the clients based on a sort of "Live Views". This idea comes from Ayman and it's very powerful!

Let's think at this simple example. A client is interested to this query:

select from order where customer.city.name = 'Rome' and amount > 100000

But it doesn't want to poll for new items, but rather be asynchronously notified when new entries match the query. Here we can apply the classic publish/subscribe pattern.

To handle it we could save 2 object in memory:
1) the target: Order
2) the filter: customer.city.name = 'Rome' and amount > 100000

In the new "OViewHook" class I could check for each view if the record's class is a sub-class of "target" (in this case Order). If this applies i could check the filter against the record. If it returns true it could be sent to the requester.

Other things to do are:
- A good way to define the view. Probably a new asynchronous command like "STREAM select from order where customer.city.name = 'Rome' and amount > 100000"
- On startup the hook must be installed and have to handle all the publish/subscribe mechanism
- Provide a new REST way to access it. Something like /stream/<database>/<view-name>. This has to support the asynchronous way
- Update the JS driver to support it

**Comment by tommykennedy** [comment]
+1

**Comment by lvca** [comment]
This feature will be part of 2.1 as Experimental. In 2.2 we plan to put it as stable.

**Comment by jwarkentin** [comment]
Full disclosure: I'm new to OrientDB so forgive me if something here is way off base.

I've read over this and #2652 and I have a concern. I've spent a lot of time building and maintaining realtime systems. It's important to have a feature like this in the database itself because there are two problems that can't otherwise be solved and I'm concerned that the second one isn't being addressed.

1. The first is that when someone (like a dev) makes a change directly in the database instead of through some application layer, caches don't get invalidated and realtime updates don't happen. By having the database push updates it ensures that all changes get pushed through to the applications interested in data changes.

2. The second, and most significant problem, is that of displaying filtered lists of items. Let's say you're building a realtime application where you are displaying filtered lists of different types of items (like lists of articles in my case). As soon as any item of a given type is added or updated, you have to invalidate ALL lists of the given type because you have no idea how the change affects any given list. Does the new or updated item belong in a given list? Where does the new item go in any given ordered list? Since it's difficult to impossible to know exactly how a given change affects each filtered list you must invalidate all of them and re-run all queries for the given type of item.

I don't know if there's documentation somewhere for the current implementation of this feature, but my question is, does it report where the new item should go in a list or where an updated item should go in a sorted list?

**Comment by jwarkentin** [comment]
Also, the guys at RethinkDB have a very good understanding of the realtime problem and have some excellent things to consider here: http://rethinkdb.com/blog/realtime-web/

**Comment by luigidellaquila** [comment]
implemented in 2.1, see http://orientdb.com/docs/last/Live-Query.html

**Comment by gadisridhar** [comment]
ESPER EPL LIKE QUERY IS CASE SENSITIVE. HOW DO I SOLVE IT. EX - select * from StockTick having symbol like '%YHOO%' . HAVE EVENTS SYMBOL AS 'yhoo'. GUYS SUGGEST. MANY THANKS
