### ISSUE TITLE
Introduction of the "salt" to improve password security

### ISSUE THREAD

**Issue by giastfader** [orientechnologies/orientdb#1229]
Hi,
I think that the introduction of a salt field to improve the password security is almost a must.
Many times we hear about stolen passwords (even the hashed ones) from big companies and because of these issues users' accounts are be compromised.
OrientDB uses the SHA256 algorithm to hash and store passwords but this is not very secure because there are many dictionaries and lookup tables to crack this system.
I think that a good way to improve password security is the introduction of a salt field in the OUser class.

Here the explanation of the "salt passwords" concepts:
http://en.wikipedia.org/wiki/Salt_(cryptography)

Here some ideas and do/do not:
http://crackstation.net/hashing-security.htm

**Comment by lvca** [comment]
@giastfader Are you addressing also this issue?

**Comment by lvca** [comment]
Hurray! We have salt in 2.2.0-SNAPSHOT. Soon I'll update the documentation. For now we support `PBKDF2WithHmacSHA1` algorithm, where the password has this format:

    {PBKDF2WithHmacSHA1}<hash>:<salt>:<iterations>

Where iterations is stored in `security.userPasswordSaltIterations` global configuration and it's 1000 by default.

Example:
    {PBKDF2WithHmacSHA1}48E6F9BD7807A7AA18C67DD3810994B87B030B4E180D0D09:00397B36B4FFAD7467E3C34412D4E822AFB3D0B2B5CE8A99:1000

**Comment by lvca** [comment]
I forgot to mention that database with previous SHA-256 can always be read, but if the password is changed, the new salt is used.

**Comment by Shyiy** [comment]
I would suggest providing at least the bcrypt or (better) scrypt key derivation function if that's possible.
PBKDF2 is quite old, and in the case of this algorithm this has lead to it becoming less and less effective for its original purposes, as reported by many sources. The main problem being its limited memory usage, which makes it worse and worse as time passes to resist parallel brute force attacks; this has been "fixed" and improved upon by bcrypt and scrypt.

Given that this will be a completely new feature I would say it's much better to go with a better, proved, more developed approach for password key derivation from the start if it isn't too much effort.

P.S.
Anyways, regarding PBKDF2WithHmacSHA1, you don't mention the salt size use, which should be at least 128bits (or even 160bits, max for SHA-1) given the current year.
Also, more importantly, the 1000 iterations value is way too low (even if it's just a default configurable value). 15 years ago (!) when the standard was published, that was the recommended number, nowadays, even for the (arguably better) version of PBKDF2 using SHA-256 instead of SHA-1, thus already slower, we are now in the range of the hundreds of thousands.

Please see:
http://stackoverflow.com/questions/6054082/recommended-of-iterations-when-using-pbkdf2-sha256
http://security.stackexchange.com/questions/3959/recommended-of-iterations-when-using-pkbdf2-sha256
https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet

In any case, I just wanted to thank you anyways for the progress, it's definitely something good in the right direction!

**Comment by lvca** [comment]
@Shyiy Current salt size id 24 bytes = 192 bits. Last link you posted says:
```
Select:
- PBKDF2 [*4] when FIPS certification or enterprise support on many platforms is required;
- scrypt [*5] where resisting any/all hardware accelerated attacks is necessary but support isn’t.
- bcrypt where PBKDF2 or scrypt support is not available.
```

So seems PBKDF2 is the first choice.

**Comment by lvca** [comment]
@Shyiy About iterations, what's in your opinion the number should I set as default?

**Comment by Shyiy** [comment]
Perfect for the salt.

Regarding the iteration count, of course there isn't a fixed number and there's always a tradeoff, judging by some recent estimates and recomendations, in order not to impact too much performance by default I would say about 64'000.

Generally the community mentioned/agreed on this measure for 2012 and suggested doubling it every 2 years (although of course this can vary); the other alternative key derivation functions are also suggested instead of a continuous increase of iteration count for the same function, but I see your point about support and thus the PBKDF2.

**Comment by lvca** [comment]
Ok, changing it to 64k ;-)

**Comment by lvca** [comment]
Hey, 64k makes every login too slow... In order to authorize the login, OrientDB must execute 64 iterations per login to check if the hash is good. Anybody know any safe technique to avoid it? Like caching the password in RAM only?

**Comment by lvca** [comment]
We could have a stupid LRU as Map<String,String> populated with the computed password, so before to compute an hash, the cache is queried. WDYT?

**Comment by lvca** [comment]
Ok, with a LRU times are much better. I'm going to push this solution. I've create a new setting or it.:

```
  SECURITY_USER_PASSWORD_SALT_CACHE_SIZE("security.userPasswordSaltCacheSize",
      "Cache size of hashed salt passwords. The cache works as LRU. Use 0 to disable the cache", Integer.class, 500),
```

**Comment by compensator** [comment]
https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet

**Comment by compensator** [comment]
https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2015/march/enough-with-the-salts-updates-on-secure-password-schemes/

**Comment by obi1kenobi** [comment]
SHA-1 is a broken hash function:
https://www.schneier.com/blog/archives/2005/02/sha1_broken.html

If using PBKDF2, please use the PBKDF2-HMAC-SHA-256 variant which is still considered secure.

**Comment by lvca** [comment]
The article reports "(although it doesn't affect applications such as HMAC where collisions aren't important)". We use `PBKDF2WithHmacSHA1`, so it's not affected by it.

**Comment by obi1kenobi** [comment]
That quote is out of context: HMAC refers to both a message authentication code which happens to use a hash function and a specific technique for constructing such a code specified in [RFC2104](https://tools.ietf.org/html/rfc2104). Using SHA-1 for message authentication via HMAC is still okay (as the quote says), but PBKDF2 is not trying to authenticate a message, and instead uses the HMAC construction from RFC2104 to generate a password hash, where collisions are important.

Furthermore, even if all of the above were wrong, there is absolutely nothing to be lost by switching to PBKDF2-HMAC-SHA256 -- that algorithm is certainly no less secure than the SHA-1 version.

**Comment by lvca** [comment]
Switching to PBKDF2-HMAC-SHA256 is easy. I'm just worried about users that are running v2.2.0-SNAPSHOT, but the algorithm is encoded in the password, so it's retro compatible.

**Comment by obi1kenobi** [comment]
I completely agree. Not to mention that the best time to switch is before a GA release goes out :)

**Comment by lvca** [comment]
;-)
