### ISSUE TITLE
Orient should not set it's own log formatter [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#187]
This is [Issue 187](http://code.google.com/p/orient/issues/detail?id=187) moved from a Google Code project.
Added by 2010-12-23T17:01:10.000Z by [jcestiba...@gmail.com](http://code.google.com/u/111147715897599544217/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium
### Original description

```
The class OLogManager sets a formatter in code, which replaces the application configuration.

This is specially problematic when Orient is used embedded because all the loggers will start using Orient's formatter.
```

**Comment by ErikShiken** [comment]
Is there a way I can vote for this to be prioritized? I'd like to show I would like to see this enhancement in Orient

**Comment by zerovian** [comment]
This creates all sorts of problems because it stuffs ${ANSI into log file output and I haven't figured out a way to turn it off.

I've tried setting OGlobalConfiguration.LOG_SUPPORTS_ANSI to false...that doesn't work.  I've tried setting system property "orientdb.installCustomFormatter" to false...that doesn't work.
