### ISSUE TITLE
Incremental Backup with plocal

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#2029]
We have LSNs (log sequence number) in plocal so we can store last LSN during backup and then only backup pages which has bigger LSN and left everything also outside. Merge should be obvious in such case.

**Comment by lvca** [comment]
How much space takes the WAL? I'm worried about it, while a dedicated log would be much smaller.

**Comment by laa** [comment]
We do not need wal for this, consider following.
We have list of numbers and we need filter out numbers which a less then given one. By numbers I mean LNSs for each page.  We can read last lsn from backuped db. And then filter out pages which has less lsn, it's performance will be pretty close to check databases performance. That is why we can use  it to measure inc. backup perrofmance. We need wal only if we do not want to block database at all. I mean ok we know that we started backup lets say at LSN 42, last lsn in wal, and we do copy diff of data to other location. if we want to have db keep and running we need to copy wal starting from LSN 42 after we copied all the data.  But from start I think we should do blocked backup and then unblocked backup later. We need to look at all nuances at last case.

**Comment by lvca** [comment]
We could create a gzipped file with all the operations with LSN > than requested.

**Comment by laa** [comment]
Live incremental backup is implemented.
It means that current version of incremental backup has following features:
1. You do not copy data of whole database every time, you merely copy data which were changed after last backup.
2. For most of the cases your database will NOT work in read only mode, you will work with database "as usual", but operations speed will be a bit slower.

To make backup from Java API use com.orientechnologies.orient.core.db.ODatabase#incrementalBackup(String path). Where path is path to the folder where all backup files (with .ibu extension) will be kept.
To restore database perform following steps: 
1. Create empty database.
2. Call com.orientechnologies.orient.core.db.ODatabase#incrementalRestore(String path). Where path is path to the folder where all backup files (with .ibu extension) are kept.

To make backup from console use the command : backup  database <path> -incremental. Where <path> is path to the folder where all backup files (with .ibu extension) will be kept.
To restore database from console use the command : restore database <path> -incremental. Where path is <path> to the folder where all backup files (with .ibu extension) are kept.

What does mean phrase "for most of the cases your database will not work in read only mode" ? Because we do not apply lock on data modification operations during backup we track all changes are done to the data during 
period when we start backup to the period when we finish backup in database journal. Then at the end of backup storage copies this journal to the backup file. So to make journal data consistent 
we wait at the end of backup till all data modification operations will be completed and only then  we "cut" database journal and allow to continue to perform next data modification operations. 
Typically it matters of milliseconds. But if you have huge transaction with many operations on it, users may experience delay (till this transaction will be finished) in their data modification requests.

**Comment by smolinari** [comment]
That sounds like a pretty cool feature Andrey. Thanks for the hard work. :+1:

Scott

**Comment by laa** [comment]
@smolinari Thank you :-)

**Comment by finid** [comment]
@laa, this is really cool. Thank you. This is expected in v2.2, right?

**Comment by laa** [comment]
Yes sure, now we integrate new projects under orientdb project, it will take couple of days. After that you may try it from maven snapshot repository or from source code (it is in develop branch)

**Comment by nagarajasr** [comment]
@laa is it possible to restore from a previous backup e.g., incremental backup1 -> lots of data deleted accidentally -> incremental backup 2 now we want to restore from backup1 how can this be done?

**Comment by laa** [comment]
@nagarajasr do you mean is it possible to restore only from part of backups not whole set ? Now it is not implemented but it may be possible. I think we should introduce 2 commands one will show you list of backup files and last time stamp of change in database it is called LSN for each backup. Then you run incremental backup and provide lsn up to which you wish to restore your database. It does not need a lot of work. If you are interested in such functionality you could create issue. It will take not more than one day, 2 at most.
