### ISSUE TITLE
Performance degradation  after deleting all vertices

### ISSUE THREAD

**Issue by egyMaak** [orientechnologies/orientdb#2244]
I develop a small application to insert 500K nodes to OrientDB (using version 1.7-rc2) It take around 47.3 seconds.  From the studio i run query "delete from Person", then i run the application again, but in this time it takes 501.6 seconds !!

Here is the code:

public class PerformanceTest {

	TransactionalGraph g;
	public PerformanceTest() {
		connect();
	}

	public void connect() {
		String dbURI = "remote:localhost/peopleGraph";
		OrientGraphFactory factory = null;
		factory = new OrientGraphFactory(dbURI).setupPool(1, 10);
		g = factory.getTx();
	}

	public void add() {
		long tOut, tIn = System.currentTimeMillis();
		for (long i = 0; i < 500000; i++) {
			Vertex v = g.addVertex("class:Person");
			v.setProperty("ID", i);
			v.setProperty("name", String.format("name-%06d", i));
                        // commit EVERY 100 records
			if (i % 100 == 0) g.commit();
		} 
		
		g.commit();
		
		tOut = System.currentTimeMillis();
		System.out.println(String.format("Procesing time %f",
				(tOut - tIn) / 1000.0));
	}
	private void close() {
		g.shutdown();		
	}
	public static void main(String[] args) {
		PerformanceTest t = new PerformanceTest(); 
		t.add();
		t.close();
	}
}

**Comment by Kikimora** [comment]
Hi, I wonder if this issue was resolved?

**Comment by laa** [comment]
Hi,
This issue will be resolved with new cluster design .

**Comment by Kikimora** [comment]
Hi @laa , thank you for quick reply! It is being a year since this issue first created and 2.0 already out (I guess). Can you share some specifics on what is causing this issue and how new cluster design resolve it?

I have very limited knowledge of OrientDB but what I learned lead me to think that OrientDB record ID point to physical location of data on disk. This is why it is blazing fast at traversing rows - conventional database has to lookup physical locations in indexes while OrientDB just read data right away. 
If my assumption is correct then you cannot move records inside database file which means that over time something like 'memory fragmentation' will happen and this will slow down not only 'deletes' but all 'updates'.

I was puzzled with above question when I found this issue in google and  I wonder if this issue has anything to do with my question.

Thank you very much!

**Comment by laa** [comment]
Duplication of https://github.com/orientechnologies/orientdb/issues/5267
