### ISSUE TITLE
query count of vertices is wrong using DICTIONARY Index

### ISSUE THREAD

**Issue by egyMaak** [orientechnologies/orientdb#2245]
I insert the following dataset into OrientDB (graph DB / plocal ) 

running the following query from the studio: 
           select count(*) from Person where ID >= 100

1. With no index on ID property: 
          the result will be 10 (CORRECT)
2. With DICTIONARY_HASH_INDEX Index on ID property: 
          the result will be 10 (CORRECT)
3. With DICTIONARY Index on ID property: 
         the result will be 5 (which is WRONG)

N.E:  ID is Long and name is String

@rid @version @class    ID   Name
  #11:10	1	Person	100	name-000000
#11:0	1	Person	0	name-000000
#11:2	1	Person	2	name-000002
#11:3	1	Person	3	name-000003
#11:4	1	Person	4	name-000004
#11:5	1	Person	0	name-000000
#11:6	1	Person	1	name-000001
#11:7	1	Person	2	name-000002
#11:8	1	Person	3	name-000003
#11:9	1	Person	4	name-000004
#11:1	1	Person	1	name-000001
#11:11	1	Person	101	name-000001
#11:12	1	Person	102	name-000002
#11:13	1	Person	103	name-000003
#11:14	1	Person	104	name-000004
#11:15	1	Person	100	name-000000
#11:16	1	Person	101	name-000001
#11:17	1	Person	102	name-000002
#11:18	1	Person	103	name-000003
#11:19	1	Person	104	name-000004

**Comment by Ziink** [comment]
Since DICTIONARY and DICTIONARY_HASH_INDEX  are supposed to be unique indices, seems like DICTIONARY_HASH_INDEX   is the one giving the wrong result as there are 5 unique IDs >= 100

**Comment by maggiolo00** [comment]
hi @egyMaak 

i'm closing this.
This is the normal behaviour 
If you see here
http://orientdb.com/docs/2.1/Indexes.html#index-types
are unique but case of duplicate key  they replace the record id

So to better explain your case

1. Correct as it does not use the index
2. Correct as it does not use index since HASH index type does not support range query
3. Correct as it uses the DICTIONARY index and for the same key only one get indexed with the last record id

Example
#11:12 1 Person 102 name-000002
#11:17 1 Person 102 name-000002

only the latest one gets indexed
