### ISSUE TITLE
Support embedded rid bag in distributed mode

### ISSUE THREAD

**Issue by enisher** [orientechnologies/orientdb#2362]
- [ ] implement support embedded rid bag in distributed mode
- [ ] forbid usage of tree-based rid bag in distributed mode

Sub-issue off #1604.

**Comment by laa** [comment]
it is already implemented otherwise graph database would not work on distributed server.

**Comment by laa** [comment]
@lvca why you reopened it ?

**Comment by laa** [comment]
If it is not implemented how graph database is working in distributed mode ?

**Comment by lvca** [comment]
Sorry, I commented but PrjHub didn't write the comment. It's working in distributed mode, but we disable the TREE rid bag to get it working: `RID_BAG_EMBEDDED_TO_SBTREEBONSAI_THRESHOLD=Integer.MAX_VALUE`. In this way it never transforms to a tree. This was a temporary fix waiting for the distributed support. So that's why I reopened the ticket.

**Comment by laa** [comment]
It is not critical now. The most critical thing now is multi-core scalability . So it is moved to next version.

**Comment by laa** [comment]
already fixed
