### ISSUE TITLE
OrientDB didn't populate current OUser to remote storage

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#2523]
Situation is following:

1) By default reader/reader has been used to access DB
2) If user authenticated we do rights elivation by db.setUser
3) But finally: if everything is ok on "client side" (java application) - server side is responding that reader doesn't have required rights.

So, it seems that db.setUser is working only for local jvm and OUser isn't being populated to remote storage.

**Comment by MarcinMichalik** [comment]
I have the same problem.

I add to myClass for some records _allReader for reader user.

```java
ODatabaseDocumentTx db = new ODatabaseDocumentTx("remote:localhost:2422/myDB").open("admin", "admin");
OSecurityUser user = new OSystemUser("reader");
db.setUser(user);
OConcurrentResultSet<ODocument> documents = db.query(new OSQLSynchQuery<>("select from myClass"));

// I get all records from myClass
...
```

**Comment by tglman** [comment]
hi @MarcinMichalik,

For get a session with different user you should do a new open, you cannot set the user in this way skipping the authentication.

I'm going to close this issue as invalid because the setUser API is going to be removed in future versions, and actually it shouldn't have been public in the first place. The only way to switch user is do an open with the specified user.

Regards
