### ISSUE TITLE
Warning if disk space is low

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#2879]
In case the space on disk is finishing we should print warnings and avoid to write data, but rather return this error:

```
WARNING: low available space on the disk. Increase the available space or move the database to a different disk/partition
```

**Comment by lukaszkaleta** [comment]
On auto growing mounted file systems (like AWS EFS) it is difficult to run orient db with those checks.

**Comment by laa** [comment]
@lukaszkaleta do you mean that we do not amount of free space before head ?

**Comment by lukaszkaleta** [comment]
@laa I changed the orient check for free space to lowest 1MB (<entry value="1" name="storage.diskCache.diskFreeSpaceLimit"/>) and then it started to working. 
But with default settings I was somehow not able to even create database. You can experiment with AWS EFS and see. Since now it is working for me I do not know if something is needed to fix. But please you decide.
