### ISSUE TITLE
Auto close of storage when no used anymore

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#3055]
Now the storage remains open, but with remote connection. The ideal would be closing non used storage after a while. I propose my idea:
- use a counter on OStorage impl that is incremented at every usage, method `addUser()`
- in `removeUser()` mehod, when the returning number of users is == 0, then start a new TimerTask that, after a configurable number of seconds, run and close the storage

This also resolve the flush of WAL when the storage is not more used.

**Comment by laa** [comment]
Will be fixed in issue #3111

**Comment by laa** [comment]
I think would be better to create LRU list of storages with defined limit and auto close the least used storage.  

P.S. Eventually would be cool to migrate to LIRS alghorithm

**Comment by lvca** [comment]
:+1

**Comment by rohitdev** [comment]
If we are not going to shutdown storgae then in multi tenant scenarios where a vendor chooses ODB for repository it might become a big issue!

**Comment by laa** [comment]
Sorry, could you elaborate why it will be big issue ?

**Comment by rohitdev** [comment]
In an isolated database approach for multi tenant , when embedded DB is used the storage will never be shut down unless the JVM is shutdown or the server reboots.

**Comment by laa** [comment]
I do not understand.
Could you provide use case and list problems which may be raised during
this use case.

**Comment by rohitdev** [comment]
Due to the nature of product i work on i would not be able to give you exact deatils but will put in some general scenario.

A software collects raw data from different entities using various protocols. This raw data is then processed and kept in embedded DB for presentation layer per entity (The data needs to be loaded on demand only hence the choice of having a instance per entity as well as for security reasons) Now the software runs as a system service and in production environment where the server would not reboot for months. So in a month we would be collecting several instances of database from a single entity. Now there would be thousands of entities in production which eventually means that since the database doesn't close storage/files on shut down we would have thousands of file handles open thus hampering the OS operations.

Another of my friend who is running a SaaS product wanted to use ODB as a backend for his application. His model for SaaS is an isolated database per customer. He was looking around to replace MySQL with some NoSQL solution. The amount of data is not much but he has higher need of security and to reduce network latency. For this reason he choose an embedded DB. Now the application server runs for months again and the same issue of file handles remain open for the lifetime of the app server. So he is now hesitant to use ODB as a replacement.

**Comment by laa** [comment]
problem is gone after refactoring of file class
