### ISSUE TITLE
Getting error while restoring orientdb database backup to blank database

### ISSUE THREAD

**Issue by rajeshrolen** [orientechnologies/orientdb#3099]
I am getting this error while restoring database from backup to blank (without any schema) database.
Error: java.io.IOException: The process cannot access the file because another process has locked a portion of the file.

![image](https://cloud.githubusercontent.com/assets/6376368/5197280/cf1b4a50-7565-11e4-90df-358d89be8c72.png)

**Comment by Strider22** [comment]
I'm doing a different process, just trying to do a simple ETL load (per the udemy class), but I get the same error. It's unclear why this issue was closed. It looks like rajeshrolen has proper Java settings. Maybe that's what worked for him. I have proper settings, but am still getting the same error. If there's something else that fixed rajeshrolen's issue I'd be interested.

**Comment by Strider22** [comment]
As an FYI for others, if I change
"file":{"path":"../people.csv","lock":true}
to 
"file":{"path":"../people.csv","lock":false}
everything works. That allows me to at least complete ETL. 

Prior to the change I did make sure no other processes were running, the server was shut down and rebooted my machine, so I unless some OrientDB processes leave stale locks lying around the locking should not have been the problem. If there are admin commands to check for locks that would be of interest.
