### ISSUE TITLE
Import database issues OrientDB Server v2.0-M2

### ISSUE THREAD

**Issue by Bretto** [orientechnologies/orientdb#3137]
When I export my db:
@rid       @class:AppData     data                _allow
#12:27                                   "my data"        #5:2

and Import it with:
import database C:/myDB.export -preserveClusterIDs=true -rebuildIndexes=false

I get: 
@rid       @class:AppData     data                _allow
#12:0                                     "my data"        #5:2

So the cluster ID is preserved but the Index was rebuild, is this a bug ? or Am I misunderstanding something ?

**Comment by obendt** [comment]
I am having the same issue in 2.0.10 using the exact syntax as suggested by lvca above. Still the @RID is being rebuilt (with the exact behavior as described by Bretto.) 

Since i have external references from my app to the @RIDs i need them to stay the same after exporting and importing the database.

**Comment by Bretto** [comment]
This problem was never resolved for me either...

**Comment by naman53** [comment]
I am facing same problem. Is this problem is solved in any version?

**Comment by thomasdemoor** [comment]
+1. Having still the same issue. Is this solved in any version? Just want to keep @rid's when importing...

**Comment by ebonavita85** [comment]
It is fixed in the release 3.0.0?It will be fixed?

**Comment by tglman** [comment]
hi,

This is not guaranteed at the storage level, and is done by design.

Regards
