### ISSUE TITLE
Client: Improve Load Balancing

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#3165]
We could use Hazelcast also for the auto-discovering by clients. This would allow to avoid using DNS or a static list of servers. Furthermore it would be interesting creating connections to multiple servers to execute commands by using a round-robin strategy or simply to get data from a shard without any forward from other servers.
- [x] Auto discovery of clients using Hazelcast
- [x] Connection to multiple servers from client
- Multiple connection modes:
 - [x] ROUND_ROBIN_CONNECT, pick a new address from the list at connect time
 - [x] ROUND_ROBIN_REQ, pick a new address from the list before every request

**Comment by vertex-github** [comment]
Auto-discovery sounds like a great feature, until you come to deploy to any cloud provider - none of the providers we use (or looked at) support multicast, so everything has to be done via IP address.  We ended up writing a custom script to obtain our list of currently assigned internal IP addresses, which we then feed both to the firewall and Hazelcast (we use Hazelcast directly on our platform).  

If there was an API within OrientDB to tell the OrientDB platform about other servers then that would be useful, since we could then hook into it with our existing script.

**Comment by lvca** [comment]
@vertex-github This is a good idea. We could add an additional API in OSrvAdmin to add/remove servers. I know Hazelcast is configurable at run-time, but I'm not sure if you can add servers in easy way.

**Comment by lvca** [comment]
My idea was to allow different connecting strategies (the client already know all the available servers):
- **sticky**, the default, like now: connect to one server and switch only if it's unreacheable
- **round-robin**, it connects to all the available servers and execute queries using round-robin algorithm
- **balanced**, executes the query on the less loaded server

**Comment by machinelearner** [comment]
@lvca  Lot of these makes sense. I think i had mentioned this in one my previous mail,  but, one thing to consider is to balance load which accounts for data locality. With *sharding* in place, its perhaps a good idea to detect nodes which can potentially answer some of the indexed/partition aware questions so that you avoid loading nodes and connections over the wire which eventually will defeat the purpose of load balancing. 

Once that is in place you'll need to think about rebalancing shards on cluster expansion(if that is applicable, forgive me I don't remember the intrinsic details of the shard principles in OrientDb) and so on..
Does that makes sense?

**Comment by lvca** [comment]
The client already receives the cluster shape in push, so once this change is done, it will be able to get any rebalancing.

**Comment by machinelearner** [comment]
Fair, but I'm assuming there is nothing in place which will account for query routing based on partitions yet as they all hit the same node. Thats something to think about.

**Comment by lvca** [comment]
Query executor already has this concept and it's user server side to do the map/reduce magic. In this case the client could parse the query and get all the involved clusters, so decide to directly address the best node for that query.

**Comment by machinelearner** [comment]
Makes sense. This also means the cluster state is now perhaps a queryable entity(unlike the distributed-config.json) as the client and server can potentially maintain this state in a similar fashion? Does that also mean that for a database with a large set of cluster(the partition and not the node) would have to transfer a lot of this info on failure and during node-state change. 
How does the addition and expansion of cluster(the partition) get propagated to the client? If the frequency of writes is high and if the number of clusters is going to increase as a result of that, the interaction between client(s) and the layer managing the distributed-setup to exchange meta on the shape of the cluster is going to be very high. Any thoughts on how that is going to be handled, does hazelcast help(i'm assuming this help is going to be non-durable)?

Forgive me for asking too many questions. I want to understand the effect of introducing this without disturbing some of the goodness of the current distributed behavior.

**Comment by lvca** [comment]
The same as for #3829.

**Comment by lvca** [comment]
@machinelearner are you using sharding?

**Comment by lvca** [comment]
Implemented in develop branch (v2.2.0-SNAPSHOT). It's missing only documentation to close this issue.

**Comment by lvca** [comment]
Docs: https://github.com/orientechnologies/orientdb-docs/blob/master/source/Distributed-Configuration.md#load-balancing.

**Comment by machinelearner** [comment]
Hi @lvca,
I've almost moved away from the previous assignment. 

But no, due to issues related to distributed setup, we did not actively peruse sharding(although the Orientdb was primarily because of data load sharing). 
I looked at the docs, many questions unanswered. Will go through the commits and get back to you with questions.
