### ISSUE TITLE
fail to create a network of memory-only databases

### ISSUE THREAD

**Issue by luigidellaquila** [orientechnologies/orientdb#3203]
Scenario: 
- start a distributed server
- create an in-memory database
- start another distributed node

the fist node tries to execute a backup to share the db and fails (cannot execute a backup on an in-memory instance)

**Comment by lvca** [comment]
The reason is about backup/restore: they works only with physical databases. In this case we could use export/import.

**Comment by laa** [comment]
Yes guys but we can do Output/Input Stream on in memory db case. I think we should consider this too.

**Comment by lvca** [comment]
I don't understand.

**Comment by fridgebuzz** [comment]
I would like to be able to create (and drop) distributed in-memory databases at run-time. That is, while all the nodes are running, not just during startup. I'm not sure if this enhancement makes that possible or not. If it does not, can someone please let me know so that I can create a separate issue/enhancement request?

**Comment by lvca** [comment]
Right now this isn't supported.

**Comment by lvca** [comment]
In case of in-memory only database we could do an export/import.

**Comment by lvca** [comment]
This will be supported in v3.0
