### ISSUE TITLE
"Database X is closed" floods server log on console termination

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#3260]
In console.bat, I ran:

explain select id from Item

Unlike "select id from Item", the console does not apply LIMIT 20, so it was really slow. That's fair enough, but SIGINT killing the console leaves the server in a state where it keeps trying the query but rapidly spams error log entries saying that the database WikiData is closed. It looks like the server does some cleanup on disconnect (e.g. close the DB), but doesn't clean up running queries fully.

**Comment by laa** [comment]
It is binary protocol issue assigned to @tglman

**Comment by tglman** [comment]
yes, when you shutdown a client the server don't kill all running operation of the specific client, we kill just the idle worker, the reason is that the current implementation doesn't recognize if the running operation is safe to be killed (like a select) or not (like insert/update/delete), so we wait till the operation finish, we already have planned the fix for this behavior but won't be included in 2.0.

The other problem is that the shutdown of the server don't send the correct signal to the running workers, I'm going to fix that for 2.0

**Comment by lvca** [comment]
@tglman all the command implementations has the method isIdempotent(), so we could simply check it: if it's idempotent (like select and traverse) we could do that. WDYT? Is that easy?

**Comment by tglman** [comment]
this is fixed now, closing
