### ISSUE TITLE
support disk based transactions

### ISSUE THREAD

**Issue by luigidellaquila** [orientechnologies/orientdb#3463]
In current implementation, some operations like ORDER BY, GROUP BY and also transactions, are executed in heap memory.
This leads to OutOfMemory exceptions when working with big transactions or with big result sets. 

When system has low memory, transaction data should be swapped on a disk-based structure, so that the operation can be completed without errors, even with lower performance.

**Comment by laa** [comment]
Luigi you propose is the same issue already created issue https://github.com/orientechnologies/orientdb/issues/2022 . Because our transactions right now absolutely disk based.  Also we already discusses this question with you in chat. Why do you call this feature "disk based transactions". It is not true.
Because:

1. It is misleading. 
2. This issue duplicates two issue, one I mentioned bellow, second one is https://github.com/orientechnologies/orientdb/issues/2874 . 

WDYT ?

**Comment by laa** [comment]
Duplication of https://github.com/orientechnologies/orientdb/issues/5504
