### ISSUE TITLE
Embedded type in schema : OValidationException

### ISSUE THREAD

**Issue by MarcelPitch** [orientechnologies/orientdb#3511]
Hi,

We're using **orientDB 2.0 Final**

When declaring a schema for a Vertex class User as following :
```
uid = STRING
val = EMBEDDED
```

If we execute this query
```SQL
CREATE VERTEX User CONTENT { "uid" : "123", "val" : { "foo" : "bar" }}
```

or this one
```SQL
CREATE VERTEX User  SET uid = "123", val : { "foo" : "bar" }
```

We have this exception :
`
com.orientechnologies.orient.core.exception.OValidationException: The field 'UserEmbedded.val' has been declared as EMBEDDED but an incompatible type is used. Value: {foo=bar}
`

If we remove the val property from the schema, all works fine.

**Comment by Ndrou** [comment]
:+1:

**Comment by vitorenesduarte** [comment]
try:
```sql
insert into User  SET uid = "123", val = { "foo" : "bar" }
```

**Comment by MarcelPitch** [comment]
Hi @vitorenesduarte,

Your query works !

But in a base graph, I don't know if it's a good practice to use `INSERT INTO` instead of `CREATE VERTEX`.

And we have the same problem with `UPDATE`.

**Comment by lvca** [comment]
Actually CREATE VERTEX and INSERT are compatible.

**Comment by lvca** [comment]
However this should work:

    CREATE VERTEX User  SET uid = "123", val = { "foo" : "bar" }

**Comment by vitorenesduarte** [comment]
I can't make it work.
And just noticed this:
```sql
insert into User set val = {"foo" : "bar"}
```
returns
```json
        {
            "@type": "d",
            "@rid": "#12:4",
            "@version": 1,
            "@class": "User",
            "val": {
                "@type": "d",
                "@version": 0,
                "foo": "bar"
            }
        }
```

And
```sql
insert into User set val = {"@type":"d", "foo" : "bar"}
```
returns
```json
        {
            "@type": "d",
            "@rid": "#12:5",
            "@version": 1,
            "@class": "User",
            "val": {
                "@type": "document",
                "@version": 0,
                "foo": "bar"
            }
        }
```

**Comment by tglman** [comment]
Hi All,

The current behavior is correct, if not specified `"@type":"d"` the json block is considered as map, so of type EMBEDDEDMAP instead of EMBEDDED, if you remove the property il get the type at runtime and will be EMBEDDEDMAP

so the correct queries are:
`CREATE VERTEX User CONTENT { "uid" : "123", "val" : {"@type":"d", "foo" : "bar" }}`
and 
`CREATE VERTEX User  SET uid = "123", val = { "@type":"d", "foo" : "bar" }`

if you want to check what is the actual type of a field of a document you can use something like:
`select val.type() from user`
