### ISSUE TITLE
SELECT MAX(id) FROM SomeClass returns 0 rows when no rows

### ISSUE THREAD

**Issue by vertex-github** [orientechnologies/orientdb#3568]
OrientDB v2.02

except every other SQL engine we've tested against returns 1 row with a null value in the first and only field in the ResultSet.

Could OrientDB follow this convention?

This was also referenced here: https://groups.google.com/forum/#!topic/orient-database/i3Ow8jHv8Gg

**Comment by StanAccy** [comment]
With the new-fangled-super-SQL parser thats in 2.1, could this issue be fixed sooner? These minor diversions from de-facto SQL really make it difficult in porting applications from a traditional RDBMS to OrientDB.  The impact of these smaller issues on the dev team during porting is surprisingly significant in terms of time (so much so that we suspended our port attempt for a second time)

**Comment by lvca** [comment]
Fixed long time ago.
