### ISSUE TITLE
Recycle Bin

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#3651]
This is an interesting feature:

http://www.javacodegeeks.com/2012/12/recycle-bin-in-database.html

**Comment by w3aponx** [comment]
We actually use OrientDB in a similar fashion in that we don't necessarily delete a vertex just because it's been removed by a user from our application UI, but keep it around in a special area in case the user wants to undo his changes.  We would definitely leverage database-level support for something like this if it became available.
An interesting aspect would be to have scoped recycle bins, because for example in our case we want a recycle bin per user session.  If the user closes its client application, there is nothing to undo anymore so we can empty the garbage he generated.

**Comment by lvca** [comment]
Not relevant anymore, closing it.
