### ISSUE TITLE
Improve binary serializer avoiding writing the class name

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#3742]
But rather the classId.

**Comment by tglman** [comment]
Aa today we don't have a class id, we can easily define it in the class and use it as reference, but we need to fix before the cluster drop on Class drop, as today we just drop the default cluster, this could leave corrupted data in the clusters not deleted.

an alternative workaround could be the same used for the properties, i'm not a fan of that solution because leave some data on the schema that is never deleted, so better fix the class drop instead.

**Comment by tglman** [comment]
this solution need also to handle a backward compatibility with the binary protocol for the 2.0

**Comment by lvca** [comment]
+1 to fix cluster drop first. Which issue is it?

**Comment by tglman** [comment]
no issue open on that, i just opened it: https://github.com/orientechnologies/orientdb/issues/3997 i knew that from the code and is quite easy to test and fix. 


the must troubling step will be the network binary compatibility for the java clients 2.0.

the problem is that the java client 2.0 read record binary v0, and is not aware of binary "v1" (or anyway the implementation that replace class name length with id).

the possible solution of that case are:

* force the network to use every time binary 2.0
* create a matrix with association (network version):(record version) can be quite tricky to maintain in long term
* create a network indipendent format from the disc format, this may fit in a bigger network refactor.

the third point i think cannot(and should not) be done for 2.1, i think the first point and the second point are quite similar a solution and i need something like 1.5 days for do that. i do prefer the first one because could be the base of the future refactor, but still if we don't have to do it now i could do a better solution than stick the network to binary v0.

so before get start the main issue i need a couple of days of other fix.

bye

**Comment by lvca** [comment]
Which driver implemented binary protocol 2.0, Java apart? AFAIK the Go Lang driver only. If there are no drivers, let's pass from now the binary protocol version on handshaking) and the compatibility should be guaranteed by us. Actually the client should pass the version and we should use that version with it.

**Comment by tglman** [comment]
there is no need to add the version of the record serialization, could be mapped from the network version, let's say 28:0 29:1, the work to do is in the server side to manage both.

**Comment by lvca** [comment]
ok

**Comment by GoorMoon** [comment]
@lvc, I am implemented binary serialization in .NET driver but it still in
the testing

**Comment by lvca** [comment]
@GoorMoon if you are still in dev. phase it's not a problem by updating the protocol with this improvement.

**Comment by GoorMoon** [comment]
@lvca could you please clarify the improvement i don't understand it.

**Comment by lvca** [comment]
We can avoid storing the class name at all, since a cluster can only contains records of declared class.

**Comment by acmeguy** [comment]
Are there other features behind the "Compression of used space on serialization" item on the 3.0 roadmap?

**Comment by lvca** [comment]
You can find the roadmap here: http://orientdb.com/docs/last/Roadmap.html.

**Comment by acmeguy** [comment]
That line in the roadmap, you linked to, only points to this ticket :) 
i'm wondering what other changes will be made in regards to space efficiency.

**Comment by lvca** [comment]
Got it. We're also working to the design of a new command `compact database/cluster/index`.

**Comment by lvca** [comment]
No more relevant, we can totally avoid storing the class name in v3.0. closing it.
