### ISSUE TITLE
getVertices(String,String[],Object[]) returns results from other classes

### ISSUE THREAD

**Issue by Desidero** [orientechnologies/orientdb#3889]
This started as a question in stackoverflow, but it looks like there's a bug...

Basic issue:

1. Create ClassA (extends V) -> Create properties String A, String B, String C -> Create unique composite index on (A,B,C)
2. Create ClassB (extends V) -> Create property String J -> Create index on J (not sure if this property/index matters)

3. Add a record to ClassA ("foo","bar","ed)

4. orientGraph.getVertices("ClassB", new String[] {"A","B","C"}, new String[] {"foo","bar","ed"})

Expected result is no records returned since we did the search on ClassB. The actual outcome is that we retrieve the record created in step 3 which is from ClassA.

Please see this post (especially the comments) for more information: http://stackoverflow.com/questions/29474506/orientdb-getvertices-not-working-with-java-generated-class-index

**Comment by vitorenesduarte** [comment]
I believe this happens with __getVertices(String label, String key, Object value)__ too.

**Comment by Asimovtech** [comment]
I"m using OrientDB 2.1

I found the same error while trying to do

    graph.getVertices("User.display_name", "test100")

to get only vertices of type User that have display_name property set to test100

I also have Registration objects that have property display_name set to test100 

I got a vertex of type Registration, instead of User, 

I have currently fixed this by using

    graph.getVertices('User', new String[]{"display_name"}, new Object[]{"test100"})

Is there a bug or am I doing something wrong?
