### ISSUE TITLE
Add PHP and Python driver in the Continuos Integeration

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb#3940]
as subject

**Comment by robfrank** [comment]
Instead of integrating third party drivers on our CI infrastructure, I modified their build scripts in a way they can fetch SNAPSHOTs packages from Sonatype. This way, with a cron job on travis (https://docs.travis-ci.com/user/cron-jobs/) they can test clients against last build. It will be my care to open PRs after our releases to update their version matrix
