### ISSUE TITLE
sql - Count(*) statement limits the result set and returns wrong count

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#3993]
OrientDB Server v2.0.7
Driver: Oriento

That's my query:
````
fetchPlan = 'References:0 parent:-1 rid:0';

select COUNT(*) as count, @rid as rid, $depth as level, Mid as userid, Points as points, Position as position, Active as active, DisplayName as displayName, SponsoredBy as parent from (traverse References from (select from Node  WHERE Mid = '5530e925e8e7ccc81dca3cd4' ) ) where $depth >= 1 and $depth <= 1 and Mid <> '5530e925e8e7ccc81dca3cd4' order by displayName desc skip 0 limit 20
```

*Issue 1:*
This query should matched 4 entrys. When I execute the query with a fetchPlan I get only one item with a `count` of **1** but in the sql studio of **4**.

*Issue 2:* 
When I remove the `COUNT(*)` statement I get 4 entrys otherwise 1 entry.

Are these issues fixed in release 2.1-RC1 cause the new parser ?

**Comment by StarpTech** [comment]
Tested against 2.1-RC1 and still occurs.

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

aggregate functions like count(*), when used without a GROUP BY can return unpredictable results.
I think this issue is related to this, more than to fetchplan.
The same query is supposed to return one single row also in Studio, could you please confirm?

Thanks

**Comment by StarpTech** [comment]
@luigidellaquila  What do you mean with unpredictable result ? According to the documentation this is the correct way to count all not null records. http://orientdb.com/docs/last/SQL-Functions.html#count Why I have to use the `group by` clause for just counting my records?

**Comment by luigidellaquila** [comment]
Hi @StarpTech ,

of course you can use it alone (no other projections) without a GROUP BY, eg.
```sql
select count(*) from Person where name = 'Dustin'
```
is a valid query

but when you add other projections you have to use the corresponding GROUP BY, eg.

```sql
select count(*), age from Person where name = 'Dustin' group by age
```

**Comment by StarpTech** [comment]
@luigidellaquila this sounds like an issue. There are two types of `count(*)`

- Count of the total numbers of records which the query affects
- Count of the total numbers (by using as an aggregate function)

Does it mean that I have to use `count(*)` like 
`select count(*), age from Person where name = 'Dustin' group by @rid`
to count all my records of my query without any grouping (because grouping could lead to other misleading behaviour when I just want to get the count)?

Reference: http://www.mysqltutorial.org/mysql-count/

**Comment by nagarajasr** [comment]
maybe i have not understood the problem well, but what i think is that when you want to retrieve additional fields along with count(*), it does not make sense at all without a group by clause. presumably the query returns multiple rows of data and since you want the fields retrieved for each row, the count does not make sense for each row unless you group the data by some field, is it not? and conversely if you want only the total count, you do not need to retrieve the individual fields.

**Comment by StarpTech** [comment]
yes, correct but what is when I want to retrieve the total number of records which my query affects plus my custom projections without any grouping ?

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

if you look at MySQL docs (the link you posted), you will not find a count(*) with other projections without a GROUP BY. Actually MySQL behavior is exactly the same as OrientDB.

The query you propose
```sql
select count(*), age from Person where name = 'Dustin' group by @rid
```
will not be of help, just because it will return a row for every record in the class, and the count(*) will always equal to 1

This other query will make more sense instead:
```sql
select count(*), age from Person where name = 'Dustin' group by  age
```

If you are interested in all the names, plus the global count, you can try this
```sql
select name, $count[0]['count'] as count from v let $count = (select count(*) from v)
```
or this
```sql
select name, $count[0]['count'] as count from v let $count = (select count(*) from v) group by name
```

but I cannot guarantee that it's very efficient...

**Comment by StarpTech** [comment]
ok thanks @luigidellaquila @nagarajasr
