### ISSUE TITLE
Integration with MongoDB

### ISSUE THREAD

**Issue by danieljoppi** [orientechnologies/orientdb#4049]
Hi there,

Its possible integrate OrientDB with MongoDB? You know any framework can do this?

**Comment by PhantomYdn** [comment]
What do you want from integration of this kind? Synchronization between 2 DBs? If yes - why is it important for you? Might be you want to use some functionality from MangoDB and another from OrientDB?

**Comment by danieljoppi** [comment]
Not synchronization all data ... I think about relationships between collections in MongoDB ... map this edges in the OrientDB ... and to improvement all search in the system

like this: https://github.com/pstaender/mongraph (MongoDB + Neo4J)

**Comment by PhantomYdn** [comment]
Interesting, but with OrientDB you already have DocumentDB and GraphDB in one. So the only reason to integrate, that I see: keep 2 DB updated. But your case can help to understand needs.

**Comment by StarpTech** [comment]
I'm using orientdb with MongoDB. OrientDB stores all Graph data in relationship with MongoDB users.

OrientDB -> Graph data, traversing...
MongoDb -> All application specific data (users, profiles...etc)

 I use this seperation also because some security aspects.

OrientDb is awesome in using with the SQL like syntax. If you only use the basic features then orientdb makes his job very well. But the farther I go into orientdb the more bugs are found. Also the tooling for the community edition is not the best. The studio is very buggy and intuitiveness looks somewhat different.

**Comment by PhantomYdn** [comment]
Btw, I'm working on "alternative tooling" for OrientDB: https://github.com/OrienteerDW/Orienteer

**Comment by StarpTech** [comment]
Looks interesting. I will have a look at it.

**Comment by maggiolo00** [comment]
@StarpTech 

Which tool are you using for MongoDB.
How Studio is so buggy and not intuitive?

**Comment by StarpTech** [comment]
I use RoboMongo http://robomongo.org/
No statistics, no metdata about the inner of your big graph. You can't execute transactions.

**Comment by danieljoppi** [comment]
@PhantomYdn my problem is the mongoose models ...  my projects in node.js use mongoose ...

@StarpTech you use mongoose ??

I'm thinking about developer new framework to substitute mongoose in node.js projects ... only with OrientDB ...

**Comment by StarpTech** [comment]
@danieljoppi no, I use the native module https://github.com/mongodb/node-mongodb-native

**Comment by lvca** [comment]
Ok, closing this issue.
