### ISSUE TITLE
Hook not trigger on distribute mode when update record

### ISSUE THREAD

**Issue by henryzhao81** [orientechnologies/orientdb#4070]
I have a problem when using distributed mode, when I try to update record  e.g. Update #xx:xxx set value = xxx. Before update hook not triggered on Local Server. 

After debug, look like runMode in ODatabaseDocumentTx.callbackHooks() is RUNNING_DISTRIBUTED, but if I execute insert command, runMode is DEFAULT which is correct. 

     Did some further debug, looks like when execute update, onMessage function triggered in ODistributedWorker, and runMode was set to Distributed mode. That mean even execute on local server, ODB treat as remote server which is not make any sense. After check the code on ODistributedStorage.command function, line 243 (executionMode = ((OCommandDistributedReplicateRequest)exec).getDistributedExecutionMode();). If command instance is OCommandExecutorSQLInsert, executionMode is LOCAL. But if command instance is OCommandExecutorSQLUpdate, executionMode will be REPLICATE. 

     Check getDistributedExecutionMode function in OCommandExecutorSQLUpdate.java, return LOCAL mode only when upsertMode equals true. My question is, Is it by design to replicate the request when update? Do I need add upsert when execute update to make it behave same as insert? Or it just a bug.

**Comment by lvca** [comment]
This was by design. The reason is that INSERT must be executed on one server, because the RID must be unique among servers. With UPDATE, instead, the command is sent to all the server that work in local.

I think we could introduce a new keyword to decide at run-time how to execute the UPDATE. Makes sense. WDYT?

**Comment by henryzhao81** [comment]
If this is by design, i think we definitely need a extra key word to make the behave same as insertion, because there are some logic in my implementation of beforeUpdateHook, update on local first then propagate to remote server without triggering hook

**Comment by lvca** [comment]
By analyzing further this problem there is no a win-win solution. In case of sharded database, the command can't be executed on LOCAL node, but on all involved nodes, because local node couldn't have a portion of records.

Furthermore, in case of command like `UPDATE V set total = 100`, if V had 1M of vertices, this generates 1M of small distributed replication call, instead of 1 with the command.

Let's see your use case deeper: why don't you set execution = BOTH in your trigger and do you manage both situation when UPDATE happens on LOCAL and TARGET nodes?

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
