### ISSUE TITLE
query returns old copy of document (OrientDB 2.0.8) : caching issue?

### ISSUE THREAD

**Issue by rjackson64840** [orientechnologies/orientdb#4099]
For our testing we are using the InMemory DB, but we have same issues with remote.

After we update a document with ODocument.save() (inside a transaction) and then turn around and run a query for that same document we are getting the previous version returned.

In the cases where we're using the load() method with a record ID, to fix it we passed in the flag to the load method to ignore the cache.  That fixed the issue, but effectively renders the cache useless.

In the cases where we're running a query to locate a document the only way we could get it to work correctly was to fetch the document twice - first run the query to locate the document based on one or more field values.  Then, we use the record ID of the doc we just fetched and do a load() on that same document, again telling the load() method to ignore the cache.

	protected ODocument getOne(String queryStr, Object... params) {
		List<ODocument> results = runQuery(queryStr, params);
		ODocument doc = null != results && results.size() > 0 ? results.get(0) : null;
        if (null != doc) {
            //@todo - workaround to bypass local cache
            doc = getDb().load(doc.getIdentity(), null, true);
        }
        return doc;
	}

The unit test is like this:

* REST service 1 fetches document (version 1 returned, let's say)
* document updated on client (unit test code)
* REST service 2 used to save (UPDATE) changes (document should be version 2 now)
* REST service 1 called again to fetch updated document (without the double read above version 1 is erroneously returned)

When I step thru the above code, just prior to the load() call the document is reporting as version 1 with the old field values.  Once load() is called with a cache bypass the document now correctly reports version 2 with the updated field values.

**Comment by lvca** [comment]
Have you already tried to use the `NOCACHE` keyword in the SELECT?

http://orientdb.com/docs/last/SQL-Query.html

**Comment by rjackson64840** [comment]
Thanks.  Will use that and expect it will fix that case.  I have other
cases where we navigate to linked documents based on the original query
and that uses neither load() nor query - will try using a fetch plan on
the original query/load and adding in the NOCACHE keyword.

Thanks!

Russ

**Comment by jbaldassari** [comment]
Hi.  I just came across this thread after experiencing the same strange behavior on 2.0.15.  Is this a known bug?  I couldn't find anything in the list of issues, and this behavior is still present in the most recent 2.0 version.  Is it considered a best practice to add ```NOCACHE``` to _every_ ```SELECT``` statement if you want the database to return the correct result for a record that has been updated?  Maybe this is fixed in 2.1; I haven't had a chance to try that yet...

**Comment by smolinari** [comment]
Puh, I am confused, again.

The more important question is, does the cache ever get refreshed, and if so, when? Or is this some strange scenario for the database? To me, it makes no sense whatsoever to have to call `nocache` all the time to get the most up-to-date version of a document. How does the client ever know when the cache is refreshed, so `nocache` can be removed? 

Actually, forget all that. I would think the freshness of the cache should be up to ODB, meaning, if an update occurs, ODB would automatically refresh the cache. Why is this not the case? Sounds like a bug to me too.

Either it is a bug, or we aren't understanding the engineering. Some enlightenment on how the caching is supposed to work would be very helpful. Why is `nocache` even necessary? The fact it is there makes no sense to me.

Scott

**Comment by jbaldassari** [comment]
I'm not exactly sure what OP's setup looked like, but my only dependency is orientdb-core and I get stale documents back when I query after inserting and then updating.  This is all within a unit test as well, no separate server/client.  I would think that any update would automatically invalidate the cache.  That's what most people would expect after working with any other database (except maybe some edge cases like eventually consistent databases with concurrent writers).  If it's necessary to add ```nocache``` to every single ```select``` in order to guarantee that you are getting the most recent data then nocache should be the default behavior.

**Comment by smolinari** [comment]
Which would mean whatever cache the `nocache`bypasses is actually completely useless IMHO. 

@lvca or @luigidellaquila can you please shed some light on what `nocache`is all about?

Scott

**Comment by vlasni** [comment]
Using community edition v2.1.12 and experiencing similar caching issues. 
While adding NOCACHE to SQL statements fixes some cases, we are using graph api and don't see how can I set something like NOCACHE when doing something like vertex.getEdges(....). 
Any tip?

**Comment by CrazyChris75** [comment]
Using 3.0.0RC1 (Feb 2018) I still see this issue!

<dependency>
	<groupId>com.orientechnologies</groupId>
	<artifactId>orientdb-client</artifactId>
	<version>3.0.0RC1</version>
</dependency>

1st thread:
ODatabaseDocument db = dbPool.acquire();
db.begin();
// load and change data
db.commit();

2nd thread running immediately AFTER commit of 1st thread (Spring TransactionSynchronizationManager afterCommit)
ODatabaseDocument db = dbPool.acquire()
db.begin();
db.load(id); <-- gets old/stale data!!!
db.commit();

adding a Thread.sleep before acquiry in 2nd thread helps and also doing
db.load(id, null, true);

but - like people here before me have pointed out - this is definitely not desired behaviour since the commit of the 1st thread MUST invalidate/flush/reload the data in the cache

please let me know if i am doing anything wrong and why this thread has been closesd in May 2015 when the issue still exists 3 years and 3 mayor version updates later? Thx!

**Comment by izhangzhihao** [comment]
With version "2.2.35", I deleted some vertices, but when I query, the deleted vertices comes back!!! But when I try to delete the vertex again, it says:

```
com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id *** was not found
	DB name=***
```
