### ISSUE TITLE
ODocument.fieldType for vertex property returns null until the vertex is reloaded

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4222]
If I create a vertex, set its property (e.g. of ArrayList type), perform commit and then try to get the property type using v1.getRecord().fieldType("listProperty"), null is returned. If I perform v1.reload() and then get the property type - the correct value OType.EMBEDDEDLIST is returned.

**Comment by tglman** [comment]
hi @ylopotun 

the reason of this behavior come from the automatic filed type detection that in case of collection, change based on the type of the content for example:

```
ODocument doc = new ODocument(); 
List<Object> list = new ArrayList<>();
doc.filed("list",list);
doc.save(); // Here the doc.fieldType("list") should be OType.EMBEDDEDLIST
//But if i do this:
list.add(new ORecordId(3,10));
doc.save(); //  Here the doc.fieldType("list") should be OType.LINKEDLIST
//if you do:
doc.reload();
list.add(new ORecordId(3,11));
//the operation on the list doesn't effect anymore the of the field "list" in the doc, so can be set to OType.EMBEDDEDLIST
```

so this is an expected behavior, if you want it to keep the type from the start, you can use: `doc.field("list",list,OType.EMBEDDEDLIST)` or create a property in the class with the type specified.

thank you
bye
