### ISSUE TITLE
2.1-rc3 - Bug?: filtering vertices on classes using inV() or outV() doesn't work??

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#4279]
Hi I am trying to run this query:

```traverse outV('FactPersonal') from (traverse inE('FactContains') from #12:15 while $depth <= 1) while $depth <= 1 limit 10000```

![image](https://cloud.githubusercontent.com/assets/526062/7956363/624c4c8a-09ad-11e5-9078-b88fadb5a85f.png)

and I am getting all nodes.. it doesn't matter what I write in outV/inV actually..(i have cleared canvas)

![image](https://cloud.githubusercontent.com/assets/526062/7956430/d6d6d1d8-09ad-11e5-87b6-15e34c00adf7.png)

In my case FactPersonal and FactGeneral are subclasses of a common class 

Funny fact in any of those queries FactPersonal nodes are not even listed in Browse mode! Edit: That could because of studio issue: https://github.com/orientechnologies/orientdb-studio/issues/291

Version: 2.1-rc3

**Comment by maggiolo00** [comment]
@zifnab87 
that is because Studio graph mode render automatically lightweight edges (direct vertices rids). 
That is why  you see more nodes that in the Browse mode.

The Graph view will be refactored with the usage of another api to get the results in Graph format

https://github.com/orientechnologies/orientdb/issues/6214
