### ISSUE TITLE
[Question] Which is a more effective way of querying vertices?

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#4281]
Hi there,

Could anyone please explain which one of the following two queries is more effective and why, provided that it is applied on a large set of records.

*NOTE*: Second query has its `where` condition for a reason. Just assume that `myedge` may be pointing to different classes in this case.

1) Using graph traversals in the `where` condition:
```
select from ClassName where outE('myedge')[attr1='foobar'].inV().@rid=#123:0
```

2) Selecting from a traversal:
```
select from (
   select expand(inE('myedge')[attr1='foobar'].outV())
   from #123:0
)
where @class='ClassName'

**Comment by luigidellaquila** [comment]
Hi @andreyvk 

the second one is much more efficient, because it starts from a single point (loaded given its physical position, that is an O(1) operation) and then only connected elements are evaluated.
The first one has to evaluate every single node in ClassName and for each of them it has to do the whole traversal.

I'm closing this, if you need additional details please move the conversation on the community group ;-)

**Comment by smolinari** [comment]
Which is here: https://groups.google.com/forum/#!forum/orient-database

Or the chat here: https://gitter.im/orientechnologies/orientdb

Scott

**Comment by luigidellaquila** [comment]
thanks @smolinari ;-)

**Comment by andreyvk** [comment]
Thanks guys! This explains my question very well.
