### ISSUE TITLE
probably corrupted data from the network connection. Cleared dirty data in the buffer (5 bytes): [ÿôÿý]

### ISSUE THREAD

**Issue by SatishAMP** [orientechnologies/orientdb#4421]
com.orientechnologies.common.io.OIOException: Received unread response from /159.202.228.1:44849 probably corrupted data from the network connection. Cleared dirty data in the buffer (5 bytes): [ÿôÿý]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.orientechnologies.common.log.OLogManager.error(OLogManager.java:207)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.clearInput(OChannelBinary.java:371)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:219)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

**Comment by tglman** [comment]
Hi @SatishAMP,
this error say that, some data was not clean on the connection, this can happen in case of some other error it's happening in the meanwhile, do you have any other stack trace on the console?

anyway this error does not create problem on persistent data, and the connection is recovered automatically.

**Comment by SatishAMP** [comment]
Hi , What ever we updated in the issue that is the complete stack trace. This error resulted big problem where its stopped accepting the new connection and didn't recovered from that situtation. Eventually we restarted the process to circumvent the issue. As we are in distributed mode , when we do restart it starts replicating the complete DB from other embedded nodes caused 2 hours outage to production.

**Comment by tglman** [comment]
hi @SatishAMP,

This seems related to https://github.com/orientechnologies/orientdb/issues/4438, can you tell us what are you using as client, and what is the environment you are running?

The java implementation has a pool of 20 connection client side, so should never reach 1000

**Comment by SatishAMP** [comment]
We have multiple clients to OrientDb Server 1. Java client with binary integration , ETL (Informatica ) which will make http RESTAPi calls . We are running with 2.0.9 . Can you please let us kow how we identified that connections reached 1000 . I verified the similor issue you mentioned , that means we have to set the limitation in the Connection pool ?

**Comment by tglman** [comment]
Hi @SatishAMP,

The reasons that lead to this problem could be many, usually error on network reading/writing happen because of other issues, as i understood your environment is quite complex, and i think in your case is more luckily that the problem come from some overload. I'm aware that some orientdb consultant it's already helping you setting up the environment, and as soon as you have that done i'm sure this problem will not show up again.

For understand if your server has reached the limit of connection you should check the log for:
`WARNI Reached maximum number of concurrent connections ....`

but it's probable that is not this your issue now, an example if with high load you bring the server to out of memory, it could not finish to read all the data from a socket and bring to this issue.
