### ISSUE TITLE
Lucene index not  available in 2.0.11

### ISSUE THREAD

**Issue by jingjingbic** [orientechnologies/orientdb#4462]
The package is not available in repository. I tried to use back the 2.0.10 version of Lucene with 2.0.11 community server, but got errors.

**Comment by lvca** [comment]
Could you attach any errors you received?

**Comment by kstock** [comment]
The orientdb-lucene-*-dist.jar file is missing from the plugins directory  in the 2.0.11 download at http://orientdb.com/download/

In previous releases the jar file was included in the plugins directory.

This is particularly vexing because the issue
Lucene indexes are removed if lucene plugin is not installed
https://github.com/orientechnologies/orientdb/issues/3522

caused lucene indices to become inaccessible after a test upgrade.

**Comment by lvca** [comment]
Something went wrong during the release, however 2.0.12 fixed it.
