### ISSUE TITLE
RidBag as Linked List

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4489]
On massive insertion of a graph, the ridbag after a threshold (default=40), becomes a tree. The tree has a bigger insertion time than a linked list. The main advantage of a tree structure is O(LogN) on contains() and remove() operation, but could be never called on a graph used with query only.

If we implement a linkedlist, the insertion time could be close to O(1). In the vertex we could store the pointers to the head and tail of the linked list.

**Comment by laa** [comment]
Do you mean that we will not support removal of items in ridbag ?

**Comment by laa** [comment]
Linked list is obvious solution for ridbag, actually list, not linked list , we work on plain set of raw bytes (disk data) and as result we do not have pointers. But it was not implemented during designing of ridbag because of absence of ability to implement removal method in way which will not force users to wait hours because of copying disk data from one place to another. Will we not support remove method in list implementation ?

**Comment by laa** [comment]
Ridbag was implemented as tree not because of fast contains method, it was obvious that for set with duplications contains does not matter, but because of implementation of removal method on disk bassed data structures, disk data is not memory data and do not have pointers, it is continuous array of data, so it is possible to implement only list, not linked list, and list has very poor performance of removal in case data are removed from the middle or head of list. So my main question will we create edges without ability to remove them ?

**Comment by lvca** [comment]
The ability to remove edges remains, but it will be O(N) and add O(1). This could be used in all the use cases when you don't have delete of edges or when deletes occurs rarely and the price could be sustainable for the end user. This will NOT REPLACE ridbag, but they could be used when a property is set with `property.setOrdered(true)` in graph API. Now we're using a List, but a linkedlist is a better structure with big numbers.

**Comment by laa** [comment]
Aha I see thank you very much for explanation and sorry for misunderstanding, will do at next release.

**Comment by laa** [comment]
That is part of https://github.com/orientechnologies/orientdb/issues/4491 solution.

**Comment by laa** [comment]
Moved to 3.0

**Comment by laa** [comment]
Duplication of https://github.com/orientechnologies/orientdb/issues/4491
