### ISSUE TITLE
Use of Unsafe is going to introduce problems with Java 9

### ISSUE THREAD

**Issue by rmuller** [orientechnologies/orientdb#4648]
OrientDB makes a lot of use of the infamous `sun.misc.Unsafe` API. Is the development team aware of the problems this will give starting Java 9?

For an excellent opinion about this matter, see
https://jaxenter.com/javas-unsafe-class-there-is-certainly-also-a-way-without-it-119084.html

IMO the use of Unsafe for direct memory access is a suboptimization *for recent Java runtimes*  and should be avoided.

**Comment by laa** [comment]
Hi @rmuller 
I can not agree with you without direct memory we had situation when JVM was stopped for minutes not seconds also modern Java runtime in enterprise is Java 6-7 . 
But we aware of the problem. Still I think that we should start to develop alternative once we will be completely sure that we can not manipulate by direct memory using Unsafe in Java 9. Right now situation is not very optimistic personally I do not want to to have minutes stop the world for the project  but even earlier we had prototypes which do not include usage of direct memory and still very fast in performance so lets wait and see if Unsafe and direct memory pointers will be put in the past since Java 9 we have ideas and prototypes which will replace this approach without working directly with Java heap.

**Comment by rmuller** [comment]
Hi Andrey,

Thanks for your detailed reply. It's up to the OrientDB team to decide what to do with this issue. We (finally) do no use OrientDB in our application, so it will not have impact on us. I only posted this issue because i still have much sympathy for the OrientDB team and personally i am still very interested in its development. 

Note that I see the BIG advantage of using direct memory! However, my statement about  suboptimization refers to to use of `Unsafe`. The difference between using Direct Memory via the official API and the Unsafe usage is relative small (at most 10-15% @ Java 8). I bet (but cannot prove) in real world scenarios it is even (much?) smaller.
And yes, most enterprise environments still use Java 6 or 7. However, the adoption rate (also in the enterprises) of Java 8 is very high compared with previous versions. Your product should focus on long term stability and Java 8 adoption is "just around the corner". For Java 9 nobody knows, but why take the risk and uncertainty?
