### ISSUE TITLE
Limiting shortest Path depth

### ISSUE THREAD

**Issue by boriswexler** [orientechnologies/orientdb#4672]
I am currently unable limit the range of ShortestPath to not try beyond a certain depth in order to save processing - please add feature if possible.

**Comment by lvca** [comment]
We should support a JSON like arguments, where you can specify params easily like this maxDepth.

**Comment by Gerenatian** [comment]
Is there any way to query the maximum number of hops between any two nodes (and limit the query to stop searching three nodes out) without using the shortest path function? I would like to use orientdb, but cannot wait until 2.2 is out due to time constraints. For reference my data is 4.8 million nodes and 68 million edges.

**Comment by lvca** [comment]
@Gerenatian which driver are you using? By the way, OrientDB is extensible: you could always write your function in JS that support a limit. Look at: http://orientdb.com/docs/last/Functions.html

**Comment by Gerenatian** [comment]
I think I've found a work around for the time being, I can run a query like ```traverse * from #12:50151 while $depth <= 3``` and search for my destination vertex in the result set. It seems fairly quick. Thank you for the quick response Ivca!

**Comment by luigidellaquila** [comment]
V 2.2 includes A* (`astar()`) function, that allows to define a max depth of the path.

Closing

Thanks

Luigi

**Comment by Gerenatian** [comment]
Thanks for the update luigidellaquila. Thats a great addition.
