### ISSUE TITLE
Overriding 'in' and 'out' properties of edge breaks inV()/outV()

### ISSUE THREAD

**Issue by TropicalPenguin** [orientechnologies/orientdb#4684]
Hello,

Out of curiosity, I created an edge class with associated properties 'in' and 'out', both of Decimal type.

Although it is possible to create edges of this kind, and query them for given vertexes with `outE()`/`inE()`, it does not seem possible to query the vertexes associated with such an edge; `inV()` and `outV()` both result in:

`java.lang.ClassCastException: java.math.BigDecimal cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable [ONetworkProtocolHttpDb]`

Should these be reserved names for edge properties? Or is there alternative state that `inV()` and `outV()` implementations should use?

Tested on 2.0.12

**Comment by TropicalPenguin** [comment]
Same ClassCastException with attempts to `delete edge` for edges of this class.

**Comment by luigidellaquila** [comment]
Hi @TropicalPenguin 
there is no specific check on this right now, but I strongly discourage to override "out" and "in".
There is not way, currently, to let outV() and inV() use another field name.
The proposed solution for this issue is to just add a control and throw an exception in case a use tries to define out and in properties on an edge class with different types, or just if he tries to store values that are not links on these properties

**Comment by lvca** [comment]
This is very low priority, overriding of out/in would break the graph model, so just don't do that. We need a check for that. Thanks for reporting.
