### ISSUE TITLE
Functions with duplicate names

### ISSUE THREAD

**Issue by randikaf** [orientechnologies/orientdb#4751]
Orientdb can have function with the same name but while retrieving the functions from java api, using meta data as below, it needs the function name. How can I know which function is getting retrieve from the below code? Is there way to retrieve the function using its RID?
 `db.getMetadata().getFunctionLibrary().getFunction("sum");`

**Comment by matanshukry** [comment]
Are you sure orientdb can have a function with the same name?

As far as I can tell from the code, it's not possible.

**Comment by lvca** [comment]
@randikaf what's the purpose of having 2 functions with the same name?

**Comment by randikaf** [comment]
@matanshukry , Yes, if you try from the Orientdb studio, you'll be able to create.

@lvca Actually this happened accidentally because of a issue in my code. But the problem is, Orientdb does not validate the function creation with the same name.

Can I use the function name to retreive the function consistently?

**Comment by matanshukry** [comment]
@randikaf you're right, my bad; Was looking at a different function.

@lvca - IMO, function names should be unique. Now I'm not too familiar with indices, but we can create (by default) a unique index on OFunction.name, that should be simple enough. What do you think?

**Comment by randikaf** [comment]
@matanshukry , @lvca Are you planning to fix this?

**Comment by nagarajasr** [comment]
i also observed that when importing the functions only from an export file using '-merge' option, duplicate function entries are created. not sure if creating index on OFunction will solve the problem. i suspect that it would need a change to import command to 'overwrite' the function in case of import.

**Comment by matanshukry** [comment]
@nagarajasr - I am not familiar with the import process, but doesn't the process add entries to the OFunction table through the index? That is, shouldn't a unique index throw error on duplicate functions?

I think it's the best option since even if you fix the import function, one can still create multiple functions with the same name, which I don't think make much sense. Unless you're planning an using parameters overloading, but then you'll need a more complex unique process.

@randikaf - I can take a look at it, just looking for some confirmation from the Orient team; They need to decide how they want to fix it (unique index? overwrite? else? ..)

**Comment by luigidellaquila** [comment]
+1 for the unique index (in v 2.2 IMHO)

**Comment by nagarajasr** [comment]
@matanshukry yes, but i would expect that the import process should overwrite an existing function if the "-merge" option is specified
