### ISSUE TITLE
SQL Command - DELETE EDGE Not Cleanly Deleting?

### ISSUE THREAD

**Issue by compensator** [orientechnologies/orientdb#4766]
I executed a DELETE EDGE on the graph to cleanly remove all Edges of a particular type.  A SELECT \* on the affected Vertices displays a "[]" in Studio Browse output and the Edge label persists under the "IN" or "OUT" section.

**Comment by lvca** [comment]
@compensator it's not dirty: the collections remain, because the cost of removing them is higher than just set to 0 elements. However the traversing considers empty collection as no edge, so everything is consistent. We could support a new keyword, in DELETE EDGE command, or change the default behavior and use the new KEYWORD to have the current behavior.

**Comment by compensator** [comment]
So I have to filter the remnants from the returned data?  I also don't know what will occur yet when I execute various actions like adding an edge with the same name due to customer requirements change or error.

**Comment by lvca** [comment]
@compensator what do you mean for filtering? What's the use case that cause you problems with empty collections?

**Comment by compensator** [comment]
If Edge types are not utterly deleted, then a listing of the database schema types returns invalid values.

**Comment by tbertels** [comment]
I think there should be a way to remove completely any reference to those edges, be it by default or not.
And a note should be added to https://github.com/orientechnologies/orientdb-docs/blob/master/SQL-Delete-Edge.md
