### ISSUE TITLE
Lucene Spatial return invalid result 

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#4820]
i found out a bug as follows: 

select  *, distance(lat, lng, 3.1333, 101.3833)
from (SELECT EXPAND(OUT("target")) FROM #45:6)
where distance(lat, lng, 3.1333, 101.3833) <= 100

--- return a set of correct result 

select  *, distance(lat, lng, 3.1333, 101.3833)
from (SELECT EXPAND(OUT("target")) FROM #45:6)
where [lat, lng, $spatial] NEAR [3.1333, 101.3833, {'maxDistance' : 100}]

------- return nothing/empty result

**Comment by maggiolo00** [comment]
Hi @martingg88 

the second one do not works because the lucene spatial index is not used.
In order to use the spatial index the target of From must be a class.
In your case the target is a subquery

```
(SELECT EXPAND(OUT("target")) FROM #45:6)
```

I will fix it to evaluate the expression in via java (full scan) but it will not use the spatial index.

**Comment by martingg88** [comment]
thanks. let me know once u fix it. thanks.
