### ISSUE TITLE
Security level should be refactored to allow to use the same DB instance after renaming of user

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#4830]
Guys,

There is the following problem.
Step by step
1) Login into the OrientDB under someother (let say "myuser")
2) Rename user to for example "myuser2"
3) You still can get db from OPartitionedDatabasePool under old username and password and at the same time `getMetadata().getSecurity().getUser('myuser')`, of course, returns null.

**Comment by taburet** [comment]
Seem like there is no satisfying solution, I have considered following:

1. Detect the user name change and throw an exception on acquire. But the user name may be changed in a context of some other connection, so that is not reliable, especially for remote connections. Also, already acquired connections will continue their work like there were no user name change until they returned to the pool and reacquired from it.

2. We may try to compare the actual remote user name with the user name configured in the pool to overcome the problem with renaming from another connection, but that will give a performance penalty on each acquire call and will not solve the problem with already acquired connections.

We are trying to mix here the connection state management and the database state management, which should be separate. What do you think, @PhantomYdn?

**Comment by PhantomYdn** [comment]
Hi! My vision is that there is only one thing which can't be changed during user's lifecycle. I mean RID of a user. Can we try to make pooling working on RID instead of names? WDYT?

**Comment by laa** [comment]
@PhantomYdn @lvca good, but it pooling works on url level not on user level, so when do you mean and @lvca support such change it means that database security level should be seriously refactored. Assign it for @tglman to make such refactoring at has nothing to do with pool, because pool does not store username at  any place merely relies on db security.

**Comment by laa** [comment]
Changed name of issue to describe it's new intention.

**Comment by tglman** [comment]
Hi,

From my point of view we should not allow the user to be renamed, like on any other database engine if you want change the username you create a new user with the new username assigning the same roles, and you drop the old one.

does this point of view make sense to you ?

In case we have just to block the rename of the user makeing the property name readonly.

bye

**Comment by PhantomYdn** [comment]
@tglman , I can't agree with you:
1) RDBMS do allow to rename users: [MySQL](http://dev.mysql.com/doc/refman/5.7/en/rename-user.html), [PostgreSQL](http://www.postgresql.org/docs/8.0/static/sql-alteruser.html), [Oracle](http://www.dba-oracle.com/t_rename_user_schema_owner.htm) has some troubles with that, but it also possible.
2) I might agree if OrientDB is simple DB. But fortunately, OrientDB  proposes full stack for developers and quite often OUsers used on application level + OAuth. And unability to change user login name is quite bad story.

**Comment by tglman** [comment]
the 2.2.x is in maintainence, moving this to 3.x
