### ISSUE TITLE
Replace 2Q read cache by LIRS cache.

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#4869]
LIRS cache is as simple as LRU cache but copes with well known LRU problems like weak cache locality (file scan), loop like access  and so on.

2Q cache tries to mitigate this problems too but has bigger runtime and development overhead.

LIRS cache has now successfully adopted at least by MySQL, Infinispan, GridGain, Jackrabbit, H2.
All of this makes it worth to consider in our project too.

**Comment by laa** [comment]
LIRS efficiency chart https://db.tt/OAGZ73Ot

**Comment by ben-manes** [comment]
I'm slowly making some progress on this for [Caffeine](https://github.com/ben-manes/caffeine), but haven't had much time lately. There are some tuning parameters that need to be optimized. There's a simulator with my own LIRS version ~70% complete, but the existing implementations show (a) good hit rate comparatively and (b) tuning makes a difference.

The concurrency scheme is also important since LIRS, like LRU, is not thread-safe. The plan is to use both the buffering strategy for a concurrent LRU with a fast-path no-op if the entry is considered hot by LIRS.

I need to find the time to finish the simulator's LIRS version, tune it, and then port it into the cache. I didn't want to take an existing implementation blindly without verifying the efficiency, understanding the algorithm in detail, and be able to write reasonable test cases.

**Comment by ben-manes** [comment]
I made some headway here, which could be a template for you.

In the process, I invented a new caching algorithm that matches LIRS efficiency in a variety of workloads. It is much simpler and has a small fixed memory overhead (not variable like LIRS). It uses a probabilistic sketch instead of a large non-resident queue to retain historical frequency. I need to experiment further, but this might be a simpler alternative.

**Comment by laa** [comment]
All improvements in hit rate are very minor if there are at all. Will move it in far future.

**Comment by ben-manes** [comment]
@laa Do you have traces? I can run it through a simulator to show how different policies behave. TinyLFU appears to be the best in general, including database workloads.

**Comment by laa** [comment]
@ben-manes well it would be interesting. We will try to find time to create one and share with you. Thank you for help.

**Comment by laa** [comment]
Not actual
