### ISSUE TITLE
OrientDB takes 10x more time to run on graph mode

### ISSUE THREAD

**Issue by sajid2045** [orientechnologies/orientdb#4899]
I am trying to run our load tests on a 2.1.1 cluster of 3 nodes. The operations / group of operations that usually takes 1.5 sec in standalone mode, is now taking 15sec +  in clustered mode.

Is this normal?

**Comment by valeriotarenghi** [comment]
what type of test are you performing which returns this slowdown?

**Comment by sajid2045** [comment]
Its a mix of graph navigation and drop / add edge & vertex. In single db, the exact code takes max 1500ms , on clustered, it takes upto 20,000 ms

**Comment by valeriotarenghi** [comment]
Can you send me or upload with dropbox your server log file?

**Comment by MVdev1** [comment]
I am also noticing significantly slower performance.  In my case, I rebuilt the indexes just in case there was something and that took nearly an hour when it usually only takes 7 or 8 minutes.

Don't know how to give more useful information short of letting you on a box, which is possible.

**Comment by lvca** [comment]
@sajid2045 if you work with graphs, you should always use OrientGraph instances, not OrientGraphNoTx. This allows you also to speedup distributed operations because the entire TX is 1 operation instead of N. So my suggestions are: use TX and measure it again. In case you wanna go faster, use asynchronous replication.

**Comment by sajid2045** [comment]
Hi Luca,

As I said, I can't afford to have version updates on the Vertex for Edge
add / remove operations because that results in concurrent modification
exception.

However, I am happy to go with asynchronous replication. Can you point me
to the doc where i can configure it?

-Sajid.

**Comment by AlessandroRota** [comment]
Hi @sajid2045,

the documentation is the following :

In order to reduce the latency in WAN, the suggested configuration is to set executionMode to "asynchronous". 
In asynchronous mode any operation is executed on local node and then replicated. 
In this mode the client doesn't wait for the quorum across all the servers, but receives the response immediately after the local node answer. Example:

{
    "autoDeploy": true,
    "hotAlignment": false,
    "executionMode": "asynchronous",
    "readQuorum": 1,
    "writeQuorum": 2,
    "failureAvailableNodesLessQuorum": false,
    "readYourWrites": true,
    "servers": {
        "*": "master"
    },
    "clusters": {
        "internal": {
        },
        "index": {
        },
        "*": {
            "servers" : [ "<NEW_NODE>" ]
        }
    }
}

Also, you can find the documentation for asynchronous replication mode at this link
http://orientdb.com/docs/2.1/Distributed-Configuration.html#asynchronous-replication-mode

**Comment by lvca** [comment]
Hi @sajid2045,
Managing concurrent exception is a must if you have concurrent threads that change the graph. It's not big deal, you can just use a retry approach. Take a look at: http://orientdb.com/docs/last/Java-Multi-Threading.html#graph-api

**Comment by sajid2045** [comment]
I switched to getTx() now for graph update operations and using retry etc. 

But any update on the slowing down?

**Comment by sajid2045** [comment]
I switched to getTx() now for graph update operations and using retry etc. 

But any update on the slowing down?

**Comment by lvca** [comment]
Did you notice any improvement in performance by using one TX instead of multiple ops?

**Comment by sajid2045** [comment]
Yes, using Tx instead of noTx did improve the performance . However, it did introduced a lot of concurrent modification issue which we solved by pushing the graph update task in a single threaded mode.
