### ISSUE TITLE
DELETE VERTEX does not remove deleted records from Linksets 

### ISSUE THREAD

**Issue by chiavelli** [orientechnologies/orientdb#4903]
I have one vertex type called ```category```

Another vertex type contains a ```LINKSET``` property which links to the ```category``` class

I have deleted a category vertex using the following command:
```delete vertex category where @rid = 14:8```

I was expecting that this command would also remove the record from any LINKSETs which contained it, but unfortunately that is not the case.

Is this expected behavior, or a bug? Should I be going about this a different way?

I am using OrientDB 2.1-rc3

@lvca

**Comment by StarpTech** [comment]
@chiavelli in my opinion this is no bug because with `delete vertex` should only delete the vertex entity instead to break references across the graph. `delete edge` also removes just `edges` and not connected vertices.

**Comment by chiavelli** [comment]
According to the documentation here: 
http://orientdb.com/docs/2.1/SQL-Delete-Vertex.html 

The ```delete vertex``` command:
> takes care to remove all the cross references to the vertices in all the edges involved.

**Comment by StarpTech** [comment]
Yes you are right then this is a bug.

**Comment by lvca** [comment]
This is not a bug. OrientDB manages edges transparently, not any other LINKs you attach to the vertex. Why did you need a LINKSET rathe than modeling it by using edges?

**Comment by lvca** [comment]
By the way this is faster:

    delete vertex 14:8

**Comment by flyingrobots** [comment]
@lvca using this syntax: `delete vertex <type> #y:z` actually provides a type check prior to deleting the given record. If the record is of type `foo`, and you say `delete vertex bar #4:20`, it will actually NOT delete the vertex in my experiments.

Furthermore, I can see that using a `LINKLIST` would be equivalent to using lightweight edges. However, `LINKMAP` and `LINKSET` provide additional utility beyond that offered by an array of edges (associative lookup). While I understand that treating edges transparently keeps things explicit and straightforward, a "lightweight edge" seems to be more or less equivalent to a "link", with the exception that they are actually properly cared for when vertexes move or are deleted. Do "links" and "lightweight edges" have separate implementations? Consider whether they could (and should) be factored together, so that we can make use of built-in data structures which provide associative lookup for "lightweight edges" (links): `LINKMAP` and `LINKSET`, or retiring the concept of a "link" entirely, or making them unavailable in `graph` type databases, since they are apparently footguns.
