### ISSUE TITLE
JavaScript Server Side Functions 'null' [Feature Request]

### ISSUE THREAD

**Issue by MVdev1** [orientechnologies/orientdb#4948]
Calling server side javascript functions supplies a string with the letters "null" when the parameter is left blank.

Ideally, you'd have an empty string or a null in the variable you get in your server side javascript environment but for now I am testing for a string with the letters n-u-l-l.

REPRO:
1. Create a new javascript server side function with at least 1 parameter (using studio) - let's call it x.
2. Click execute without filling in any parameters

Notice that x will be "null" on the server.

You can return {aaa: x} to see the results or add code like this...

   if (x == null) return {"a":"null string"};   **<< Expect this**
   if (x == "null") return {"b":"string with n-u-l-l"};     **<<<<<<< Get this.**
   if (x.length == 0) return {"c":"empty string"};   **<< Could live with this**
   return {"d": x};

Results:

[
    {
        "@type": "d",
        "@version": 0,
        "b": "string with n-u-l-l"
    }
]

**Comment by luigidellaquila** [comment]
Hi @MVdev1 

If I didn't get it wrong, this issue is related to:
- the Function panel in Studio: this cannot be fixed, because the parameters are a simple HTML form, you cannot set a non-string value there
- HTTP API: in this case I really don't know how to support it, a URL is just a string, I cannot set a null value (and "null" is a valid string...)

Any suggestion is welcome

Thanks

Luigi

**Comment by maggiolo00** [comment]
This issue will be fixed once
https://github.com/orientechnologies/orientdb-studio/issues/445
is implemented
