### ISSUE TITLE
Speed up traversal and queries

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5034]
In order to speed up traversal and queries, we'd need to operate at lower level. To reach this result the first step could be providing these new API in Binary Protocol class:
- `long[] in(String... classes)`
- `long[] out(String... classes)`
- `long[] both(String... classes)`
- `Object field(String iFieldName)`
- `byte[] rawField(String iFieldName)`

The idea behind `in()`, `out()` and `both()` is to return a long[] of size entries \* 2. In this way the following array of RID:

```
[#10:2, #10:343, #232:34343]
```

Would become:

```
[10,2,10,343,232,34343]
```

So in RAM this is just `1` objects instead of `1+items`. While traversing thousands/millions of nodes, the GC will thank us. We could build a new class like `OBinaryIdentifiableIterable` that holds such big long[] object and allows to iterate on it.

`Object field()` returns a field value, but more interesting is `byte[] rawField()` that returns the portion of byte[] that contains the field. Thanks to this method we could support binary comparator at SQL Operator level with a method like:

``` java
boolean compare( byte[] first, byte[] second )
```

For example the operator "equals" (=) could compare byte per byte two values without create the Java object. We could support also the type, so `rawField()` could return a new Object of type 
`OBinaryValue { OType type, byte[] value }` so that we could also convert values inside the operators in compare().

This new low level methods could be used by new Pattern Matching executor to speed up the most common use cases.

**Comment by tglman** [comment]
Yes for speed up traversal we could provide some additional api, i would say that we don't need to remove completely the concept of iterator in favor of array, and it could actually create more slowdown due to the need of a full preallocation ( in big dataset).

i would define a different low level api for the 'query engine use' that should look like:
- `Iterator<ORecordID> in(int... clusters)`
- `Iterator<ORecordID> out(int... clusters)`
- `Iterator<ORecordID> both(int... clusters)`

with this api i can easily create an iterator on any kind of structure we have in the bottom (LINKLIST,LINKSET,RIDBAG embedded,RIDBAG tree, even only RID) and do lazy deserialization on that, and probably i can even implement it with a bidirectional (next/prev) behaviour.

to notice the id of the cluster instead of the class to avoid schema lookup and to filter record at priori without need to load them.

for a low level compare api i was think to something like

`int compare(byte [] record, string [] path, OValue value)`
for OValue i mean a structure alive for all the query run that can keep the value with all the possible/used serialized conversion, so the conversion can be done only once in the whole query.

can be defined even a kind of join compare api :
`int compare(byte [] record, string [] path, byte [] record1, string [] path1)`

i prefer not expose portion of serialized byte[], just as general design.

this api could even be exposed in  case of remote but i feel is an overkill today, most of the case fetch the whole record in remote is not to huge overhead, and in case of huge collections we already use OSBTreeBonsai that has a paginated fetching.

**Comment by lvca** [comment]
My comments:
- in/out/both must have also strings, because with that names we compute the field names that handle the collection of RIDs
- What's `string[] path` ?

**Comment by tglman** [comment]
in/out/both,  corrected.
i prefer to have a path[] that will match "field.secondField.third" and have a bit of logic to get the next record byte[] in the low level resolver to avoid the need of the query engine to manage if is an embedded or a link, an information that the higher level cannot have. considering also  the schemaless nature of the database for the same path i could have in one record everything embedded in another all link. 

anyway that could be solved in the same way returning an OBinaryValue and call multiple times the same api.

**Comment by lvca** [comment]
Not relevant anymore, closing it.
