### ISSUE TITLE
Why is that vertex persisted even though I am committing through different Tx?

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#5065]
Hello, 
I have this small example

		OrientGraph graph = factory.getTx();
		Vertex v = graph.addVertex("class:someClass");
		OrientGraph graph2 = factory.getTx();
		graph2.commit();
		graph.rollback();

from what i saw v  gets proper id after graph2.commit(), I thought that only graph can commit and do that.. These two graphs have different ids. On top of that when I rollback graph, the vertex is still there in the database :/. Could I have some explanation please? When I do getTx() from various places, it is safe to commit once on whichever of the objects? How does the system know that all these transactions are on the same thread or not ?

Thanks,
Michail

**Comment by urugator** [comment]
There is only single ODatabaseDocumentTx (used by multiple OrientGraph instances wrappers produced by factory) per thread and therefore a single TX per thread (owned by ODatabaseDocumentTx).
Following will be true if graph and graph2 have been produced in the same thread:
graph.getRawGraph() == graph2.getRawGraph()

Also note that it doesn't matter on which OrientGraph instance you calls shutdown(). It needs to be called the same times as you call getTx() in that thread.
So
graph.shutdown();
graph.shutdown();
will also close the graph2.
And if you call shutdown only single time on "graph", that instance will be still usable, because it's not actually returned to pool.

**Comment by zifnab87** [comment]
Thanks @urugator. I was forced to think that things were working in a different way because of this issue https://github.com/orientechnologies/orientdb/issues/5033#issuecomment-145730231. It seems it is a bug that made me think that way

**Comment by urugator** [comment]
I looked at your comment and I might have a few ideas.

First problem:
You got a pool with 10 connections and you try to get 1000 connections from that pool, without calling single shutdown().
If you would have read that OPartitionedDatabasePool documentation carefully, you will notice that pool throws an exception if pool is exahausted, instead of creating additional connections lazily.

Second problem:
By default the OrientGraph starts TX automatically. The tricky part is that TX is not started when it's needed, but there is actually always a transaction.
TX is started at OrientGraph creation and restarted at after every commit() and rollback() if needed.
So when you're entering to next iteration in that for cycle, there is already a running TX associated with that thread, that might interfere with your setup method (if you would use transaction there).
You can change that by factory.setAutoStartTx(false) (I don't recommend you to set that on graph instance directly, it will lead you to other problems). In that case you have to call begin() manually.
Also I recommend you to use the same factory also for that ODatabaseDocumentTx you use in setup method. You can get ODatabaseDocumentTx from OrientGraph by OrientGraph.getRawGraph()

**Comment by urugator** [comment]
I updated my previous comment.

**Comment by urugator** [comment]
Bottom line:
Use only one way to create your DB instances in a single thread (factory).
Keep in mind that in a single thread, all OrientGraph instances shares the same connection and same transaction.
Make sure you call shutdown() the same times as getTx().
Keep track of your transactions.

If you need more ODatabaseDocumentTx in a single thread, you need to realize, there is only one which can be currently active and which is used by existing OrientGraph instances.

**Comment by zifnab87** [comment]
Thank you @urugator - I really appreciate your detailed answer! I will read carefully the documentation you sent. I will update the other example in the question so it doesn't create classes on the fly.. btw it fails after 2-3 trials and not a thousand so that's why I don't understand it says closed for the database..

**Comment by laa** [comment]
It is already fixed in 2.1 version, will be in next hotfix.
