### ISSUE TITLE
EmbeddedRidBag: enhance concurrency

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5066]
Today embedded ridbag are stored in the owner document, so every change impacts the owner's document by updating the version too. This means that is impossible to add edges concurrently without a OConcurrentModificationException. Ok, the interesting thing is that the TreeRidBag has a different behavior: it never updates the version. So my proposal is: **embedded rid bag couldn't change the version but rather merge changes**.

Changes:
- [ ] EmbeddedRidBag must track add/remove (like tree rid bag)
- [ ] On document save check if no fields are changed and only embedded rid bags, then apply changes to the loaded document and save with the same version

WDYT?

**Comment by tglman** [comment]
yes, is a good idea,but for get it done it need a bit complex refactor, i explain:

In case of the tree all the changes are kept in a separate structure with a count, and at the moment of the save behind a lock(record lock in not tx, storage lock in tx) this changes are merged to a shared structure and flushed.

For do the same with embedded ridbag we should define a similar shared structure and serialize the embedded ridbag only after the merge. there are some issue with the current database design due to the fact that the record serialization is made at database level, and the shared structures/locks are at storage level.

In case of distribute it's even more complex.

another solution could be implement a merge strategy that in case of MVCC fail check if the changes are only in the embedded ridbag and attempt a merge, it may need some more information stored in the embedded ridbag though.

**Comment by laa** [comment]
@tglman +1 for merge strategy, imho making of shared structure from sate which is embedded in document impossible or at least will introduce so amount of bugs that we will fix them months.

**Comment by lvca** [comment]
@tglman the solution at conflict strategy is interesting, we already have an auto-merge where we could start with.
