### ISSUE TITLE
"Wrong user/password" error message when using SHA-256 hashed passwords

### ISSUE THREAD

**Issue by ajmazurie** [orientechnologies/orientdb#5078]
Hi,
I am currently testing the automatic deployment of OrientDB on some virtual machines. As part of this process I programmatically edit the `config/orientdb-server-config.xml` file to add a couple of users, namely `root` and `guest`.

Everything works fine when I provide plain text passwords; e.g., if I put

``` xml
<users>
    <user name="root" password="root" resources="*"/>
</users>
```

then I can login on the OrientDB console as expected: `connect remote:localhost root root`.

However, if I generate a SHA-256 hash of this password and store this instead:

``` xml
<users>
    <user name="root" password="{SHA-256}4813494D137E1631BBA301D5ACAB6E7BB7AA74CE1185D456565EF51D737677B2" resources="*"/>
</users>
```

then I get an error message in the console when attempting to log on:

```
orientdb> connect remote:localhost root root                     

Disconnecting from the database [null]...OK
Connecting to remote Server instance [remote:localhost] with user 'root'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot connect to the remote server/database 'remote:localhost/'

Error: com.orientechnologies.orient.core.exception.OSecurityAccessException: Wrong user/password to [connect] to the remote OrientDB Server instance. Get the user/password from the config/orientdb-server-config.xml file
```

From the documentation I expected the SHA-256 hashing to work, especially since that's currently how they are stored in the OUser table. Am I missing something? For information, I tried to store a lower-case version of the SHA-256 hash to no avail. I'm using OrientDB 2.1.3.

Best,
Aurélien

**Comment by santo-it** [comment]
Hi,

Thanks for opening this

I was checking some old issues and noticed this one


Starting from version 2.2, OrientDB hashes the passwords using PBKDF2WithHmacSHA256 algorithm if it's running on Java 8 or major, otherwise using PBKDF2WithHmacSHA1 with a configurable SALT (from doc: http://orientdb.com/docs/2.2.x/Server-Security.html)

I have double checked with 2.2.17 and 3.0.0-snapshot and indeed in the configuration file I see the hashed password, and when I try to connect to the server using the console or Studio it works

I believe it's safe to close this issue. Please comment if you are still affected or you feel this is current

Many Thanks,
