### ISSUE TITLE
Error querying a Lucene index with SQL based on a nested query 

### ISSUE THREAD

**Issue by arisAlexis** [orientechnologies/orientdb#5332]
given Classes User,Post 
and Edge Posts from User to Post
and given Post.body is a FULLTEXT LUCENE index then:

this works

SELECT FROM (SELECT EXPAND(OUT('Posts')) FROM User WHERE username='marco') WHERE body LIKE '%China%'

this works

SELECT FROM Post WHERE body LUCENE 'China'

**this doesn't work**

SELECT FROM (SELECT EXPAND(OUT('Posts')) FROM User WHERE username='marco') WHERE body LUCENE 'China'

error message is:

com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing command at position #0: LUCENE condition is allowed only when query target is a Class or an Index

**Comment by lvca** [comment]
I guess we already fixed this in 2.2.x. @maggiolo00 can you confirm it?

**Comment by maggiolo00** [comment]
@lvca we removed the parsing static check.

but this query will not use the lucene index since the target is not a class but a subquery. The condition will be evaluated in memory. I can remove in the next hotfix the static check also in 2.1.x since the memory index implementation has been ported in 2.1.x
```
SELECT FROM (SELECT EXPAND(OUT('Posts')) FROM User WHERE username='marco') WHERE body LUCENE 'China'
```

**Comment by maggiolo00** [comment]
hi @arisAlexis 

can you confirm that is fixed?

**Comment by lvca** [comment]
No answer since a while, closing it for now. In case please reopen/comment it.
