### ISSUE TITLE
documentation bug re "CREATE FUNCTION .... language javascript"

### ISSUE THREAD

**Issue by pkoppstein** [orientechnologies/orientdb#5388]
The following transcript illustrates there is a documentation bug on the page:

http://orientdb.com/docs/2.1/SQL-Create-Function.html

where it claims:

"language, optional, is the language. By default is "Javascript"."

```
OrientDB console v.2.1.5 (build 2.1.x@r; 2015-10-29 16:54:25+0000) www.orientdb.com
...
orientdb {db=diner}> CREATE FUNCTION test1 "print('Testing 1')" 

Function created successfully with id=#6:6

orientdb {db=diner}> select test1()

Error: com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.print('Testing 1')

orientdb {db=diner}> CREATE FUNCTION test2 "print('Testing 2')"  language javascript

Function created successfully with id=#6:7

orientdb {db=diner}> select test2()
Testing 2
----+------
#   |@CLASS
----+------
0   |null  
----+------
```

**Comment by smolinari** [comment]
The docs you've linked to is the SQL command reference. I am not sure, but if you look under the console command reference, `CREATE FUNCTION` isn't under those commands. 

http://orientdb.com/docs/2.1/Console-Commands.html

So, either the `CREATE FUNCTION` command is missing in the docs under "Console Commands" and this is a bug....

...... or the command was never meant to work over the console to begin with. If so, then I'd still call this a bug, as the command, if it isn't supposed to be supported by the console, should then return a "No such function" error and not strange results, contrary to the actual SQL command and possibly causing confusion with users.

Scott

**Comment by pkoppstein** [comment]
@smolinari - The key point that your post suggests you may be missing is that "CREATE FUNCTION" does work as expected (both for javascript and SQL functions) provided the LANGUAGE keyword is given.  Thus I think that your "either ... or ..." dichotomy is thus probably wrong as it's clear there are multiple deficiencies in the documentation.

**Comment by smolinari** [comment]
Only the ODB team knows......

The fact something works in certain situations could be a mistake. i.e. functions working over the console. 

It is either missing documentation and a bug, because the key word is necessary for JS functions to work over the console and functions aren't described in the console documentation or it is a bug with no missing documentation, because functions function over the console and actually shouldn't. Just because they do function partially doesn't mean it was intended. Put another way, if functions worked properly over the console, I'd be more reluctant to say the documentation is missing. 

Scott
