### ISSUE TITLE
Make the distributed mode reliable.

### ISSUE THREAD

**Issue by testark** [orientechnologies/orientdb#5403]
Following #2914, #5380 and also http://stackoverflow.com/questions/32893656/inserting-3500-objects-into-orientdb-takes-too-long and https://github.com/orientechnologies/orientdb/issues/5091#issuecomment-147479307, I would label the current implementation of the distributed mode as plainly *unusable*. I'm experiencing all kinds of problems and delays, and I can reproduce each of the issues I am quoting. @lvca has previously said that this will be fixed on a 3.0 release, but... we've just now reached 2.1.6. How much time will we really have to wait to get this fixed? For real...

**Comment by lvca** [comment]
For unusable do you mean you have issues or it's just because it's slow?

**Comment by smolinari** [comment]
If it is too slow, a database is also unusable. :stuck_out_tongue_winking_eye: 

Looks like #2914 is a problem with indexes being ignored in distributed asynchronous execution mode.
#5380 is a performance problem with mass inserting edges. Not sure which execution mode, async or sync.

On that, the standard default distribution config has "undefined" in it under execution mode. What execution mode does the system default to and why can't that be put in the config file as the default value instead of "undefined"? Or is the config set up properly, when the system is first put into distributed mode?

The [stackoverflow issue](http://stackoverflow.com/questions/32893656/inserting-3500-objects-into-orientdb-takes-too-long) seems to also be a problem with very slow performance on batch inserts in distributed mode.

#5091 doesn't deal with a distributed system. So, I am not sure what the relevance is. 

Scott

**Comment by testark** [comment]
@smolinari, I'll quote the relevant part from #5091:

> It is very hard to take orientdb serious when such simple things doesn't works. In almost every release there is a regression. Orientdb should be focused on qualitity not in features. This is my perspective in 6 month orientdb.

Looks like I'm not the only one who is dissatisfied.

@lvca I mean both. I do have issues. Sometimes one of the nodes stops responding. A simple `TRUNCATE CLASS` takes about 3 seconds. I get lots of "couldn't find best cluster for" errors and a lot of "quorum not reached" which makes the server exit. This, I'm afraid, means it's unusable.

**Comment by lvca** [comment]
@testark I see your frustration, but this is an Open Source project so you have mainly 2 choices:
- help finding the problem, or at least
- help us to reproduce the problem

In issue #2914 we have a test case, so please don't just say "This is still the case with 2.1.6.", but please provide a way to reproduce your problem, namely a **test case**.

**Comment by testark** [comment]
@lvca It's not hard to reproduce the problems I am refering to. All it takes is:

- Grabbing (at least) three VMs somewhere.
- Grabbing the OrientDB tarball and setup it in distributed mode on those VMs (stock configuration).
- Get a client to connect using `remote` and do some basic operations.

It's not that hard really. And regarding your last sentence,

> so please don't just say "This is still the case with 2.1.6."

Then please don't just say "can you try with latest version we've just released" when people report a problem, because that's the only single thing you've been telling me and everyone when a problem is reported. (I can provide evidence, if you need, though I won't really bother doing this right now as you know this is your usually *modus operandi*).

**Comment by ggoodman** [comment]
From the anecdotal perspective of someone wanting to take OrientDB into production, this makes me regret the time I've invested in building my project using OrientDB. It appears to me that the ambition of the project exceeds the resources to which it has access.

Is it really reasonable for users to be running serious non-embedded projects that are *not* using the distributed mode? How can you ever hope to set up HA without the distributed scenario being bulletproof.

I understand that this is an Open Source project and that it is unfair for me to have any sense of entitlement. However, it isn't clear to me that this project has the sort of focus that is suitable for production use as the primary database supporting a high-traffic website.

I would love to be convinced otherwise because on the surface the product is without match.

**Comment by lvca** [comment]
Issue #2914 is closed, what kind of problem @ggoodman are you experimenting? Default configuration? Could you tell us more?

**Comment by lvca** [comment]
Closing because no response, in case @ggoodman please provide the problem/error/test-case where doesn't work.
