### ISSUE TITLE
Class aliases in SELECTS

### ISSUE THREAD

**Issue by mdekrey** [orientechnologies/orientdb#5426]
In the demo "GratefulDeadConcerts" database, I am unable to find a way to use class aliases, even in simple queries. I am running community 2.1.6.

I have tried:

``` sql
select other.name as pseudonym from V other
select other.name as pseudonym from V AS other
select from V as other
```

(Note that the `as pseudonym` does work when I am not attempting the `as other`.)

It gives me an error like the following:

```
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Error parsing query: \u000aselect other.name as pseudonym from V as other\u000aEncountered \" <AS> \"as \"\" at line 1, column 39.\u000d\u000aWas expecting one of:\u000d\u000a    <EOF> \u000d\u000a    <WHERE> ...\u000d\u000a    <ORDER> ...\u000d\u000a    <GROUP> ...\u000d\u000a    <LIMIT> ...\u000d\u000a    <SKIP2> ...\u000d\u000a    <OFFSET> ...\u000d\u000a    <TIMEOUT> ...\u000d\u000a    <FETCHPLAN> ...\u000d\u000a    <LOCK> ...\u000d\u000a    <LET> ...\u000d\u000a    <NOCACHE> ...\u000d\u000a    <PARALLEL> ...\u000d\u000a    <UNWIND> ...\u000d\u000a    \";\" ...\u000d\u000a    <LET> ...\u000d\u000a    <WHERE> ...\u000d\u000a    <GROUP> ...\u000d\u000a    <ORDER> ...\u000d\u000a    <UNWIND> ...\u000d\u000a    <SKIP2> ...\u000d\u000a    <OFFSET> ...\u000d\u000a    <LIMIT> ...\u000d\u000a    <FETCHPLAN> ...\u000d\u000a    <TIMEOUT> ...\u000d\u000a    <LOCK> ...\u000d\u000a    <PARALLEL> ...\u000d\u000a    <NOCACHE> ...\u000d\u000a    <NOCACHE> ...\u000d\u000a    
```

I see that #1920 appears to be asking for the same thing, but was resolved over a year ago. What am I missing?

Thanks!

**Comment by luigidellaquila** [comment]
Hi @mdekrey 

it is not supported and probably it does not make much sense.
OrientDB does not support JOIN, so referring to two or more different classes in the same query is not possible.

If your goal is to use the class short name (http://orientdb.com/docs/last/SQL-Alter-Class.html) then you can just use it instead of the class name, eg.

```sql
select from other
```

What is the purpose for doing this?

Thanks

Luigi

**Comment by mdekrey** [comment]
Thanks for the quick response!

Like [Lebnik on this Google Code thread](https://groups.google.com/forum/#!topic/orient-database/NE803NtA0Tw) I am working on writing a driver - specifically, for Microsoft Entity Framework 7. Its inbuilt SQL generation classes use aliases inherently; I was trying to determine if that was a portion I needed to/should remove. Because only one source class is permitted, it makes sense. However, I felt the need to ask because #1920 seemed to imply that the feature was there and working.

Thanks again, @luigidellaquila! Feel free to close, though I will not because it was marked with a Milestone already.

**Comment by luigidellaquila** [comment]
Hi @mdekrey 

Ah, got it, so it's because of automatically generated queries. 

In this case I'll leave it open, but I'm afraid we won't be able to address for the release of 2.2 GA (we are reaching RC1 shortly), unfortunately it's not only a matter of parsing, but it also involves the query execution.

Thanks

Luigi
