### ISSUE TITLE
prepared statement with ? argument in LIKE clause returns no results

### ISSUE THREAD

**Issue by fac2003** [orientechnologies/orientdb#5481]
select * from X where name like '%?%' returns no results. Makes prepared statement unusable with like queries.

**Comment by fac2003** [comment]
This is against version 2.1.5

**Comment by StarpTech** [comment]
@fac2003 I try it with 2.1.8 and it works!

1. ```sql
create index Node.DisplayName on Node (DisplayName) FULLTEXT ENGINE LUCENE
```
2. ```sql
select * from Node where DisplayName LIKE "%?%"
```

**Comment by StarpTech** [comment]
@fac2003 I try it with 2.1.8 and it works!

1. ```sql
create index Node.DisplayName on Node (DisplayName) FULLTEXT ENGINE LUCENE
```
2. ```sql
select * from Node where DisplayName LIKE "%?%"
```

**Comment by luigidellaquila** [comment]
Hi guys, 

it works with Lucene because that expression is interpreted as a lucene expression.

If you do not have an index, you have to pass as a parameter a string that already contains the % characters, eg.
```
db.query("select * from Node where DisplayName LIKE ?", "%"+theString+"%")
```
Parameter names are never replaced inside strings, otherwise a query like 

```
select * from Question where text = "What's your name?"
```

would be impossible to do

Thanks

Luigi
