### ISSUE TITLE
incorrect calculation of disk free space causing failure

### ISSUE THREAD

**Issue by fommil** [orientechnologies/orientdb#5491]
```
[info]   com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'graph-2.0' due to limited free space on the disk (0 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 100 MB. Required space is now set to 100MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) .
```

but

```
df -h /tmp/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb5       7.4G  105M  6.9G   2% /tmp
```

**Comment by fommil** [comment]
argh, even setting that variable to 0 doesn't workaround this. Is it possible to disable the check?

**Comment by fommil** [comment]
oh come on

```
final long freeSpaceInMB = new File(".").getFreeSpace() / 1024 / 1024;
```

that isn't even on the drive that contains my database!

**Comment by fommil** [comment]
I seem to have no workaround for this. I can only guess that your implementation in `OWOWCache.java` or `ODistributedCounter.java` is broken (or `getFreeSpace` can't be trusted).

```java
  public boolean checkLowDiskSpace() {
    final File storageDir = new File(storagePath);

    long freeSpace = storageDir.getFreeSpace();
    long effectiveFreeSpace = freeSpace - allocatedSpace.get();

    return effectiveFreeSpace < freeSpaceLimit;
  }
```

But I can assure you that I have multi-GB free on all my partitions.

**Comment by fommil** [comment]
(gets out the dusty manual for overriding methods with reflection...)

**Comment by fommil** [comment]
workaround

```scala
OGlobalConfiguration.DISK_CACHE_FREE_SPACE_LIMIT.setValue(Long.MinValue / 1024L / 1024L)
```

seems to be holding up, but this is really evil.

I almost did an unspeakable thing and hotswapped `g.database.storage.writeCache = myOWOWCache`.

Obviously, it'd be called `SuchHackManyInsaneOWowCache`.

**Comment by laa** [comment]
Fixed

**Comment by fommil** [comment]
cool, do I need to do anything to get the fix or will it apply automatically?

**Comment by laa** [comment]
It will be in next 2.1 release.

**Comment by jbfm21** [comment]
Hello Iaa, do you know when this fix will be released?

**Comment by jbfm21** [comment]
Hello, i detect one problem in this method:

     final long freeSpaceInMB = new File(".").getFreeSpace() / 1024 / 1024;

If the user (or a service user), that is running orientdb, doesn´t have read access to the driver (parent disk folder, ex: D:\) where the lib orientdb.jar is installed, then the method always return 0 Mbytes of free disk space, not a SecurityException.

**Comment by laa** [comment]
@jbfm21 Why do you think we use `new File(".")` ? We use new File("<path to the storage>").

**Comment by jbfm21** [comment]
The method autoConfig (com.orientechnologies.orient.core.config.OGlobalConfiguration.java) use new File(".")

**Comment by laa** [comment]
@jbfm21 I see thank you very much. This algorithm is definitely incorrect I will remove it , though it does not related directly to calculation of free space inside of cache.

**Comment by ComeMaes** [comment]
Hello, I am trying to use orientdb with Amazon EFS and are running into problems that seem related to this issue.

The EFS volume is mounted in orientdb containers (official 2.2.8 image) to directory `orientdb/databases` 

If I mount the EFS volume on an instance and run `df -hT /home/ec2-user/mount_point/` I get the following:

`file system                                                                    Type  Size  Used  Avail. Used%  Mount`
`XXXX.efs.YYY.amazonaws.com:/   nfs4   8,0E     0     8,0E   0%       /home/ec2-user/mount_point`

When I run one server container, and run the console in another one to try to create a database, here's my console output:

`orientdb {server=remote:orientdb/}> create database remote:orientdb/test root root local`
`Creating database [remote:orientdb/test] using the storage type [plocal]...`
`Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot create the remote storage: test`

`Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'test'`
`	DB name="test"`
`	DB name="test"`

`Error: com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'test' due to limited free space on the disk (-8796093022208 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 256 MB. Required space is now set to 256MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) .`
`	DB name="test"`

So there is that obvious negative free space left on the disk number. As EFS volumes are supposed to be virtually infinite, I suspect the 8,0E size given by the `df` command correspond to some kind of largest possible integer value. Therefore my initial supposition would be that orientdb misinterprets this number as signed, but I have not investigated this much deeper.

Any hints about this?

**Comment by laa** [comment]
Hi @ComeMaes could you create separate issue, I will provide you fix for that problem.

**Comment by ComeMaes** [comment]
Hello @laa 
Sure, here it is:  #6688
