### ISSUE TITLE
Which is better  more number of edges or vertices?

### ISSUE THREAD

**Issue by grachit** [orientechnologies/orientdb#5498]
lets consider an example:
    I have vertices of type A and B. Edges between A and B contain scores and timestamp. (will it be good to have more edges and store properties over it) OR (create more number of vertices of type B for each timestamp and have lightweight edges)?

**Comment by luigidellaquila** [comment]
Hi @grachit 

at the low level there is no difference between vertices and edges, both are represented as documents.

Traversing a regular edge and two vertices has the same cost of traversing two lightweight edges and three vertices.

The real difference is in how many documents your query will visit

I hope it will help you in your analysis

Thanks

Luigi

**Comment by grachit** [comment]
thanks @luigidellaquila, But wanted to understand, what is the idea behind edges having properties? Somewhere, i read in documentation that lightweight edges are better in performance. could u please explain how?

**Comment by luigidellaquila** [comment]
Hi @grachit 

In the Property Graph model, edges are allowed to have properties, so OrientDB provides this functionality.

There is no real advantage in having properties on edges, compared to having lightweight edges, one more vertex in the middle and properties on the vertex.

Lightweight edges are faster than regular edges when your model just does not need properties related to relationships

Thanks

Luigi

**Comment by smolinari** [comment]
In other words, an edge with properties is just another (type of) vertex? But, if you create such "normal edges" (not light weight edges) ODB will take care of the linking between the 3 vertices accordingly? What other advantage is there in using normal edges and considering them edges and not just another vertex (type)?

Scott

**Comment by luigidellaquila** [comment]
Hi @smolinari 

IMHO the main advantage is in the model quality: an edge represents a relationship while a vertex represents an entity in the graph.

At the low level both are represented as documents, but in the model they have a different meaning, staying with regular edges will make your model clearer.

Lightweight edges should be considered an optimization and should be used only if your domain does not have properties on relationships

Thanks

Luigi

**Comment by smolinari** [comment]
Thanks Luigi. 

Yes, of course an edge represents something completely different on the user side. I was just trying to understand it from the database side, as you said, vertexes and normal edges are all just documents.I think I get the overall picture from the database perspective. 

I would say, "properties on relationships" are only needed, if "intelligence" on those relationships is needed. In other words, if you are going to analyze the state of relationships in some way, you'll need normal edges. Otherwise, if you don't need to analyze the state of edges, then you can go with light weight edges. It is basically a trade-off between just knowing there is a relationship and working that that simple state (light weight edge), which is faster..... or knowing there is a relationship and knowing exactly what the relationship is all about (normal edge), which is slower. 

So, could we boil this down to, if you need intelligence about the relationships at any point in your graph, use normal edges, if you don't, go with light weight edges?  

Wasn't there a statement made that normal edges are just as performant as light weight edges and that is why they were made the default for a database (just checking to be sure)? It would be really good to know that light weight edges are still more performant (which also makes sense), then normal edges. Unfortunately, I can't find where I read the statement. If you could confirm either way, I'd appreciate it. 

Scott

**Comment by luigidellaquila** [comment]
Hi @smolinari 

Yes, I'd say that your interpretation on edge properties is correct.

About lightweight edges, I can confirm that they are more performant than normal edges, in some cases 50% faster on traversal :-)

It's an old discussion, I'm closing it, but please reopen if you need further clarification

Thanks!

Luigi

**Comment by smolinari** [comment]
Nope. All perfectly clear to me now (and hopefully anyone else reading this thread). And knowing the light weight edges are actually "light weight", as in, their usage can mean additional performance, is great to know. Thanks.

Scott

**Comment by fabriziofortino** [comment]
@smolinari @luigidellaquila Interesting discussion here.

One more question: AFAIK I can decide to enable/disable lightweight edges at database level.
What if I have a scenario where I need normal edges only for some relationships? It would be cool to specify at schema level which type of edge I want to use for a specific link. What do you think?

**Comment by smolinari** [comment]
You can do this now. You can determine the edge type when you create the edge, by turning light weight edges on and creating edges with no properties. These will be light weight edges. Once you add properties to the edge class, then those edges becomes normal edges. 

Scott
