### ISSUE TITLE
lucene query parse

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#5518]
i feel strange the results returned from following query. Can i know which query is considered the right one?

1. select name from hotel where name lucene '"Court motor Lodge"~0.9'
     result below is most closer to query.
name
-------------------------
Knightsbridge Court Motor Lodge
Knightsbridge Court Motor Lodge

2. select name from hotel where name lucene 'Court motor Lodge~0.9'
     result below is not closer at all to query.
name
------------------------------
Knightsbridge Court Motor Lodge
Knightsbridge Court Motor Lodge
Niagara Falls Motor Lodge
Cedar Court Huddersfield/Halifax
Cedar Court Huddersfield/Halifax
Kings Court Hotel
Niagara Parkway Court Motel
Stagecoach Motor Inn
Stagecoach Motor Inn
Major League Motor Inn

**Comment by robfrank** [comment]
First of all, which version of orient are you using?
After that, as for Lucene query parser doc (https://lucene.apache.org/core/5_4_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#package_description) terms of second query are evaluated in OR. The proximity operator ~ in the second query is applied only to the last term, Lodge. 
What kind of result do you expect?

**Comment by martingg88** [comment]
i'm using the following versions
orientdb = V2.1.8
orientjs = v2.0

I expect the final result should be most closer to this phrase "'Court motor Lodge" instead.
So how's the query look like to get the expected result with orientdb?

**Comment by robfrank** [comment]
OrientDb 2.1.8 uses Lucene 4.7.0, you can find query parser documentation here : https://lucene.apache.org/core/4_7_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#package_description

As from documentation, the first query you wrote perform a proximity search, but a value of 0.9 is meaningless: should be an integer value. 

Second query apply a fuzzy search on the last term, searching for documents where a term is  _similar_ (based on  Damerau-Levenshtein Distance) to Lodge. __BUT__ the value 0.9 is wrong: should be from 1 to 2. It is the number of maximun edits allowed.
Moreover, quoting docs :
_Previously, a floating point value was allowed here. This syntax is considered deprecated and will be removed in Lucene 5.0_

If you need to match documents on the phrase "Court motor Lodge", the query should be enclosed by double quotes, maybe doing some escaping on js side.

Terms on second query are evaluated in OR, the lucene standard. So each description match the query since at least one of the term is present in the text.

If you need/want to compose advanced full text queries, read carefully the lucene's documentation.

**Comment by martingg88** [comment]
thanks for sharing this.
