### ISSUE TITLE
OrientDB 2.2 Documentation as a GitBook

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5690]
Hi,
I recommend you build Documentation of the new release of OrientDB 2.2 as a GitBook and make it available online. 

I had several problems with the present form of documentation, especially in navigation and contents,  in browsers such as Chrome and Mozilla. Printing pages online was not also easy.

**Comment by smolinari** [comment]
You could do this yourself actually, if you want to. All you have to do is register a Gitbook account, 

https://www.gitbook.com

fork the docs repo and hook your Gitbook account to your Github account and your fork of the book repo. Then you can open the docs in Gitbook as PDF, ePub or Mobi versions.

Scott

**Comment by healiseu** [comment]
@smolinari, I did not ask a solution for myself. I suggested something for the benefit of the whole community. But I followed your advice and I can view it as a Gitbook from my github account and that indeed solved problems I had with navigation, thank you for this.

May I add that OrientDB documentation is already formatted as a Gitbook, i.e. md files but there are problems with navigation panel when you browse, e.g. it disappears, then you have to click back on the web browser, etc....

**Comment by smolinari** [comment]
Yes, I know you asked as a general request, which would be good for the whole community. My comment was only to help you out now, until ODB possibly carries out your suggestion. It shouldn't mean ODB should now ignore your suggestion, because everyone can make their own Gitbook, just so they can print out pages or get an ePub version. That would be ridiculous, of course. 

As for the navigation, I use Google Chrome's latest version and I have Firefox's latest version (on Windows 7) and it seems the navigation works properly. Can you be a bit more specific on how to recreate the issue with the navigation? Also note which browser version and OS you are using?

Scott

**Comment by healiseu** [comment]
Google Chrome Version 47.0.2526.106 (64-bit)
on Ubuntu 14.02
