### ISSUE TITLE
Possible / canbe values for a class property

### ISSUE THREAD

**Issue by smallik** [orientechnologies/orientdb#5692]
Idea

have a setCanbe(List<Object>) method on the property of a class
This method will define the possible values that this property can be assigned.
Its a constraint mechanism. So if we try to set any other value to the property to the list other than the one specified in the list then it should error out.

Examples 1:

Seller is the class name
name is the property in class seller of type string 
list<String> seller_list=['acme', 'nike', 'logitech', 'microsoft']
setCanbe(seller_list)

in the above case the only values allowed to be set on a seller object name property is one of the values from the list.

Examples 2:

Seller is the class name
product_id is the property in class seller of type integer 
list<Integer> product_list=[10003, 20056, 8093, 9532]
setCanbe(product_list)

**Comment by smolinari** [comment]
This issue might be of interest to you. https://github.com/orientechnologies/orientdb/issues/62

Also, in your suggestion, since there can be more than one property in a class, I'd venture to say, there would need to be a second argument to the method denoting the property the method should be checking against. Like for the last example, setCanbe(product_list, product_id).

Scott
