### ISSUE TITLE
array parameter passed as string in Function

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5737]
select check(['a','b'])

where check(t){return t;}

t is a String , not a Array

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

I'll check it soon

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

I just checked it in Studio and it works fine if you run the query from the query browser.
If you test the function from the Functions tab, then it's normal to obtain a string, because the input field just passes strings forward

I'm closing this, please reopen if I missed something

Thanks

Luigi
