### ISSUE TITLE
Error on retrieving record by traverse function & enabled record security

### ISSUE THREAD

**Issue by AlexanderRay** [orientechnologies/orientdb#5766]
Hi, I have issues by execution following query with enabled RecordSecurity (through ORestricted) if some of vertexes have no read access by current user. "select @rid from (traverse \* from #10:19 WHILE $depth <= 2) where $depth in [0,2] limit 100"

![screen shot 2016-02-23 at 17 30 18](https://cloud.githubusercontent.com/assets/786006/13258670/67d29a4c-da54-11e5-9a62-45c66738a25b.png)

**Comment by maggiolo00** [comment]
hi @AlexanderRay 

can you post the permissions of user manager?

**Comment by AlexanderRay** [comment]
user manager have no permissions  for reading on vertex #5:0, but that vertex is connected to vertex #10:19. should I made some demo-db and upload it somewhere?

**Comment by maggiolo00** [comment]
Yes thanks

**Comment by AlexanderRay** [comment]
Hi, here is the dropbox link to the issue demo db "https://db.tt/y3yTQx6M"

sql for reproduce "select @rid from (traverse * from #12:0 WHILE $depth <= 2) where $depth in [0,2] limit 100"

logged in user is "writer"

**Comment by maggiolo00** [comment]
hi @AlexanderRay 

which version are you using?
I tried with 2.1.11 from console
and i got no results back which i think is correct because user writer is not allowed to read record
#12:0
If i do

```
select @rid from (traverse * from #12:1 WHILE $depth <= 2) where $depth in [0,2] limit 100
```
with record #12:1 i get your exception but i think because you specify travers with *
that means that it will try to traverse also the _allow* links, and user writer cannot read that clusters
You can solve it by traversing only graph relationship

```
select @rid from (traverse both() from #12:1 WHILE $depth <= 2) where $depth in [0,2] limit 100
```

**Comment by AlexanderRay** [comment]
i'm using 2.1.9

Ok, I see, it works also for graph relations and not for link types, but it's enough for me.

thank you very match)
