### ISSUE TITLE
v2.2.0-beta - automatic backup firstTime not using GMT as documentation says

### ISSUE THREAD

**Issue by pboos** [orientechnologies/orientdb#5916]
Using the embedded version of v2.2.0-beta and passing in the xml as a string to OServer.startup

Setting up the automatic backup with the following parameter:

```
<parameter name="firstTime" value="09:04:50" />
```

Results in the following output when starting:

```
Automatic backup plugin installed and active: delay=14400000ms, firstTime=Sat Apr 02 09:04:50 CEST 2016, targetDirectory=backup/ [OAutomaticBackup]
```

So it seems like it is using CEST which is the timezone my computer is in. CEST is GMT+2. So something seems wrong.

The other thing that I notice that I wonder if it is a bug or a feature: It says Apr 2 (today is Apr 1). It even says that if I set a time in the future. Is it possible to run the backup immediately?

**Comment by obi1kenobi** [comment]
Part of this exists on 2.1.x as well -- if the time specified in "firstTime" is not in the future for the present day, the backup will not run until the following day even if the "delay" parameter is set to something small like 1h. I'd really appreciate this getting fixed, because it means that *restarting the db process once a day could lead to not having any backups*, despite the backups being set to hourly frequency.
