### ISSUE TITLE
Edge path + AS clause + WHERE clause on the edge path causes empty result sets

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#5961]
```
CREATE VERTEX V SET name='abc'
CREATE VERTEX V SET name='def'
CREATE EDGE E FROM (SELECT FROM V WHERE name='abc') TO (SELECT FROM V WHERE name='def')

SELECT out('E') AS path FROM V WHERE out('E').size() > 0  # returns the expected 1 record
# compare with
SELECT out('E') AS path FROM V WHERE path.size() > 0  # returns no records, and no errors
```

Since the `AS` clause defines `path` to be the same thing as `out('E')`, one would expect that the two queries above return the same result. I'd also accept an error from the second query, if this is not supported. However, OrientDB 2.1.13 silently returns no data. There isn't anything in the server logs either.

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

In current implementation aliases are used only to return data (they are calculated only after record evaluation). The statement does not fail only because they "path" name could refer to another (schemaless) property of the document

We have in the roadmap the full implementation of usage of aliases for filtering, ordering and so on

Thanks

Luigi

**Comment by obi1kenobi** [comment]
Thanks for your reply! It would be nice if the documentation on aliases mentioned that one cannot yet use aliases to filter and order records.

**Comment by luigidellaquila** [comment]
+1, I'll update the docs

Thanks

Luigi
