### ISSUE TITLE
(Feature) JDBC Driver not supports JTA transactions.

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#5972]
OrientDB JDBC Driver not supports standart JTA transactions.

**Comment by robfrank** [comment]
Hi, JTA isn't implemented right now. I took a look around to other noSQL db with a JDBC driver and I didn't find a driver with JTA implemented, but I can be wrong. 
Is it mandatory for your project? 
I'm asking because it seems a big task to me, and I really don't know when I'll have time to implement it. A initial PR will be wonderful.

**Comment by schernolyas** [comment]
HI @robfrank 

It is not mandatory.  I implemented local transaction manager for Hibernate OGM  for OrientDB. Other developers did same for other NoSQL systems that Hibernate OGM supports.

You can see sources of JDBC drivers for PostgreSQL or MySQL as some example. In other words, JDBC driver must implement javax.transaction.xa.XAResource.

About PR ....I can to try but ... my previus PR is hanging. I mean PR 5622.
