### ISSUE TITLE
Hash Index: preallocating

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6021]
When you're going to insert 1B of vertices and you have an hashindex, a good optimization is to specify the initial size, so OrientDB avoids to create many sub-buckets. In this way the lookup cost pass from `O(log N)` to `O(1)`.

**Comment by laa** [comment]
This issue does not fix problem described by Luigi because of problem described in https://github.com/orientechnologies/orientdb/issues/1757 , what is additional value in it's implementattion ?

**Comment by lvca** [comment]
Today our hash index is allocated of size X. As soon as a bucket is considered full, it's splitted in sub-bucket, right? So an hash index becomes similar to a b-tree in his shape (but in different ways). With 1B of records, you could have from 1 to Y levels of buckets. In the worse case scenario, you could do Y lookups, where every lookup is a load of a page with high chance this page is on disk, so SEEK+LOAD.

Preallocating the hash index size (it would well work only if the key are well distributed after hashing), allows us to keep the index at level 1 only, in theory, with a O(1) access for every key. In practice it would be from 1 to Z, where Z should be much lower than Y.

When you deal with the disk, having even 1 level less in a index tree, means much less SEEK+READ. (The difference between RAM & DISK is 2-3 orders of magnitude)

**Comment by laa** [comment]
@lvca there is no index tree in this index. We always have O(1) complexity with hash index. We will decrease index seeks from about 45 ms  to about 40 ms using this issue.  I do think it help to solve users issue described by @luigidellaquila . Did you read explanation of user's problem in https://github.com/orientechnologies/orientdb/issues/1757 issue ? If yes,  and it is still not clear I will provide additional details.

**Comment by lvca** [comment]
With current implementation, how you reach the sub levels? Is it lookup for the key and in case go down (=seek & load a page), and repeat the lookup?

**Comment by laa** [comment]
we do have sublevels, hash index has plain buckets.

**Comment by lvca** [comment]
Right, so in theory if we create a large hashindex, the chance to have sublevels is lower, right? Could this be a temporary workaround before we have something better?

**Comment by laa** [comment]
@lvca it was a typo, I mean in hash index we do *not* have sublevels. All buckets are equal and accessed at single page load. I will explain. Each insert on each stage consist of following operations:

1. Find pointer to the page/bucket in in memory data structure.
2. Load this bucket in single IO file operation or from cache.
3. Add item to the bucket. 
4. If bucket is full , split the bucket, so we will have two buckets on the same level as initial bucket.
5. Update in memory index.

So if each bucket contains let's say 1000 items. And we have cache which cache only few items then each ordinal write read page from file and update already cached page for 20 ms.

Then for every 1000 item we need to read 2 pages, one original page when only half of items will left and one new page. 
So for 1000 items in average we will read 2.002 pages. 
With provided improvement we will spend on 1000 items 2 pages instead of 2.002 pages. 
IMHO improvement does not worth time is needed to implement it.

**Comment by lvca** [comment]
It's still not clear to me why we need 2,002 pages to insert 1,000 items (see your last statement). Also, the point (1) about finding the pointer, how do you find the pointer? Imagine 1B entries, and you are looking for the key 'Andrey' with hash = X.

**Comment by laa** [comment]
@lvca 
> Imagine 1B entries, and you are looking for the key 'Andrey' with hash = X.

What problem do you see in finding  the key with hash X ? Long.MAX_VALUE is 18 446 744 073 709 551 615 . It is much bigger than 1B. About hash codes itself, they stored in a form of a compressed trie. 
A trie is not a typo.

**Comment by laa** [comment]
@lvca about your second question
>It's still not clear to me why we need 2,002 pages to insert 1,000 items

I wrote not about pages but on operations on pages.
To insert 999 items we:

1. Read page
2. Modify content 
3. Store the same page to the storage

To insert the last item we :+1: 

1. Read page
2. Split content of single page on two pages
3. Write 2 pages on the disk

So to insert 999 items we need (2 * 999) page r/w operations.  To insert the last item we need 3  operations  . Or 2 * (1000 -1) + 3 = 2 * 1000 - 2 + 3 = 2,001 operations. Which means that preallocation will provide so minor speed up  (if provide at all) that it does not worth time is needed to implement it.
