### ISSUE TITLE
JSON Request to Insert record - Data type issue

### ISSUE THREAD

**Issue by SatishAMP** [orientechnologies/orientdb#6071]
HI , I have Vertex with 2 fields , 1 as date type and 1 as double.
I am unable to update or rather create a new record to this vertex  using json request.
http://localhost:2480/command/demo/sql/INSERT INTO FundTransfer CONTENT {"FundTrnsfrAmt": "2000.90", "TrnsfrDate": "20-04-2016"}

but it created the FundTrnsfrAmt and TrnsfrDate as string values. I am not able to create them as double and datetime values. 

I reffered all the documents couldnt find any solution.
Can you please how can i insert record using JSON request which as datatypes other than String ?

**Comment by luigidellaquila** [comment]
Hi @SatishAMP 

A couple of points here:
- remember to send the request in POST, otherwise it won't succeed
- double values are correctly stored if you just remove the quotes: `{"FundTrnsfrAmt": 2000.90, `
- for the date field, you have to define the property in the schema and then pass the value as a string, in the correct date format (the default is yyyy-MM-dd, but you can change it in the db config), eg. `"TrnsfrDate": "2016-04-20"}`, OrientDB will do the conversion automatically

I hope it helps

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @SatishAMP 

This this help? Can i close this issue?

Thanks

Luigi
