### ISSUE TITLE
Select on Class (28k of columns and 58k of rows) really slow

### ISSUE THREAD

**Issue by fedyfausto** [orientechnologies/orientdb#6223]
Hello i hase some troubles with my OrientDB. I insert all data into my Class and when i use curl for extract CSV result my select query take really long time (about 15 minute only for 3 columns) this is my curl:
# !/bin/bash

QUERY="select CompositeSequence_Identifier,$1 from Processed;";
curl --user admin:admin --header "Accept: text/csv" -d "$(echo $QUERY)" "http://localhost:2480/command/EsperimentoTest/sql" > test.csv

**Comment by luigidellaquila** [comment]
Hi @fedyfausto 

Do you have 28.000 fields for every single record? So you have about 1.5 billion fields on your db in total?

Are you working schemaful (it would help) or schemaless?

 I guess the problem is in the fact that to generate the result-set, OrientDB has to unmarshal the all DB, and it takes a while... maybe reviewing your domain will help a lot


Thanks

Luigi

**Comment by lvca** [comment]
I'm closing this issue because of no response since a while. In case the issue is still valid, please reopen/comment this. Thanks.
