### ISSUE TITLE
JavaScript function and IN operator

### ISSUE THREAD

**Issue by warriorkitty** [orientechnologies/orientdb#6225]
Hi all. I have a use-case where I have userId and a list of movie rid's which I want to get (along with the Edge Rating). How do I pass the parameter **movies** as an array in JavaScript to OrientDB?

<img width="453" alt="123" src="https://cloud.githubusercontent.com/assets/5781483/15637402/ee18062e-2616-11e6-87bc-874615f0caa0.png">

This works but I'm sure it's not the right way.
I also tried this and it's not working (getting an empty array as a result):

<img width="316" alt="123" src="https://cloud.githubusercontent.com/assets/5781483/15637430/642f6154-2617-11e6-9bdc-75d287c31869.png">

**Comment by luigidellaquila** [comment]
Hi @warriorkitty 

The problem here is that the Studio Graph panel passes the second parameter as a string, so the result of the second query will be something like (see the quotes)

```
SELECT * FROM... WHERE rid in ["#13:0, #13:1"]
```

that is not what you want to do of course.
The second version, used from SQL, should work fine though

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @warriorkitty 

I'm closing this ticket, please reopen if you need further help

Thanks

Luigi
