### ISSUE TITLE
Please help optimize query

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#6257]
There is need to have some generic search over all objects. Currently it's done with the following query:

``` sql
SELECT FROM MyClass WHERE any() CONTAINSTEXT 'query'
```

As you can see: that's search through all documents of class MyClass which contains required text in any field. But even for 30000 it takes around 30 secs to complete.

Do you have any ideas how to optimize search without going on low field-by-field level? I made search like that on Apache Solr and on 20.000.000 it took not more that 0.1 sec. 
But in this case I don't want to involve Apache Solr because OrientDB already has LUCENE.

So - any ideas?
### Runninng Mode
- [x] Embedded, using PLOCAL access mode
### OrientDB Version
- [x] v2.1.19
### Operating System
- [x] Linux
### Java Version
- [x] 8

**Comment by smolinari** [comment]
When you say search over all objects, what do you consider an object? A record in a class?

If so, couldn't you use a multi-property Lucene index on the class "MyClass"? 

http://orientdb.com/docs/2.2/Full-Text-Index.html

`CREATE INDEX MyClass.multi_property ON MyClass(prop1, prop2, prop3, prop4) FULLTEXT ENGINE LUCENE`

Scott

**Comment by PhantomYdn** [comment]
Tried to create for all properties: no effect.

**Comment by smolinari** [comment]
How did you then do the search? With the query you posted above?

Scott

**Comment by PhantomYdn** [comment]
Do you have other suggestions? It seems should work with CONTAINSTEXT.

**Comment by smolinari** [comment]
`SELECT FROM MyClass WHERE [prop1, prop2, ...] LUCENE "query"`

Scott

**Comment by smolinari** [comment]
BTW, we are torn between using the Lucene search and going with Elasticsearch and will probably end up having to use Elasticsearch (despite the added complexity). 

The problem is, our schema is (and so should ODB's) flexible. That is THE killer NoSQL feature, right? However, if you create a full-text search index with Lucene and you add a new property at some point in the lifetime of the application (i.e. what a flexible schema should allow and what makes NoSQL a winner, right?) it means that the index for the ODB class must be completely reindexed. This totally kills the purpose of NoSQL, in effect, especially when working with large data sets. Basically, a user of ODB should not expect to have any major downtimes to change schema....period. 

We are looking at Elasticsearch, because it allows for on-the-fly (zero downtime) schema changes.   

Have a look at this article: 

https://www.elastic.co/blog/changing-mapping-with-zero-downtime

Scott
