### ISSUE TITLE
Tree traversal unexpectedly slow with HTTP connections

### ISSUE THREAD

**Issue by jwgmeligmeyling** [orientechnologies/orientdb#6262]
## Expected behavior and actual behavior

Considering a simple tree structure, with vertices connected with `Child` edges, and each vertex having about 5 children, with a total of 5 levels, resulting in 2.500 vertices. Doing a simple _list all_ query as follows:

```
TRAVERSE out("Child") FROM 1:0 MAXDEPTH 5 LIMIT 2500
```

Takes as much as `800 ms`. For a simple traversal as this, I find this unacceptably slow. I would expect it to be in the range of `30 ms` to `50 ms`. Especially considering the fact that a graph of 2.500 vertices is hardly a megabyte.

Just selecting all the vertexes using `SELECT FROM X LIMIT 2500` also takes about `200 ms`. So it may be that some of the time is not spent in traversal at all, but I still find the result really high for what the hardware should be capable of.
## Steps to reproduce the problem

Described above.
### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x] Remote (on localhost, query ran on web interface, so executed locally on DB)
### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition
### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [x] v2.1.x - Please specify last number: 12
- [ ] v2.2.x - Please specify last number: 
### Operating System
- [x] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
### Java Version
- [ ] 6
- [ ] 7
- [x] 8

Potentially related to #4056

**Comment by basdek** [comment]
Let me add some more details to this issue, since JWGmeligMeyling is a colleague of mine and we are working together on set query.

The tree is pyramidic in form, with no cycles:

```
root
16 sublevels
+/- 8 sub sub levels per sublevel
+-- 5 sub sub sub levels per sub sub level
+/- 5 sub sub sub sub levels per sub sub sub level, amounting to a total of about 2600 - 3200 vertices.

```

There is no apparent difference between a gremlin query and an OSQL query.

The most devastatingly frightening detail is that this seems to scale in O(n) wherein n is the amount of records, which is absolutely not acceptable.

I.e.

From the root it takes 800ms.
From a sublevel (emitting about 150 results) it takes 44ms.
Which leads to ```16*44=704``` 

That can't be correct now, can it.

**Comment by luigidellaquila** [comment]
Hi @JWGmeligMeyling 

Is it with warm or cold cache?

Could you please try to run this an post the result:

```
EXPLAIN TRAVERSE out("Child") FROM 1:0 MAXDEPTH 5 LIMIT 2500
```

Please do it twice, I'm interested in seeing the difference of the two

Thanks

Luigi

**Comment by JWGmeligMeyling** [comment]
Now the cache is hot the query time seems to decrease to +/- `330 ms`. Which is still high, but considerably closer to the query time for just selecting all vertices of that type.

First explain:
```
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "path": "(#14:0).out[10](#15:10).out[1](#16:46).out[0](#17:61).out[8](#25:857)",
            "stack": [
                "[idx:-1]",
                "#25:857",
                "[idx:8]",
                "#17:61",
                "[idx:0]",
                "#16:46",
                "[idx:1]",
                "#15:10",
                "[idx:10]",
                "#14:0",
                "java.util.ArrayList$Itr@6f8bd1ab"
            ],
            "depth": 4,
            "elapsed": 209.65195,
            "resultType": "collection",
            "resultSize": 2500,
            "@fieldTypes": "stack=u,elapsed=f"
        }
    ],
    "notification": "Query executed in 0.246 sec. Returned 1 record(s)"
}
```

Second explain:
```
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "path": "(#14:0).out[10](#15:10).out[1](#16:46).out[0](#17:61).out[8](#25:857)",
            "stack": [
                "[idx:-1]",
                "#25:857",
                "[idx:8]",
                "#17:61",
                "[idx:0]",
                "#16:46",
                "[idx:1]",
                "#15:10",
                "[idx:10]",
                "#14:0",
                "java.util.ArrayList$Itr@4480619c"
            ],
            "depth": 4,
            "elapsed": 126.16431,
            "resultType": "collection",
            "resultSize": 2500,
            "@fieldTypes": "stack=u,elapsed=f"
        }
    ],
    "notification": "Query executed in 0.163 sec. Returned 1 record(s)"
}
```

**Comment by luigidellaquila** [comment]
Hi @JWGmeligMeyling 

From the explain the query execution time is 209ms (first run) and 126ms (second run), all the rest is network communication and record marshalling/unmarshalling. 
This is the actual performance you would have if you ran your queries from an embedded OrientDB instance (http://orientdb.com/docs/2.2/Embedded-Server.html)

If your use case allows it (eg. if you have no properties on the edges), you can enable lightweight edges and significantly reduce the traversal time.

About the scale of the performance with the result set, in general on a graph database the performance of a query depends on the number of traversed nodes/edges (ie not on the depth of the traversal)

I hope it helps

Thanks

Luigi

**Comment by basdek** [comment]
@JWGmeligMeyling @luigidellaquila Retrieving 2600 vertices plain and simple with a ``` select from ClusterName limit 3000``` should not take so long now should it?

``` select from Scope limit 40000 ```

```
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "documentReads": 5287,
            "current": "#43:2679",
            "documentAnalyzedCompatibleClass": 5287,
            "recordReads": 5287,
            "fetchingFromTargetElapsed": 22,
            "evaluated": 5287,
            "elapsed": 21.829865,
            "resultType": "collection",
            "resultSize": 5287,
            "@fieldTypes": "documentReads=l,current=x,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,evaluated=l,elapsed=f"
        }
    ],
    "notification": "Query executed in 0.079 sec. Returned 1 record(s)"
```

Should I open a second issue for that?

**Comment by luigidellaquila** [comment]
@basdek 

Which client are you using? Are you from OrientDB Studio or from a remote server?

That second of execution is 98% network communication, the query actually took 21ms to execute  (see `"elapsed": 21.829865` in the explain result)

Thanks

Luigi

**Comment by luigidellaquila** [comment]
(and rendering maybe, if you are in Studio)

**Comment by basdek** [comment]
@luigidellaquila Using orient studio, on a LOCAL db (so virtually no network overhead), and on a very very fast machine on an M2 hard drive that is also very fast. 

How should I read the timing indicator in Orient Studio? Because it says: 1.5 seconds. And you are telling me that it takes 21ms. Would this not imply that the timing indicator in studio is useless?

**Comment by JWGmeligMeyling** [comment]
Very interesting, so it seems that most time is spent in getting the answer to the web interface, and not necessarily in querying... So we should be able to sharp off some seconds by optimizing query output. Wheras using light edges will improve query time (I am not sure how much), it seems  that we will not get under this 200 ms query time, and that this query time will scale linearly with our number of vertices. So scaling one or two orders of magnitude will bring some difficulties and force us to manual caching. Is BFS/DFS so intensive after all?

**Comment by basdek** [comment]
@luigidellaquila 

This raises a couple of new questions:

- With regards to the cache? What is the eviction strategy? Is this influenceable? How do we take control over the cache? 

- Could I perhaps cache adjacencies of a certain class? 

- I assume that if I change one vertex this invalidates the cache. So a cache seems an invalid answer to the problem: I am almost never executing such a query twice in a short time.

- Would you be so kind as to address the fact that this seems to scale in O(n)? Cause that negates the validity of OrientDB as a proper solution for what in all honesty can not be considered a very complex graph problem. What if I have this data size tenfold? Would that mean that I would see a query time of 2 seconds (excluding marshalling)?

**Comment by basdek** [comment]
With regards to the suggestion of using light weight edges? That is sort of a last resort I think. Cause it reduces a lot of why a graph db is such a beautiful thing: relations as first class citizens.

**Comment by smolinari** [comment]
@basdek - If you don't need any properties on the edges, then you are much better off using lightweight edges, as then ODB only has to deal with 2 links in two classes to form the edges, instead of 6 links in three classes (as is the case with regular edges). With lightweight edges, the relationships, are still first class citizens, just not as "informational". 

As for your concerns about ODB's performance, in what scenario do you require to have a result set of 2500 records and need it under 200ms? What is your particular use case? What is your data structure/ schema? What is the size of the records on average? With more background information, I am sure the ODB team can fix you up with a more performant solution. 

Scott

**Comment by basdek** [comment]
@smolinari

**Comment by basdek** [comment]
@smolinari @luigidellaquila 

After some consideration and trial and error, this is my take on the problem:

* Marshalling has immense penalties (which are in it's self a painful problem, that I think orient should adress).  

* The query time results of this query are quite decent if you do not marshall - it is very arguable that it is quite an artificial / sketchy measuring technique to conclude that performance is in order if you don't count marshalling (after all we are building a real world app, the data is needed at some point). In our specific use case it would be okay (albeit not ideal) to construct a tree with unloaded vertices from only their id's and relations (x -> y

**Comment by basdek** [comment]
With all due respect guys, I would not consider this answered, nor resolved. Any thoughts or replies to the (concrete) questions I issued? 

@luigidellaquila @smolinari 

cc @JWGmeligMeyling

**Comment by lvca** [comment]
@basdek I have a few questions for you:

1. How you did measure the time for marshalling?
1. How many fields your vertices and edges have?
1. How many fields your vertices and edges are you loading during your traverse?
1. Could you please provide some numbers?

**Comment by JWGmeligMeyling** [comment]
We're talking about approximately 20.000 vertices, with 5 to 10 properties, and 1 to 5 outgoing edges. I wouldn't consider that very big data (at least not close to billions of vertices). We have been using the web console, the Java API and the output for `EXPLAIN` commands to measure our results. If we really need to have some actual numbers, please give us an indication what sort of benchmark would give you the most useful information.

Furthermore, the issue focus has slightly moved since we have been investigating this issue. Initially we found a (in our minds) relatively easy tree traversal to be unacceptably slow. I still think that this tree traversal can be improved (adjacency indices, better cache invalidation strategy, lazy fetching of vertices - admittedly, our vertices have a paragraph of text attached to it, but that should not matter for traversal, and it seems it currently does).

Our focus has however switched to serialisation, as concluded from above results, it seems most time is spent in serialisation anyway. The question is why is serialisation so slow? We observe smaller result sets easily being out-runned by returning the same number of results in other databases. More problematic, bigger result sets (on a test DB of approximately 200MB) crash with an `OutOfMemoryError` (how can 200MB data consume 32GB RAM?).

From profiling the VM we see that most time is spent in the `String` class. We also see a lot of `byte[]` manipulation from the serialisation source. This raises the question, is there any pipelining at all? As it starts to look as if the penalty for serialisation was assumed to be insignificant for the overall query time in the development process, but it turns out to be very intensive in practise.

**Comment by basdek** [comment]
@JWGmeligMeyling @luigidellaquila @lvca @smolinari 

Let me add to JWGM's story that we were not trying to marshall 25k vertices but 2.5k vertices. 25k is our entire db.

**Comment by lvca** [comment]
The problem with RAM here is the HTTP layer: it doesn't stream the result but it uses RAM before to send the result back. So if you have a big JSON as result set and/or concurrent requests, the RAM could be a problem. We're working for a fix on this.

**Comment by lvca** [comment]
@basdek can you tell me please the size of the resulting JSON in bytes?

**Comment by lvca** [comment]
I'm closing this issue because of no response since a while. In case the issue is still valid, please reopen/comment this. Thanks.

**Comment by JWGmeligMeyling** [comment]
String concatenation in the serializer is the problem here. Bigger results sets throw an OutOfMemoryException easily. String#concat shows up red on every heat map produced by several profilers. I am not sure if thats fixed in a new version of orient? Anyways, even without the tremendous penalty of IO and marshalling, I find even the query execution times that are presented here quite poor.

**Comment by lvca** [comment]
Ok, I'm reopening the issue, then. @JWGmeligMeyling do you have any chance to use a binary protocol instead of HTTP?

**Comment by JWGmeligMeyling** [comment]
I don't really think this has to be reopend though, because from @tglman 's comment it seems as if the serializer is already being rewritten to utilize streaming more?

**Comment by lvca** [comment]
@tglman WDYT?

**Comment by tglman** [comment]
hi,

If the client send a request that allow chunked response it will be done streaming on http, that should solve the issue on memory usage and marshaling, i see as well discussion also receving the content and the rendering on the studio, so thi issue seems a bit to wide.

For what i can say in the server part since 3.0 we have in place all for do proper streming and is also inplemented in the current http server inplementation, anyway the http server implementation is old and not allow us to do a lot of things, we will have the full potential expressed at the moment that we replace the current http server with a new implementation that will happen between 3.1 and 3.2.

Regards

**Comment by basdek** [comment]
What is the expected release date of 3.0?

**Comment by lvca** [comment]
3.0 M1 should be out in 1 week, but it's not suitable for production.

**Comment by smolinari** [comment]
What does "M1" mean?

Scott

**Comment by lvca** [comment]
M1 = Milestone 1. It's not yet a RC. It's the first step on publishing something so the early adopter can use and provide feedback. After M1 will come M2 and then the RC before the GA.

**Comment by smolinari** [comment]
Hehehe...sorry bout that. I guess Github sends off the notification emails pretty fast. I removed my question about "M1" and asked in the Google Group. 

https://groups.google.com/forum/#!topic/orient-database/hXc_myADvzE

Thanks for the explanation anyway. Shows the great service you guys try to give, which I still think overweighs any mistakes ODB might have. 😄  

Scott
