### ISSUE TITLE
Dense graphs can be a problem?

### ISSUE THREAD

**Issue by lucevers** [orientechnologies/orientdb#6283]
### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [+ ] Remote

### Misc
- [+ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [+ ] v2.2.x - Please specify last number: 

### Operating System
- [+ ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [+ ] 8

Question?

https://www.quora.com/Is-there-any-reason-not-to-use-OrientDB

Dense graphs can be a problem?
Is this right or already solved by a new version?

**Comment by smolinari** [comment]
Hi,

This is the key part.

> vertices with millions of edges

These vertices with millions of edges are considered supernodes and they do cause problems for the reasons the reply author mentioned. However, this isn't an ODB problem. It is a general issue with all graph databases.  

Scott

**Comment by luigidellaquila** [comment]
Hi @lucevers 

Supernodes can create some problems with flat traversal (without conditions), just because of the number of nodes/edges you visit.

In v.2.2 we solved this problem with pattern matching. Consider this scenario:

- A and B are supernodes with millions of edges
- you want to know if there is an edge that connects A and B

If you have an index on the edge `out` and `in` properties, the following query will use it and will be extremely fast:

MATCH
{class:A, as:a, where:(condition for node A)} -EdgeClass-> {class:B, as:b, where:(condition for node B)}
RETURN a, b

Of course the index is used also if the pattern is in more complex query.

The index is used only in case of supernodes, if you have only a few incoming/outgoing edges OrientDB will use normal index-free adjacency, so you will have the best performance for each use case

Thanks

Luigi

**Comment by lucevers** [comment]
Thanks!
