### ISSUE TITLE
Question: SELECT projection VS toJSON

### ISSUE THREAD

**Issue by ibeals** [orientechnologies/orientdb#6295]
I am jumping between `select from (traverse out() from foo)` to `select @this.toJSON("fetchPlan:[*]in_*:-2 out_*:-1") FROM foo`. In the first select each related document connected by an outgoing edge is returned separately, and toJSON returns them nested by connected edges and one record (more or less). -- How can I specify the SELECT projections or FROM so that the return is similar to toJSON but more control over the projections I have in the first select statement above.

### OrientDB Version
v2.2.0

**Comment by luigidellaquila** [comment]
Hi @ibeals 

if you are using HTTP API you can use the fetchplan in the query (see the syntax http://orientdb.com/docs/last/SQL-Query.html). If you are using the binary protocol (eg. Java client) then you will have full objects loades, so you can just use Tinkerpop API to traverse the edges

I hope it helps

Thanks

Luigi

**Comment by ibeals** [comment]
Hi @luigidellaquila 

I'm using the binary protocol in OrientJS.

With `select from (traverse out() from foo)` the return results is something like:

`[
{"rid":"#7:1","class":"foo","property":"testing","out_baz":["#5:1"]},
{"rid":"#8:1","class":"bar","property":"testing","in_baz":["#5:1"]}
]`

Each record is its own JSON document.

With `select @this.toJSON("fetchPlan:[*]in_*:-2 out_*:-1") FROM foo` the return result is like:
`[
{"rid":"#7:1","class":"foo","property":"testing","out_baz":[{"rid":"#8:1","class":"bar","property":"testing"}]}
]`

I'm looking for a way to write up my query statement that allows me to pull documents and nest them according to their edges like this.toJSON will do.

Example: `select foo.*, expand(nest(out())) from foo`

I don't know if it exists but I'm open to trying anything OrientJS/binary protocol can do. I will be writing this with Node.js or Golang.

**Comment by sungeunchoi-kr** [comment]
Hi @ibeals;

I have been using OrientDB for more than a year now, and as far as I know, doing what you described--nested projections--is impossible with SQL. SQL likes to return everything as a flat table. I would love to be wrong since nested projections is a feature I had always wanted ever since I began using OrientDB.

You have some alternatives, which is to (1) use fetchPlan as you described or (2) use the Javascript stored functions (http://orientdb.com/docs/2.2/Functions.html) to manually loop through and aggregate the data according to your data structure. For me, the Javascript stored functions have worked quite well. You can use `orientjs`'s `createFn()` that creates stored functions so that you don't have to write them in the browser, and also be able to keep your stored functions in source control.

Also, if you search for "nested projections" in the issues, you'll be able to read some discussions that the developers and the contributors have had regarding the feature you want.

**Comment by ibeals** [comment]
Hi @sungeunchoi-kr,

Thank you for the tip about server side functions. I'll look into those. It seems the toJSON function is very close to nested projections so maybe that will come soon too.

Thanks for all of the input.

Ian

**Comment by luigidellaquila** [comment]
Hi @ibeals 

I'm closing this ticket, please reopen if you need further info

Thanks

Luigi
