### ISSUE TITLE
Error while executing a creation script in a plocal database

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#6303]
I have a medium size application which uses OrientDB extensively: SQL scripts, java API (Document, Graph, Object).

I have a large set of integration tests which are executed using plocal and in memory databases.

When using OrientDB 2.1.15 all my tests pass correctly, but after moving to OrientDB 2.2.2 many of them fail. The tests pass when executed isolated and when executed in a sequence via eclipse, but fail when executed via maven using the command line. Most of the tests reuse the same database: they add initial data, perform a test and clear the database at the end. The only way I found to make the tests pass is to make each test create its own database, which obviously makes my build slower.

There is an error which is even more weird, because it shows up in jenkins but not in my local machine (I guess it's because our jenkins is a linux machine and my desktop is windows). This happens when an integration test initializes a plocal database executing a sql script. The exception I get:

Error: com.orientechnologies.orient.core.exception.OPaginatedClusterException: Error during creation of cluster with name dprocesslog_7
	DB name="custom-app-emulation-integration"
	Component Name="dprocesslog_7"

Error: java.io.FileNotFoundException: /srv/build/ssd1/jenkins/workspace/DestinyG_benchmarks/sandbox/target/databases/custom-app-emulation-integration/dprocesslog_7.cpm (Too many open files)

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode

### OrientDB Version
- [ ] v2.2.x - Please specify last number: 2

### Operating System
- [ ] Linux

### Java Version
- [ ] 8

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

I think the problem is related to the new "multiple clusters per class" feature in 2.2 (see https://github.com/orientechnologies/orientdb/issues/4518)

The problem seems to be also related to the fact that your OS cannot open all the open files for the existing clusters.

As a quick fix, you can re-enable the old defaults, setting minimum clusters to 1. Here's how to do it http://orientdb.com/docs/last/Configuration.html

The parameter to set is `class.minimumClusters=1`. The constant, to do it  from code, is `OGlobalConfiguration.CLASS_MINIMUM_CLUSTERS`

I hope it helps

Thanks

Luigi
