### ISSUE TITLE
Provide more configuration for teleporter

### ISSUE THREAD

**Issue by Koc** [orientechnologies/orientdb#6314]
For now it is impossible change target class name for source tables. It would be useful specify target properties names and types. Also would be nice filter subset of the columns to import

**Comment by G4br13l3** [comment]
Hi @Koc, we are working in order to offer a smarter, more flexible and customizable importing. We have just released the last OrientDB 2.2.2 EE with a new version of Teleporter included that allows to configure the migration through a JSON file. At the moment you can affect the relationships-edges mapping (https://github.com/orientechnologies/orientdb-docs/blob/master/Teleporter-Import-Configuration.md), the next step we will work on will comprehend your proposal: a new configuration mapping between tables and vertices will be possible, with a granularity at property level. 

BTW at the moment you can filter in or filter out the tables you want to import (table granularity) through the arguments '-include' or '-esclude':

https://github.com/orientechnologies/orientdb-docs/blob/master/Teleporter-Import-Filters.md

Thanks for your feedback and proposal.

**Comment by Koc** [comment]
@G4br13l3 thank you for fast reply. Yes, I've reading this sections in documentation.

Also teleporter which shipped with inside EE 2.2.2 not works for me, it says that cann't load class OTeleporter or similar. I've downloaded teleporter separately and put jar inside plugins dir and it works.

**Comment by G4br13l3** [comment]
We have just planned a new release, I advise you to try again when the last version will be available because the package you just downloaded is outdated. I will update here when the release will be completed.

**Comment by G4br13l3** [comment]
Hi @Koc, we released the new orientdb 2.2.3 version with Teleporter correctly integrated. Can you try again with the latest version?
Let me know, thanks.

Here the download link:
http://orientdb.com/download/

**Comment by Koc** [comment]
@G4br13l3 okay, thank you, will try.

Can you also see related issue https://github.com/orientechnologies/orientdb-docs/issues/168 ?

**Comment by G4br13l3** [comment]
Hi @Koc, we released a new user interface for Teleporter in orientdb studio 2.2.24 (in the server management area), thus now you can map in a visual way the source schema of the RDBMS with the graph model in OrientDB. The Teleporter plugin is now integrated into OrientDB Community Edition (previously it was available only in the Enterprise Edition). Beware: in CE you can't synch your database. 

I'm closing this thread, please reopen it if you need something more.

Thanks.

Gabriele
