### ISSUE TITLE
Altering the name of a property if it already has a value returns both property names and values

### ISSUE THREAD

**Issue by SDIPro** [orientechnologies/orientdb#6354]
Tested on 2.2.4-snapshot but affects 2.1.x and 2.0.x too.

Steps to reproduce:
create class PropTest
create property PropTest.Name String
insert into PropTest set Name = "Bob"
alter property PropTest.Name name Nomen

select from PropTest

There will now be a "Name" property and a "Nomen" property returned, and both will have a value of "Bob".

**Comment by luigidellaquila** [comment]
Hi @SDIPro 

That's an expected behavior, when you rename a property, the property value is copied to the new name.
There is a cryptic note in the docs about that (http://orientdb.com/docs/2.2.x/SQL-Alter-Property.html bottom of the page), I think it's worth updating the docs and making it more explicit

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Done, the docs will be updated in short

Closing

Thanks

Luigi

**Comment by smolinari** [comment]
@luigidellaquila - Can you explain why that is proper behavior? I would have expected the name of the property to be changed and nothing else. If the only way to do this is to copy to a new property internally, then I would also expect the old property should be deleted internally too. 

Scott

**Comment by luigidellaquila** [comment]
Hi Scott,

That's a good point, it's for historical reasons I think, I should back-track it and see why it was implemented...
