### ISSUE TITLE
Java removeVertex and SQL delete vertex have very different performance

### ISSUE THREAD

**Issue by scrabb** [orientechnologies/orientdb#6367]
## Expected behavior and actual behavior

I would expect using removeVertex method or issuing the DELETE VERTEX command to execute in the same amount of time.
Using my particular data
- remoteVertex took 2.5 minutes
- DELETE VERTEX took 13.4 seconds

Both tests were done in Java connecting to orient via the remote protocol however all code was actually running on the same physical server.
## Steps to reproduce the problem

Using a large graph db (35M vertices, 170M edges),delete a vertex with a lot of edges
### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x] Remote
### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition
### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.x - Please specify last number: 
### Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 
### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by luigidellaquila** [comment]
Hi @scrabb 

The problem here is that the removal of a vertex also involves the removal of all the connected edges and the update of the "other side" of the edges (all  the connected vertices).
If you do it from the Java API, each of these operations will involve some record fetching from remote, plus at commit time you will have to flush the transaction to the server. 
On the other side, using an SQL statement, all the operations are made on the server, without network overhead.
This should explain the difference in performance

Thanks

Luigi

**Comment by scrabb** [comment]
Appreciate the quick response.
Would it not make sense for the remoteVertex method to just invoke a DELETE VERTEX SQL statement internally to avoid this difference when used with remote running mode.
Don't suppose you know if any other methods from the java API would have the same issue?  And if so should it be recommended to use the SQL statements when running in remote mode rather than the Java API.

**Comment by tglman** [comment]
Hi @scrabb,

The reason why the removeVertex run client side is because it need to be in  the context of the transaction, the sql commands server side work outside the transactions.

Some of this behavior is going to be changed in 3.0, making everything more coherent and faster.

Regards
