### ISSUE TITLE
Inconsistent and obscure behaviour of external collections

### ISSUE THREAD

**Issue by taburet** [orientechnologies/orientdb#6370]
After setting an external collection to a document field, it is not easy to understand when the connection between the external collection and the collection stored in the field is destroyed. Two possible solutions:
1. Make sure the connection is never destroyed while accessing the data through the same document/database instance.
2. Define an easy to understand and consistent behaviour of the connection destruction. Describe it in the documentation.

`com.orientechnologies.orient.core.tx.ExternalCollectionsTest` test case will be added to the repo soon to demonstrate a weakness of the current solution.

**Comment by taburet** [comment]
One idea came to my mind, we can't track the modifications diff for the external collection, but at least we can throw an exception when we detect the internal and external collections are out of sync. Almost any standard Java collection type has something like `modCount` field to fail fast on concurrent modifications. We can't access `modCount` directly, but we may acquire collection iterator which checks for concurrent modifications and store it in the internal collection. On saves we may ask the iterator to throw the exception and if it throw we may just re-throw it wrapped into another exception with a more clear message.

**Comment by lvca** [comment]
@tglman WDYT about this issue?

**Comment by tglman** [comment]
hi @taburet,

Yes the test case make assumption that the internal external collection are the same, this cannot be because it means keep some kind of connection for long running instance and even loose the control of what save and what not save, we could do it if the collection where instances of our own classes, but this would limit a lot the usability of the API.

On the tracking of external collection and eventual error on change, I think it can be done, but at the end is going to be quite complex to maintain with not much more benefit than a good documentation.

For me is OK as it is now, but I'm open to other evaluations.

Regards
