### ISSUE TITLE
Big in binary protocol and auto-merge conflict strategy

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6387]
Using Auto-Merge conflict strategy in case the content is merged, the updated byte[] is never sent to the client, so the client has an old version and corrupts the database.

I've patched the binary protocol (version=37), please review it.

**Comment by tglman** [comment]
Hi,

We had some problem with that specific commit, i reverted it and tried to write it in another way that not need the change of the protocol, now if the version from the server is not what i expect( client version + 1) I unload the record, so in this way the next access to the record trigger a load, it's slower that it not include the changes to the binary protocol that can be defined as public api.

Other point i assume that in case of conflict the version is not client version + 1, is that correct ?

**Comment by lvca** [comment]
Ok to have such behaviour with older releases, but why removing this optimization? It's anyway an improvement and it's backward compatible.

**Comment by tglman** [comment]
hi,

The main reason to not do the protocol changes is actually that this behaviour has meaning only for the java client, and we have many other clients that are trying to keep up with our changes, so i prefer to treat the binary protocal more like a public api, keeping it constant expecially on hotfixes.

in any case the performance improvement is true only in some cases when you reuse the same record later on, otherwise will be only additional data sent on the network that the client will never use, so more a slowdown that performance improvement, and in any case all the clients without a local cache don't really need this change.

On the specific commit we had some small compilation issues, and the fix was not tacking care of the noTx update, i redo all the cases invalidating the record client side, so now we cover all the cases.

**Comment by tglman** [comment]
this should be fixed and released, closing
