### ISSUE TITLE
[Question] How does declaring the intent to do massive inserts change OrientDB?

### ISSUE THREAD

**Issue by Dacnomanie** [orientechnologies/orientdb#6400]
How does OrientDB prepare itself for the inserts and what does it do differently?

**Comment by luigidellaquila** [comment]
Hi @Dacnomanie 

with MassiveInsert OrientDB disables some checks and functionalities, so that single record insert is faster. These checks include:

- document validation
- security
- hooks
- automatic Tx for no-tx graph operations

The Java class OIntentMassiveInsert has setter methods to explicitly enable/disable these behaviors

Thanks

Luigi
