### ISSUE TITLE
[Suggestion] - Allow for creating in-memory (memory only) classes

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb#6447]
[From this discussion in GG.](https://groups.google.com/forum/#!topic/orient-database/_xwbdw55_IM) 

It would be cool to have the ability to create in-memory classes, much like heap tables in MySQL. These could be used for temporary data storage or for caching or any other in-memory storage of data use case.

Scott

**Comment by Eric24** [comment]
Some implementation notes:

- Minimum requirements would allow "marking" a class as "in-memory" (i.e. specific classes in an otherwise normal PLOCAL database, _not_ a separate MEMORY database), which would automatically keep any record created or previously read in memory, and leave the responsibility of using it wisely to the application (i.e. making sure there is enough memory for the expected records, etc.), and of course it must release the memory used by deleted records. The class would be replicated across multiple servers if the database was configured for replication and could be set for "in-memory only" or "synchronously persisted to disk" (for "asynchronously persisted to disk", see below).

- A "better" (but not critical) implementation would add support for setting a max size of the in-memory cache per class (i.e. so the total size of all records could be larger, but the most recently accessed records would remain in memory), allow for "pre-load" (i.e. all of the records in the class would be loaded upon startup, asynchronously in the background, so we're not waiting for it), allow for "lazy" disk persistence (i.e. where creates or updates to records would complete immediately and be written to disk by an asynchronous background thread).

**Comment by smolinari** [comment]
@Eric24 - Doesn't your second point describe a disk caching system? ODB does have disk caching AFAIK. 

To me, an in-memory class would be completely volatile and used purely for runtime data persistence. There is no disk access and why that makes such a class advantageous. If there is any "preloading" of data, it would have to be done by the application itself, not ODB.

Scott

**Comment by Eric24** [comment]
@Scott: There are (at least) two different scenarios for what I'm
describing, neither of which are just disk caching (and yes, it's certainly
my understanding that ODB already has this). The first is what you
describe: a fully in-memory class that does *not* persist data to disk
(although the class schema *does *persist), and this implementation would
work fine for my particular (and immediate) use-case as long as it also
supports cross-server replication (same quorum-commit model that ODB
already implements). The second is an in-memory class that is "backed" by
records stored on disk, and this is different from normal caching in that
the "cached" records in this class are "pinned" in memory, rather than
managed by the caching algorithm (LRU or whatever) and periodically purged
(or "evicted", to use cache terminology). This second scenario has value,
too, and is similar to how Redis/etc. works (or can be configured to work),
for example. It provides disk-backed storage of records that are always
guaranteed to be in memory (and thus fast and highly deterministic with
regard to access times). The pre-loading can certainly be done by the
application, but since that's a fairly common feature for this sort of
design, I mentioned it as a "nice to have". The last point on the "disk
backed" scenario is whether persistence to disk is done synchronously or
asynchronously--both options have their place, based on create/update speed
frequency and performance requirements. My thought is to implement
whichever option is easiest (I assume synchronous) and make the other a
"nice to have".
--Eric

**Comment by Eric24** [comment]
@Scott: Also, the other objective that I don't think I was clear on is that
this kind of class must (obviously) reuse deleted space, else it would run
out of memory pretty fast. And since a common use-case (as well as my
specific use-case) is to use such a class for frequently-updated temporary
data, this becomes even more critical. Of course, I'd prefer all ODB
classes to reuse deleted space, as documented elsewhere, but for this
in-memory class, it's critical. I realize that probably makes this more
complicated, but I could envision a design for the in-memory class that
allows it to reuse deleted space in memory, while still not reusing disk
space if it was configured for persistence.

**Comment by smolinari** [comment]
For my curiosity, could you please explain a use case, or even two, where such a in-memory, but also stored on disk type of class would be useful?

Scott

**Comment by Eric24** [comment]
Sure, but the caveat is that there's always more than one way to approach a
particular problem. In general, the idea of an in-memory class is speed and
deterministic response, for data that is frequently accessed (which could
be read-only or read-mostly). I also think in terms of scalability under
very heavy load and 24/7 systems that have very rare or no maintenance
windows. So here are a few use cases where I'd want to use an in-memory,
disk-backed class...

A heavily-read lookup table -- The content of the lookup table (say
country/city names based on phone numbers) is relatively static, but is
used for high-frequency real-time transactions where speed is critical.
Here, you could have the application reload the table from a separate
underlying disk-based class at startup and periodically (as records are
updated over time, because the table is not 100% static). Automatic
pre-loading would be desirable here, so the table is "in-memory complete"
as quickly as possible after a server restart. The same logic would apply
to a fully-static lookup table, without any need to do periodic "refreshes".

Temporary storage of web session data, especially in the case of ecommerce
sessions, where you may want to retain the "shopping cart" for some period
of time, even if the user left and came back tomorrow -- If the in-memory
class was replicated to multiple servers, that may be enough
fault-tolerance that you'd not need it to be disk-backed, but one way or
the other, you'd not want the data to disappear in case of a sever crash.
Here, the access pattern is heavy read/write and pre-loading after a server
restart isn't really necessary.

A work queue, where multiple "clients" are queuing requests to multiple
"workers" -- Here, too, multi-server replication may provide enough
fault-tolerance, but if not, you wouldn't want the content of the work
queue to disappear in case of a server crash. Here too, the access pattern
is heavy read/write, and pre-loading after a server restart might be
beneficial, depending on how big the queue is generally expected to be and
if the performance penalty can be tolerated until the old queue items
naturally clear out.

**Comment by smolinari** [comment]
Ok. Thanks for the explanation. If I may ask as a last question, which programming language are you using for your application?

Scott

**Comment by Eric24** [comment]
Sure, no problem. We're using node.js with the orientjs driver.

**Comment by smolinari** [comment]
Ok. Thanks.  :smile: 

Scott
