### ISSUE TITLE
Add link to documentation of password format in config/orientdb-server-config.xml

### ISSUE THREAD

**Issue by krichter722** [orientechnologies/orientdb#6517]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .6[x]

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
Being able to copy the password for user `root` from default `config/orientdb-server-config.xml` into the studio web frontend. There was no link to the documentation of the password format which by default is `{PBKDF2WithHmacSHA256}[first part]:[second part]:[third part]` and trying the complete string, `[first part]:[second part]:[third part]`, `[firstpart]` and `[second part]` didn't work.

## Steps to reproduce the problem
Download 2.2.6 release and open `config/orientdb-server-config.xml`.

**Comment by lvca** [comment]
The password is hashed in the file using `PBKDF2WithHmacSHA256` algorithm, so you cannot copy & paste. You have to know the password :-)

**Comment by krichter722** [comment]
This is not a question. The text doesn't even contain a question mark... Please read again the title. Your comment doesn't solve this issue.

**Comment by lvca** [comment]
Sorry, I don't understand if you are expecting that copying the hashed password from the file into studio login form, you think it's correct you can log in.

**Comment by krichter722** [comment]
> Sorry, I don't understand if you are expecting that copying the hashed password from the file into studio login form, you think it's correct you can log in.

I understand how it works. I want it to be documented for others. Basically, your first comment should go into a comment of the default server configuration file.

**Comment by lvca** [comment]
It's not possible to comment after we generated the XML file with the library we use.

**Comment by smolinari** [comment]
I think the issue is if you run the server for the first time, but don't enter any password and just press enter, something is added as a password, but it isn't known to the user. This forces the user to go into the config and add a new password (usually unencrypted). 

Copying and pasting the password, as suggested in Studio, doesn't work. 

![image](https://cloud.githubusercontent.com/assets/3314957/18806876/7cd3ffc0-8239-11e6-8479-7f621cef184f.png)


Suggestions:

1. At startup, if only "enter" is pressed, warn the user that the password being set is the default "root". Warn that this is unsafe and only for test or demo purposes. And if the password needs changing use the "resetpasswd.sh" script, to set up a new password.

2. Create a "resetpasswd.sh" script, which a user with server root or sudo privileges can run to reset the ODB root user's password. 

3. The first suggestion is only an alternative.

Scott

**Comment by lvca** [comment]
I totally forgot we have that old HTML in Studio. This can't be done anymore for security reasons, we should remove it. Sorry for the lack of understanding from my side.

**Comment by lvca** [comment]
@maggiolo00 Could you please remove that snippet in Studio?

**Comment by maggiolo00** [comment]
@lvca 
sure

**Comment by smolinari** [comment]
How about the other suggestions?

Scott

**Comment by lvca** [comment]
You can still change the user from the console. Through the console you can manage server users with the following commands:
- list server users
- drop server user <name>
- set server user <name> <password> <permissions>

**Comment by smolinari** [comment]
Ahh... I tried searching for something like that, but didn't find anything. 

What are the permissions one can add? The docs don't offer the options.

http://orientdb.com/docs/2.2/Console-Command-Set-Server-User.html

Scott

**Comment by maggiolo00** [comment]
@lvca 
Removed

**Comment by lvca** [comment]
@smolinari is right, the resources are missing here.

**Comment by lvca** [comment]
Updated docs.
