### ISSUE TITLE
60 Second "502 Under Maintenance" Issue

### ISSUE THREAD

**Issue by havkarl** [orientechnologies/orientdb#6582]
Hello,

First time posting a question and using this forum, so I apologize if this is answered somewhere!

We're running into a fairly pervasive issue where if a simple query takes over 60 seconds to complete, a 502 Under Maintenance exception is returned.  However, after combing through the code and google, I cannot seem to find out 1.) what configuration I can modify that controls this timeout, and 2.) what the actual problem is.  We're running into degraded performance over time and see inconsistent response times.  We are indexing on the fields we search on.  The performance comes during heavy read operations.

The simplest question I have is how do I extend this timeout?  The next step is to identify why we even have this problem in the first place.  Our development servers seem to have less problems handling our load than the production server at times, and I am suspicious as to why.  Is there a good way that others have found to identify how to properly set the max disk cache + max mem?

Your help is appreciated.  Thank you for your time.

Karl Haviland
Senior Developer
Bright Power

**Comment by luigidellaquila** [comment]
Hi @havkarl 

There is a specific `command.timeout` parameter, but by default it's disabled, so it should not be the problem.

Other parameters that involve a timeout are related to networking or to distributed configuration (eg. `distributed.crudTaskTimeout`, are you running distributed right now?)

Here you can find the full list of config parameters:

http://orientdb.com/docs/2.2.x/Configuration.html

Now let's try to identify the main problem:

- how much total memory does your system have?
- what kind of operations are you doing? 
  - N reads vs. N writes
  - transaction size (number of records)
  - typical size of query result sets
  - do you perform many GROUP BY or ORDER BY operations

The optimal configuration of heap and disk cache depends a lot on these parameters.

As general rules, you should consider the following:

- choose the size of your heap based on the operations you execute (transactions and group/order operations are heap based) and leave all the rest of the memory for disk cache
- never exceed the physical memory, eg. if you have 32GB you can give 4GB to heap and 24GB to disk cache, leaving some memory for the OS and for other processes. This is important, because if you exceed the maximum physical memory and the system starts to swap memory to disk, your performance will go down quickly

Thanks

Luigi

**Comment by lvca** [comment]
If you get a `502 Under Maintenance` error, it means something in the middle has a timeout. Apache? A proxy?

**Comment by havkarl** [comment]
That would make sense.  I will look for an Apache setting or proxy timeout, and get back to you on what I find.

**Comment by havkarl** [comment]
Hello, quick update.  I did find a Timeout setting in the Apache httpd.conf that is set to 60 seconds.  Thank you for the pointer.  I haven't tested it yet, but it definitely looks like the issue.  It make take a bit of time to get to a sufficient test, so I'll reply with my findings in a day or two.

**Comment by havkarl** [comment]
Hello, I want to close this ticket.  We were able to solve the problem by updating the Apache timeout settings in the httpd.conf file.  Thank you for helping with this issue.
