### ISSUE TITLE
Performance of SUM() is low

### ISSUE THREAD

**Issue by zhengguozhu** [orientechnologies/orientdb#6615]
## OrientDB Version, operating system, or hardware.
- v2.2.7

## Operating System
- [x] Linux

## Expected behavior and actual behavior
SUM() takes more than half of the query time, it should be very fast.

**Comment by lvca** [comment]
I'm sorry but this issue doesn't contain any information about it, like:
- what's your query?
- what's your datasets? 
- how many records were involved in the query?
- what's the time we are talking about? milliseconds or seconds?
- etc.

If you want help, please be more specific and provide all the information we could need to understand the problem when you open the issue, so we avoid to write back and forth on it. Thanks.

**Comment by zhengguozhu** [comment]
The dataset is about 20,000 objects A with edges to 2000 objects B.
And the query is SUM(in('B2A').size()) from B.
With a 16G Mem, 4CPU, SSD machine, the query is about 500ms.
With no SUM() calculation, just query in('B2A').size(), the query is less than 100ms.

**Comment by lvca** [comment]
Thanks. I think in your case the 2nd query had a limit of 20 items, while the SUM is an aggregation so it scans all for all B anyway. The `SUM` operation is very simple and can't add overhead. Try this:

    select in('B2A').size() from B limit -1

It should have the same performance as with the SUM or even worse (more results).

In order to speedup this query, you could avoid to jump to the incoming vertices, but just counting the edges. Try this:

    select sum( inE('B2A').size() ) from B

**Comment by lvca** [comment]
Please let me know if works.

**Comment by zhengguozhu** [comment]
thanks, it is not the performance issue of SUM().
