### ISSUE TITLE
Result of subquery doesn't hit index on master query field

### ISSUE THREAD

**Issue by ismaelpernas** [orientechnologies/orientdb#6684]
## OrientDB Version, operating system, or hardware.
-  [x] v2.2.4
## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

Apologies if this is not the place for this question, not sure if this is a bug or not. 

I have a ClassA with an NONUNIQUE - SBTREE index on field Id. When I perform the following query:

```
SELECT @rid.asString() as rid, Id as id, PrimaryName as name FROM ClassA
WHERE Id IN [100, 200, 300, 400]
```

I get the results back in few milliseconds and I can see that the index is used. No problem at all. However, If I do the following query:

```
SELECT @rid.asString() as rid, Id as id, PrimaryName as name FROM ClassA
WHERE Id IN (SELECT DISTINCT(in('edge_to_classA').Id) FROM ClassB WHERE (PrimaryName LUCENE 'Hello'))
```

The result of the subquery is Ids 100, 200, 300, 400, which then applied to the master query returns the same results as expected. However, it doesn't hit the index on the Id field in ClassA. As a result, query1 takes 11ms to run and query2 takes 500ms on a class with 50K vertices. Lucene index is used as expected.

Is there anything missing in order to hit the index? Is it a bug or intended behavior?

Thanks!

**Comment by luigidellaquila** [comment]
Hi @ismaelpernas 

It is a known limitation of current SQL executor. We are completely re-writing it, so in v 3.0 it will be supported, but for now I think you have to deal with it.
As a temporary work around, you can use a BATCH script like following:

```
LET $a = (SELECT DISTINCT(in('edge_to_classA').Id) FROM ClassB WHERE (PrimaryName LUCENE 'Hello'))
SELECT @rid.asString() as rid, Id as id, PrimaryName as name FROM ClassA WHERE Id IN $a
```

In this case the index will be used

Thanks

Luigi

**Comment by lvca** [comment]
In 3.0 this is already working.

**Comment by titikakatoo** [comment]
Hello,

 we are using the Document API in OrientDB version 2.2 and facing exactly the same problem as @ismaelpernas. 

Switching to Orient 3 (beta) is a no go for us, since we are already using it in production.

Suppose we have a class Company and a class Employee and are interested in all Companies with at least one employee having a name from an arbitrary list. Employees are defined as LINKEDLISTs in our Company schema. Our query would look smth like this:

`select from Company where employees in (select from Employee where name in ["John", "Paul"])`

Currently we have defined the following two indexes:

Company.employees (index on the employee links (their @rid)) -> dictionary hash index and Employee.name -> notunique index

When executing the above query with explain we see that only the second index Employee.name is used, since we did not define the above indexes as a compound index across the two classes Employee and Company.

The batch approach worked for us, however when applying it we are already hitting a second big limitation. Command scripts seem to only work synchronously,  meaning also that we can only get the results as a list all at once and not one by one in a lazy fashion, which in our case is a NO GO due to the memory overhead.

A naive workaround we tried is as follows: 
The approach of defining a custom OCommandAsyncScript did not work unfortunately. When debugging the OStorageRemote class of Orient it seems that no partial results could be read, Here the respective extract from the source code:

```
 public class OCommandAsyncScript extends OCommandScript implements OCommandRequestAsynch{

            public OCommandAsyncScript(String sql, String cmd) {
                super(sql, cmd);
            }

            @Override
            public boolean isAsynchronous() {
                return true;
            }
        }



        private void containsAtLeastOne(final @Nonnull ODatabaseDocumentTx documentTx,
                                            final @Nonnull Consumer<Company> matchConsumer,
                                            final @Nonnull String queryText
                                           ) throws TimeoutException {

                String cmd = "begin\n";
                cmd += "let a = select from Employee where name " + queryText + "\n";
                cmd += "let b = select from Company where employees in $a\n";
                cmd += "COMMIT\n";
                cmd += "return $b";
                final OCommandHandler resultListener = new OCommandHandler(documentTx, (document -> {
                    final Company companies = document2model(document);
                    matchConsumer.accept(company);
                }));

                OCommandAsyncScript request =  new OCommandAsyncScript("sql", cmd);
                request.setResultListener(resultListener);
                documentTx.command(request).execute();
...
            }


    public class OCommandHandler implements OCommandResultListener {
     private final ODatabaseDocumentTx database;
        private final Consumer<ODocument> matchConsumer;

        public OCommandHandler(
                final @Nonnull ODatabaseDocumentTx database,
                final @Nonnull Consumer<ODocument> matchConsumer
        ) {
            this.database = database;
            this.matchConsumer = matchConsumer;
        }


        @Override
        public boolean result(Object iRecord) {
            if (iRecord != null) {

                final ODocument document = (ODocument) iRecord;

                /*
                 Result handler might be asynchronous, if document is loaded in a lazy mode,
                 database will be queries to fetch various fields. Need to activate it on the current thread.
                 */
                database.activateOnCurrentThread();

                matchConsumer.accept(document);
            }
            return true;
        }
        .......................
    }
