### ISSUE TITLE
Teleporter: switch database schema.

### ISSUE THREAD

**Issue by mdre** [orientechnologies/orientdb#6801]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[x] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]
## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

Need a parameter to tell what schema should Teleporter import. In Oracle this could be accomplished running "ALTER SESSION SET CURRENT_SCHEMA= <your-schema>"

**Comment by G4br13l3** [comment]
Hi @mdre, are you performing your migration from Oracle? I'm wondering that because the concept of schema is slightly different depending on the DBMS.
For example in Oracle we should consider the user account and all the objects therein (tables, grants etc.) as the schema itself. At the moment each migration in Teleporter can involve just one schema at a time, so if you want import a different schema you can simply change the user in the next migration. Let me know if I got the point, thanks.

**Comment by mdre** [comment]
Hi!
The problem is that the user that has the schema only can access from the
App server IP. All other user has readonly access from some few IPs.
The user we have can query the production DB but has no other grant so in
this way, we secure the server. The DB Server Administration is
responsability of another area in the goverment.
As you say, we see the Oracle DB in the "Other users" hive. Here is a short
view of we see:

[image: oracle-access.png]
Thanks.

Marcelo
