### ISSUE TITLE
Performance problem with MATCH command

### ISSUE THREAD

**Issue by tanhv90** [orientechnologies/orientdb#6826]
## OrientDB Version, operating system, or hardware.
- v2.2.11
## Operating System
- [x] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

I have a graph db with 4 nodes (V1...V4) and 5 relationships (e1...e5) like that:
{V1} -e1/e2-> {V2} -e3->{V3} -e4->{V4} -e5-> {V4}

I used MATCH command to query data:

> MATCH
> {class:V2, where: (e2_property is not null) <-e1- {class:V1, as:v1},
> {as:v1} -e2-> {class:V2, as:v2_1} -e3-> {} -e4-> {class:V4, where: (v4_property is not null)}
> RETURN v2_1

This query works well with small dataset.
But when the data is large enough, the problem occurs.

The above query return only 2 records but it takes ~ 15 seconds.

I have tried to add the `LIMIT 2` to the query, so it responses immediately (~ 0.2 seconds).
But if I change the LIMIT to 3, the problem is back, it takes long time to response as mentioned in above ~15 seconds.

I have tested a lot of cases, and I found that in case the dataset is large enough.

> If you use MATCH command without LIMIT or the LIMIT value > the number of records (will be returned), it will take long time to execute and response. (my case: 15 seconds)
> 
> If the LIMIT value < the number of records, it execute and response in short time (my case: 0.2 seconds)

**Comment by luigidellaquila** [comment]
Hi @tanhv90 

could you please post a sample dataset to reproduce the problem?

Thanks

Luigi

**Comment by tanhv90** [comment]
Hi @luigidellaquila ,

I cannot post the dataset I used here because it is too large and contains business data.
I will try to create a test database and post it later.

Thanks,
Tan

**Comment by tanhv90** [comment]
Hello @luigidellaquila 

This doesn't really match with my real case. But the issue with performance of MATCH command is still the same.
Hope this useful.

Thank you!
Tan

**Comment by tanhv90** [comment]
Hi,
I would like some response please

**Comment by luigidellaquila** [comment]
Hi @tanhv90,

Sorry, I was out of office in these days.
I think I got the problem:
suppose you have a pattern like following:
```
A-->B-->C

return A, B
```

and you have 1 occurrence of A, 1 occurrence of B and 100.000 occurrences of C (all linked to B), now the MATCH returns the only result very quickly, but then it tries to evaluated all the occurrences of C, but it's just useless. 

I think I have to implement a short-circuit policy, so that when the tuple is matched it avoids to evaluate all the possible "non returned" parts of the pattern.

It should not be too complex to implement, but it requires some refactoring, I'll try to estimate it and let you know

Thanks

Luigi

**Comment by tanhv90** [comment]
Hello @luigidellaquila,

Thanks for your information.
I'm trying to workaround by adding LINKSET and use both it with current EDGE relationship.
The performance is acceptable now. But I don't think it a good solution.

I hope you finish this work soon and it can be released with ver 2.2.13 💃 

Thanks,
Tan

**Comment by tanhv90** [comment]
Hello @luigidellaquila,

How about the current status of this issue?

Thanks,
Tan
