### ISSUE TITLE
Backup: Create a multi-threaded backup

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6829]
OrientDB executes backups by using a single thread implementation (class `OZIPCompressionUtil.java`). We could easily use the features of JDK7 to create a multi-threaded zipper by following the examples contained here:
- http://www.pixeldonor.com/2013/oct/12/concurrent-zip-compression-java-nio/
- http://docs.oracle.com/javase/7/docs/technotes/guides/io/fsp/zipfilesystemprovider.html

**Comment by laa** [comment]
Hi @lvca those approaches use Java 7 API, but 2.2.x version is based on 3.0 API should we move this issue to 3.0 version ?

**Comment by lvca** [comment]
Wasn't 2.2 based on Java7?

**Comment by laa** [comment]
No , Java 6  from, https://github.com/orientechnologies/orientdb/blob/master/readme.txt "OrientDB needs Oracle Java JDK version 6 or major to run the Server. "

**Comment by tglman** [comment]
Nope 2.2 is still java 6, otherwise we could have used a lot of nice features of java7 like `try(closable){}`

**Comment by laa** [comment]
Ok , I move it to 3.0 version.

**Comment by taburet** [comment]
Unfortunately, Java 7+ zip file system compresses files into memory and writes compressed buffers from memory to disk on the file system shutdown. That may lead to OOM for large file sets and/or files. There is an undocumented option to use temporary files instead of memory, but still, that is not satisfactory, the temporary files consume disk space and disk IO overhead is doubled. Also, there is no way to control the compression level of the resulting zipped files.

Closing for now.
