### ISSUE TITLE
Studio Graph Editor remember last graph but not query

### ISSUE THREAD

**Issue by austx** [orientechnologies/orientdb#6923]
## OrientDB Version, operating system, or hardware.
- v2.2.13  (since 2.2.11)

## Operating System
- [ x] Linux

## Actual behavior
If keeping graph in buffer the query(select or match) should also be "remembered"

## Steps to reproduce the problem
run a query and go to SCHEMA and back again to GRAPH. The query you used is gone but the
graph comes back. If you log off and log into another database, the graph from the database you logged off shows up again. That's really odd.

**Comment by santo-it** [comment]
Hi @austx, 

Thanks for opening this issue. Both your points are valid in my opinion. I do agree that it's odd that the graph shows up again after you change database. I was going to open an issue for this myself

Thanks again for your feedback!

**Comment by santo-it** [comment]
Hi @austx,

Thanks again for opening this issue. I believe both problems have been fixed in 2.2.15

Just in case you would like to test the fix before the official 2.2.15 version is out, please be aware that you may download the latest snapshot from https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-studio/2.2.15-SNAPSHOT/
(to install it, just replace the studio zip file included in the orientDB_home/plugins directory with the snapshot archive)

I'm closing this issue now. Please feel free to reopen if needed

Many thanks,
