### ISSUE TITLE
Logging as java.util.Class

### ISSUE THREAD

**Issue by rohrl** [orientechnologies/orientdb#6962]
## OrientDB Version, operating system, or hardware.
2.2.12

## Operating System
all

## Expected behavior and actual behavior
Our logs are spammed with following:
`2016-12-01 16:41:27,502 [DefaultExecutorService-1] 478278 WARN  java.lang.Class - MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=16068m option when you start the JVM.`

**We can't increase logger level for this one because Orient logs this as "java.util.Class"**
The bug is in OMemory:128:
`OLogManager.instance().warn(OMemory.class, "..."`
instead of probably:
`OLogManager.instance().warn(null, "..."`

## Steps to reproduce the problem
Startup any database with global log level set to WARN

**Comment by cmassi** [comment]
The warning about MaxDirectMemorySize can be found at startup, and is due to the lack of a correct value for required parameter; the auto configuration will try to set a value, which might not be fine for your server instance <br>
2016-12-02 12:51:18:200 INFO  OrientDB auto-config DISKCACHE=491MB (heap=491MB direct=491MB os=16,384MB), assuming maximum direct memory size equals to maximum JVM heap size [orientechnologies] <br>
<br> If you set to null in OLogMananger the first parameter, which is the iRequester, the DEFAULT_LOG ="com.orientechnologies" will be set in requesterName, to run Logger.getLogger(requesterName), and output will be
<br>
WARNI MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=16384m option when you start the JVM. [orientechnologies] <br>
<br> You probably simply have to set an appropriate value for direct memory.

**Comment by rohrl** [comment]
Setting the system property is a separate issue.

The problem here is that the log requester is "java.lang.Class" which is incorrect, it should be "OMemory" or at least the default "com.orientechnologies"

We are using log4j and forward Orient logs to log4j. 
Normally we can set different levels of logging for particular libraries, using the package prefix. 
But in this case, we can't mute this logs, unless we set it to "java.lang.Class"

**Comment by lvca** [comment]
I don't know why it was NULL, there is no reason for that. Fixed, now it's `OMemoryAndLocalPaginatedEnginesInitializer`.
