### ISSUE TITLE
Problem about OStateMementCache's synchronized method 'get'

### ISSUE THREAD

**Issue by BruceMu** [orientechnologies/orientdb#6974]
## OrientDB Version, operating system, or hardware.
OrientDB 2.2.12

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

Hi, 

I use plocal orientDB ,and submit a lot of sql-like query at the same time. I find many sql querys are blocked on the `OStateMementCache` object's `get` method , like

<img width="811" alt="git_orient" src="https://cloud.githubusercontent.com/assets/5007167/20929839/5d22a558-bc06-11e6-8de2-ecb73e9912c7.png">

After reading the code, I think is it necessary to use `Synchronized` method ? If there are hundreds of concurrent querys, the last one may wail a long time. It may be not a good idea.

**Comment by luigidellaquila** [comment]
Hi @BruceMu 

I think you're right, we could just synchronize the internal map and reduce the contention a lot.
I'll work on it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @BruceMu 

I just pushed a fix for this. I did some more fine-grained locks that do not involve query parsing (that is the expensive part of that method).

The fix is in 2.2.x branch and will be released with 2.2.14

This should completely solve the problem, but please reopen if you see anything that can be improved.

Thanks

Luigi
