### ISSUE TITLE
Problem about batch write

### ISSUE THREAD

**Issue by BruceMu** [orientechnologies/orientdb#6981]
version 2.2.12

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

Hi,
I found flush pages to STAT disk is really slow. I traced the cost of every write, as : 

![write_trace](https://cloud.githubusercontent.com/assets/5007167/20998377/4c2e0aec-bd48-11e6-91e8-ad1b49397fbc.png)

and the iostat is : 

![writeio](https://cloud.githubusercontent.com/assets/5007167/20998396/80d3390c-bd48-11e6-97e2-af3078076253.png)

We can see the `await` time is very long, but the `svctm` time is short.  

The io write  can be optimize , in your code : 
```java
while (entriesIterator.hasNext()) {
        Map.Entry<PageKey, PageGroup> entry = entriesIterator.next();

        final PageGroup group = entry.getValue();
        final PageKey pageKey = entry.getKey();

        if (lastPageIndex >= 0) {
          if (pageKey.pageIndex != lastPageIndex + 1) {
            flushedRegions++;

            if (flushedWritePages > writePagesToFlush && flushedRegions >= 4)
              break;
          }
        }

        final OCachePointer pagePointer = group.page;
        final boolean weakLockMode =
            currentTime - group.creationTime < groupTTL && !forceFlush && !tooOldLsn(pagePointer.getLastFlushedLsn(),
                maxSegmentDistance);

        if (group.recencyBit && weakLockMode) {
          group.recencyBit = false;
          continue;
        }

        final Lock groupLock = lockManager.acquireExclusiveLock(entry.getKey());
        try {
          if (group.recencyBit && weakLockMode) {
            group.recencyBit = false;
            continue;
          } else {
            group.recencyBit = false;

            if (!pagePointer.tryAcquireSharedLock())
              continue;

            try {
              final ByteBuffer buffer = pagePointer.getSharedBuffer();
              flushPage(pageKey.fileId, pageKey.pageIndex, buffer);

              final OLogSequenceNumber flushedLSN = ODurablePage.getLogSequenceNumberFromPage(buffer);
              pagePointer.setLastFlushedLsn(flushedLSN);
            } finally {
              pagePointer.releaseSharedLock();
            }

            pagePointer.decrementWritersReferrer();
            pagePointer.setWritersListener(null);

            entriesIterator.remove();
          }
        } finally {
          lockManager.releaseExclusiveLock(entry.getKey());
        }

        lastPageKey = pageKey;

        flushedWritePages++;
        lastPageIndex = pageKey.pageIndex;

        writeCacheSize.decrement();
      }
```
every page flush is an io write request, if a lot pages waiting to flush, they must wait. Merge some page flush into one io request may be better.

Hope you think about it , thanks !

**Comment by laa** [comment]
Hi ,
Thank you very much for such feedback .
You are right we can merge single pages in several once and flush them . That is already implemented in separate branch .
It is called ycsb_freeze . But we found out that still we have a lot of random io operations . To avoid that we are working on new abstraction layer above file system which will remap pages are going to be written into pages which forms continuous sequential chunk of data and alongside pages will be compressed. So in nutshell we are going to use 100% of dusk throughput and even a little bit more )) (because of compression ). Now we are making performance measurements and calculations to be sure that we do not miss anything.  If you have desire to contribute in implementation of such layer  ping me.

**Comment by laa** [comment]
Closed because of copy of already existing issue
