### ISSUE TITLE
Studio: interrupt button not working

### ISSUE THREAD

**Issue by tbertels** [orientechnologies/orientdb#7006]
## OrientDB Version, operating system, or hardware.
- 2.2.13

## Operating System
- [ ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
The interrupt button should stop the request, but nothing happens.
## Steps to reproduce the problem
* Import the MovieRatings public database
* Increase the limit to 9999999 in the Query configuration
* Start a long request (by example SELECT expand(both().both()) FROM Users)
* Click on the Interrupt button

**Comment by maggiolo00** [comment]
@tbertels 

i think probably the problem is not the interrupt button but the fact that this query

SELECT expand(both().both()) FROM Users

loads the entire db, and the expand function keeps the cache of the traversed records, 
so the server becomes rapidly unavailable and it's not able to interrupt the query

**Comment by lvca** [comment]
@maggiolo00 can the expand be interruptable?

**Comment by maggiolo00** [comment]
The problem is not with expand. It was that the server was going in OOM and cannot fulfill  the interrupt request
