### ISSUE TITLE
Offheap memory is leaking

### ISSUE THREAD

**Issue by lodrion** [orientechnologies/orientdb#7007]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ x] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

We are using recommended settings for off-heap storage (-XX:MaxDirectMemorySize=512g) and limit storage.diskCache.bufferSize to 2G

Running jmxterm and querying OByteBufferPoolMXBean

```

#bean is set to com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean
$>get -i *
#mbean = com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean:
BufferSize = 65536; (BufferSize)
AllocatedBufferCount = 23922; (AllocatedBufferCount)
OverflowBufferCount = 0; (OverflowBufferCount)
BuffersInThePool = 0; (BuffersInThePool)
AllocatedMemory = 2147483648; (AllocatedMemory)
AllocatedMemoryInMB = 2048; (AllocatedMemoryInMB)
AllocatedMemoryInGB = 2.0; (AllocatedMemoryInGB)

```

Looks reasonable. But looking at the JVM's own view of memory consumption, things do not look so cheerful:

```

$>bean java.lang:type=Memory
#bean is set to java.lang:type=Memory
$>get -i *                  
#mbean = java.lang:type=Memory:
Verbose = false; (Verbose)

ObjectPendingFinalizationCount = 0; (ObjectPendingFinalizationCount)

HeapMemoryUsage = { 
  committed = 5359796224; (committed)
  init = 5368709120; (init)
  max = 5359796224; (max)
  used = 1782962328; (used)
 }; (HeapMemoryUsage)

NonHeapMemoryUsage = { 
  committed = 2903453696; (committed)
  init = 2555904; (init)
  max = -1; (max)
  used = 1175846984; (used)
 }; (NonHeapMemoryUsage)

ObjectName = java.lang:type=Memory; (ObjectName)

```
Heap memory allocation is stable and obeys the set maximum  ( -Xms5g -Xmx5g )
Committed non-heap memory usage is almost 3G now and is climbing without any limit especially during high write throughput. This eventually leads to system OOM killer just shutting down the process altogether. Sometimes with unfortunate consequences to the integrity of the database.

**Comment by lodrion** [comment]
There is a possibility that you are hitting this http://www.evanjones.ca/java-bytebuffer-leak.html since ByteBuffer.allocate() is all over the code

**Comment by laa** [comment]
@lodrion what version do you use ?

**Comment by laa** [comment]
@lodrion could you also activate leak detector http://orientdb.com/docs/2.2/Leak-Detector.html ?

**Comment by lodrion** [comment]
We are on 2.2.12. I will attempt the load with the leak detector today

**Comment by laa** [comment]
@lodrion any updates on this ?

**Comment by lodrion** [comment]
I ran with the leak detector and nothing interesting popped out. 
We've increased the memory on the machine and seen the consumption stabilize at a relatively high level (13Gb) while jumping to above 32Gb at high loads. So this makes me believe that this is a byte buffer leak (having enough memory allows all threads to "cache" sufficiently long buffers)

**Comment by laa** [comment]
@lodrion we use non direct byte buffer only in one place I will change the code to use direct byte buffer there too. Will provide you update shortly.

**Comment by laa** [comment]
Hi @lodrion could you build 2.2.x branch and verify memory usage consumption ?

**Comment by weixliu** [comment]
#7047 I think I have the same problem, I can't restrict the orientdb memory consuming.

**Comment by taburet** [comment]
@lodrion @weixliu @jamieb22 guys, could you please provide the contents of `java.nio:type=BufferPool,name=direct`, `java.lang:type=Memory` and `com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean` beans? Lets compare what JVM and OrientDB are saying about direct byte buffers. That may be some other native memory leak, not direct byte buffers leak.

**Comment by weixliu** [comment]
@taburet 
How I get the beans information? I enable JMXPlugin in orientdb-server-config.xml, then how to connect it through jmxterm.

**Comment by weixliu** [comment]
`java.nio:name=direct,type=BufferPool`
```
$>bean java.nio:name=direct,type=BufferPool
#bean is set to java.nio:name=direct,type=BufferPool
$>get -i *
#mbean = java.nio:name=direct,type=BufferPool:
Count = 16; (Count)

Name = direct; (Name)

MemoryUsed = 11811291139; (MemoryUsed)

TotalCapacity = 11811291139; (TotalCapacity)

ObjectName = java.nio:type=BufferPool,name=direct; (ObjectName)

```

`java.lang:type=Memory`
```
$>bean java.lang:type=Memory
#bean is set to java.lang:type=Memory
$>get -i * 
#mbean = java.lang:type=Memory:
Verbose = false; (Verbose)

HeapMemoryUsage = { 
  committed = 8586264576; (committed)
  init = 8589934592; (init)
  max = 8586264576; (max)
  used = 2994548432; (used)
 }; (HeapMemoryUsage)

NonHeapMemoryUsage = { 
  committed = 33357824; (committed)
  init = 24576000; (init)
  max = 136314880; (max)
  used = 32949728; (used)
 }; (NonHeapMemoryUsage)

ObjectPendingFinalizationCount = 0; (ObjectPendingFinalizationCount)

ObjectName = java.lang:type=Memory; (ObjectName)
```

`com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean`
```
$>bean com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean
#bean is set to com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean
$>get -i *
#mbean = com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean:
BufferSize = 65536; (BufferSize)

AllocatedBufferCount = 176117; (AllocatedBufferCount)

OverflowBufferCount = 0; (OverflowBufferCount)

BuffersInThePool = 0; (BuffersInThePool)

AllocatedMemory = 11811160064; (AllocatedMemory)

AllocatedMemoryInMB = 11264; (AllocatedMemoryInMB)

AllocatedMemoryInGB = 11.0; (AllocatedMemoryInGB)
```

Is there sth wrong with this?

**Comment by taburet** [comment]
@weixliu seems like nothing bad, JVM and OrientDB reports about the same amount of allocated direct memory, the difference is about 100KB. `NonHeapMemoryUsage` also looks good to me, there is only 30MB of allocated memory. Please capture the JMX beans next you will suspect a leaky situation, at least we will know what kind of a memory is leaking. I assume your `storage.diskCache.bufferSize` is at least 10GB, right?

Seems like `NonHeapMemoryUsage` doesn't include direct memory allocations, have tested this separately. So in case of @lodrion something else is leaking (2.7GB in `NonHeapMemoryUsage`), since OrientDB doesn't do any native allocations other than direct memory byte buffers.

**Comment by cmassi** [comment]
The Non-Heap Memory reported by MemoryMXBean is documented : <br>
https://docs.oracle.com/javase/8/docs/api/java/lang/management/MemoryMXBean.html .<br>
You should trace gc log details first, to see how much memory is used in each segment <br>
Then you can set fixed values of all segments, and retry, e.g: -Xms8g -Xmn3g -Xmx8g -XX:MetaspaceSize=1g -XX:MaxMetaspaceSize=1g -XX:CompressedClassSpaceSize=512m -XX:-UseAdaptiveSizePolicy -XX:InitialCodeCacheSize=128m -XX:ReservedCodeCacheSize=128m <br>
Then check again with any jmx client (e.g: jmxterm,jconsole) and also see memory mapped files, with : bean java.nio:name=mapped,type=BufferPool

**Comment by jamieb22** [comment]
Here is ours... AllocatedBufferCount rises steadily...
```
$>get -i *
#mbean = com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean:
AllocatedBufferCount = 145336; (AllocatedBufferCount)
OverflowBufferCount = 0; (OverflowBufferCount)
AllocatedMemory = 9663676416; (AllocatedMemory)
BufferSize = 65536; (BufferSize)
BuffersInThePool = 0; (BuffersInThePool)
AllocatedMemoryInMB = 9216; (AllocatedMemoryInMB)
AllocatedMemoryInGB = 9.0; (AllocatedMemoryInGB)
$>get -i *
#mbean = com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean:
AllocatedBufferCount = 145726; (AllocatedBufferCount)
OverflowBufferCount = 0; (OverflowBufferCount)
AllocatedMemory = 9663676416; (AllocatedMemory)
BufferSize = 65536; (BufferSize)
BuffersInThePool = 0; (BuffersInThePool)
AllocatedMemoryInMB = 9216; (AllocatedMemoryInMB)
AllocatedMemoryInGB = 9.0; (AllocatedMemoryInGB)
```

**Comment by taburet** [comment]
@jamieb22 if `AllocatedMemoryInMB ` doesn't go too far beyond `storage.diskCache.bufferSize` value, everything is good. `AllocatedBufferCount` grows because the file cache is being populated, which size is limited by `storage.diskCache.bufferSize`. It counts the internal small byte buffers of `BufferSize` bytes in size, not the actual direct memory byte buffers. So the memory usage is `AllocatedBufferCount * BufferSize = 145726 * 65536 / 1024^2 = 9 107,875 MB`, which should be bellow the `storage.diskCache.bufferSize`.

**Comment by jamieb22** [comment]
```
$>bean java.nio:type=BufferPool,name=direct
#bean is set to java.nio:type=BufferPool,name=direct
$>get -i *
#mbean = java.nio:type=BufferPool,name=direct:
TotalCapacity = 12424011309; (TotalCapacity)
MemoryUsed = 12424011309; (MemoryUsed)
Name = direct; (Name)
Count = 470; (Count)
ObjectName = java.nio:type=BufferPool,name=direct; (ObjectName)
$>bean java.lang:type=Memory
#bean is set to java.lang:type=Memory
$>get -i *
#mbean = java.lang:type=Memory:
HeapMemoryUsage = { 
  committed = 6091177984; (committed)
  init = 268435456; (init)
  max = 6091177984; (max)
  used = 4649219824; (used)
 }; (HeapMemoryUsage)
NonHeapMemoryUsage = { 
  committed = 332251136; (committed)
  init = 2555904; (init)
  max = -1; (max)
  used = 322970440; (used)
 }; (NonHeapMemoryUsage)
ObjectPendingFinalizationCount = 0; (ObjectPendingFinalizationCount)
Verbose = false; (Verbose)
ObjectName = java.lang:type=Memory; (ObjectName)
$>bean com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean
#bean is set to com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean
```

**Comment by jamieb22** [comment]
What is the default value for storage.diskCache.bufferSize? We are not setting this property at the moment?

**Comment by taburet** [comment]
@jamieb22 

if `-XX:MaxDirectMemorySize` is not set, it will be auto-configured to `-Xmx`. If `-XX:MaxDirectMemorySize` is set, it will be auto-configured to `machine_physical_memory - Xmx - 2GB`, but not larger than `-XX:MaxDirectMemorySize`. I strongly recommend to set `storage.diskCache.bufferSize` to some reasonable value. In general, `orient_db_memory = heap + direct`, `heap <= Xmx`, `direct <= storage.diskCache.bufferSize <= XX:MaxDirectMemorySize`.

Regarding `java.nio:name=mapped,type=BufferPool` that's strange, OrientDB don't use mapped memory at all. Lets try to limit the `storage.diskCache.bufferSize` and set `XX:MaxDirectMemorySize = storage.diskCache.bufferSize * 2`, just in case some other part of your system also needs direct memory.

**Comment by jamieb22** [comment]
Don't you think these default params are a bit aggressive? I mean, is your  thinking that Orient DB will be the only software running on a given server? Alot of disks have inbuilt caching .. so do we really need such a huge software based cache? Currently, our MaxDirectMemorySize is set to 512g. From what I can see you guys are setting all the Orient DB defaults for max performance. A useful analogy might be ... shipping an Intel processor over clocked or selling a BMW tuned for extreme performance. Can you set reasonable defaults. Like storage.diskCache.bufferSize=32 (32MB).

**Comment by cmassi** [comment]
Any jvm require tuning, because autoconfiguration does not fit all the needs, and often is executed only at startup. <br>
By default a jvm might use all the available resources on your system (stack, direct memory, cpu), unless you set some parameters for your own installation which limit resources in use (e.g: Xmx, MaxMetaspaceSize, ReservedCodeCacheSize, ParallelGCThreads, ThreadStackSize, MaxDirectMemorySize, ...). <br> 
You should check peak usage of [embedded] orientdb server with load tests, and trace resources in use. <br> 
If you are running an orientdb 2.2.x server, it will use both direct memory and java heap, so you have to set a limit for both parameters. In server.sh for a standalone server, current jvm setting are the following: Xmx is 2g and MaxDirectMemorySize is virtually unlimited (512g). <br> If you are running other processes on your server, you have to add your own storage.diskCache.buffersize as the max direct cache to be used by orientdb threads to create direct ByteBuffers, allocated in memory chunks of memory.chunk.size=2g.

**Comment by jamieb22** [comment]
I get the tuning part. We've been doing that for more than twenty years. This issue is the specific default settings of Orient. Speaking for the embedded scenario, the default settings leave no room for any other software components. Another matter, our software keeps crashing with Orient 2.2.14. Heap memory is stable. Virtual memory is the problem.

**Comment by jamieb22** [comment]
Further to the above, since embedded vs standalone have different requirements in terms of memory management, I would suggest to confine the aggressive memory settings to the standalone Orient server itself, and for the API level integration, use conservative defaults. I think part of the problem is that the core Orient developers typically work with their database in standalone mode, and thus the needs of embedded users are often overlooked. 

The other thing that I would have to take issue with, is that manner in which these memory settings were changed. They were applied as part of a point release update. Since the memory requirements changed so radically, OME occurred in many production environments, databases crashed, corruption occurred, and data was lost (aka. the butterfly effect). For this reasons, changes that radically affect the functioning or requirements of software, should never be applied to point releases. i.e.  One should  not expect radical changes in requirements, from v2.2.13 -> v2.2.14, nor even v2.2 -> v2.3. Only v2 - v3! 

Orient DB's releases are powered by great enthusiasm (which is good), albeit also with a touch of impulsivity (which is very bad, especially when it comes to databases).

**Comment by taburet** [comment]
@weixliu @lodrion @jamieb22 Guys, I have analysed all the provided information from #7047, #6922 and #7007, what I have learned:

1. Direct memory usage reported by JVM doesn't go far beyond `storage.diskCache.bufferSize`, information from `java.nio:type=BufferPool,name=direct` and `com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean` match with some minor differences, so I assume there is no leaks in ODB's direct byte buffers management. If you spotted a counterexample, please capture the jmx beans information and send it to me along with the actual `storage.diskCache.bufferSize` value. If you unhappy with the default/auto-configured `storage.diskCache.bufferSize`, just set the value you like.

2. `NonHeapMemoryUsage` doesn't include direct memory allocations, but it includes things like memory allocated for the stacks of running threads. The value is correlated well with the number of running threads, with the default JVM setting of 1MB thread stack size and 2000 threads running the usage may easily go above 2GB. In the one of the provided thread dumps I spotted about 1800 active threads and only minority of them are related to ODB. Please capture a thread dump and send it me if you suspect ODB is guilty.

3. _Mapped_ memory "usage" reported by `java.nio:name=mapped,type=BufferPool` bean may go really high, that's because of ODB full text indexing, which uses Lucene, which uses memory mapped files to do its job. As Lucene developers [claim](http://blog.thetaphi.de/2012/07/use-lucenes-mmapdirectory-on-64bit.html), there is nothing dangerous in this situation.

**Comment by laa** [comment]
@lodrion any updates for this issue ?

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.
