### ISSUE TITLE
Server seems deadlock with multiple concurrent binary clients

### ISSUE THREAD

**Issue by weixliu** [orientechnologies/orientdb#7047]
## OrientDB Version, operating system, or hardware.
- v2.2.13

## Operating System
- [ ] Linux

1. The first problem is similar with #5821. All server connection with binary clients are waiting for lock. With jstack I can't find any deadlock information, but all connection are waiting. So I think it's a deadlock problem. 
Jstack information: https://gist.github.com/weixliu/281f154908ed52ba65daa4b82c24db0d

When I encounter this problem, I found that if I continue all the client connection, eventually after a long time [ about 1 hour] I got this information (https://gist.github.com/weixliu/4fb7878fecd237d8c26c7ec98a79c356) in client. Then it seems that some server connection resume runnable.

Finally there exists no useful information in server log , there exists no today or yestoday information in the server log, so I think it's no meaning show the log.

2. Also I have a question, my server start script i set Xmx 10G, but when I using top I found that orientdb consume a lot memory.( top command show it consum 54.6% memory, about 30G+ )I think the memory is too heavy. I don't know whick part apply so much memory( directed Memory config?).

`top command result :  1466 root      20   0 64.6g  34g 1852 S  8.3 54.6 574:28.92 java `

Finally I paste my orientdb config: https://gist.github.com/weixliu/4f884d976dbab2d2bf2d65fdcae676ed

**Comment by laa** [comment]
@weixliu seems problem is not threads are stack problem is that you seems out of space on disk. Is it possible ?

**Comment by laa** [comment]
About your second question, OrientDB uses as much memory as possible to speed up all things. Is it a problem for you ?

**Comment by weixliu** [comment]
@laa 
I check that there exists 1.4T free space in my disk. And the database only need 54G disk space. 

About the second problem I got that. So I should install orientdb to a cleaning server.

**Comment by laa** [comment]
@weixliu according to stack trace 
```
OrientDB (/172.16.6.213:2424) <- BinaryClient (/172.16.6.212:51978)" daemon prio=10 tid=0x00007f9b94058800 nid=0x6e10 waiting on condition [0x00007f9bcca38000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000073173abd8> (a java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:425)
	at java.util.concurrent.FutureTask.get(FutureTask.java:187)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.flush(OWOWCache.java:703)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.flush(OWOWCache.java:719)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeFullCheckpoint(OAbstractPaginatedStorage.java:2772)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.synch(OAbstractPaginatedStorage.java:2273)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkLowDiskSpaceFullCheckpointRequestsAndBackgroundDataFlushExceptions(OAbstractPaginatedStorage.java:4075)
```
As you can see db thinks that it is not enough space and tries to cut databse jounal to find more space. 
Is it possible that OS limits or file system permissions do not allow to fill all 1.4 T space?

**Comment by weixliu** [comment]
@laa 
I start orientdb with root, so maybe it's not because disk space. Is there sth with my configuration not appropriate? Disk space can't explain that when network timeout and client reconnect server, some threads become runnable.

Is there methods to restrict the orientdb memory?Because in the server, I also install some other service exception orientdb, orientdb consuming large memory will lead other service become slow.

**Comment by laa** [comment]
@weixliu they become runnable because new threads are started. 
Yes, there is a method to restrict memory Set property storage.diskCache.bufferSize to the desired memory in megabytes.  A suggest you, to do following to understand the reason of this freeze.
If you encounter this situation again, please make a thread dump and check whether stack trace which I sent to you exists, if so please check disk space at this time and send all results to me.

**Comment by weixliu** [comment]
@laa 
1.  I set storage.diskCache.bufferSize to 4096 and in server.sh I also set Xmx to 8G. But I also can't restrict the memory (Below about 50%+ memory, total 64G). Any other config to restrict the memory?

`17951 root      20   0 41.3g  32g 4472 S 51.6 51.6 193:11.92 java`

config: https://gist.github.com/weixliu/d806a6fee2c6e6c20fd9840cc66eae05

2. When I import data again, the import data rate freeze for a while, then I found there is stack trace you sent to me, but the disk space is also 50% at that time.  The difference is that it's only freeze for a while then continue.

In my client log: https://gist.github.com/weixliu/d455e833a07e62f0cad79a4441ff7361
It freeze about five minutes. (in the log download is real download number/total need download number, process number is the real number insert into orientdb)

thread dump: https://gist.github.com/weixliu/811f3e6baf6b7ac93d002e2264523a62

**Comment by laa** [comment]
Hi, @weixliu 
1. About free space detection, could you try to use https://github.com/orientechnologies/orientdb/tree/ycsb_freeze branch?
2. For unlimited memory consumption could you try latest https://github.com/orientechnologies/orientdb/tree/2.2.x branch and check memory consumption?

One more question, could you write a simple java program which calls https://docs.oracle.com/javase/7/docs/api/java/io/File.html#getUsableSpace() and print the output (you shoul run this program inside db folder) ?

**Comment by cmassi** [comment]
Can use this sample https://docs.oracle.com/javase/tutorial/essential/io/examples/DiskUsage.java 
Compile with java7+ and run with db folder as argument, e.g: "java DiskUsage $ORIENTDB_HOME/databases/GratefulDeadConcerts"

**Comment by weixliu** [comment]
@laa 
About getUsableSpace() test I use cmassi program test get below information. But this is not the time I get the checkLowDiskSpaceFullCheckpointRequestsAndBackgroundDataFlushExceptions information. Later if I encounter that stack trace in thread dump I will test this program then reply.
```
[root@wmcloud3 databases]# ll
total 48
-rw-r--r--. 1 root root  2000 1月   4 09:41 DiskUsage.class
drwxrwxr-x. 2 root root  4096 1月   3 10:40 GratefulDeadConcerts
drwxr-xr-x. 2 root root  4096 1月   3 17:11 OSystem
drwxr-xr-x. 2 root root 36864 1月   4 05:13 wmcloud_cpwsw
[root@wmcloud3 databases]# java DiskUsage .
Filesystem                 kbytes         used        avail
/wm (/dev/sdb1)        2882717020   1396043856   1340239576
```

I'll try 2.2.x and check that if I can restrict the memory according Xmx and storage.diskCache.bufferSize then update this comment. I think this is more import than the freeze problem(freeze problem now is just a performance, memory problem is an available problem~).

**Comment by weixliu** [comment]
@laa 
1. I found the reason why I can't restrict the memory. In the server.sh script there exists `-XX:MaxDirectMemorySize=512g` , so even though I set `storage.diskCache.bufferSize` in config/orientdb-server-config.xml, it is not effective. so I guess MaxDirectMemorySize equals storage.diskCache.bufferSize, I found if I decrease MaxDirectMemorySize, the storage.diskCache.bufferSize increase also. I suggest lowering the default MaxDirectMemorySize in server.sh.
2. Aboult the freeze problem I'll also keep tracking.

**Comment by cmassi** [comment]
The java process is always a little bit bigger then expected (due to code cache, stacks , libraries, and more), but should allocate the huge memory segments as requested, so you can have:
- java heap+metaspace+classpace (or permanent)
- heap ByteBuffer.allocate()
- native ByteBuffer.allocateDirect()
- native Unsafe.allocateMemory() 

To avoid changes in java heap usage in your tests, set min=max and do not use adaptive size policy in oracle jvm, e.g: -Xms=4g -Xmn=1g -Xmx=4G -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m -XX:CompressedClassSpaceSize=128m -XX:-UseAdaptiveSizePolicy (or for java 7 -XX:PermSize=256m -XX:MaxPermSize=256m); tune sizes looking at -XX:+PrintGCDetails output
See also https://blogs.oracle.com/jonthecollector/entry/the_unspoken_the_why_of

To limit usage in jvm of temporary direct buffers as thread-local caches, the orientdb storage code is going to be changed, in latest 2.2.x branch, to use direct ByteBuffers instead of heap ByteBuffer; or you can try to get fixed buffers using in oracle jvm 8u112+ the -Djdk.nio.maxCachedBufferSize=262144 (256k)
http://www.evanjones.ca/java-bytebuffer-leak.html

To limit the direct memory usage, set the jvm upper limit -XX:MaxDirectMemorySize=6g and define the orientdb property -Dstorage.diskCache.bufferSize=4096 . The default MaxDirectMemorySize=512g means, unlimited, so you can tune it with storage.diskCache.bufferSize and preallocate by memory.chunk.size (2g default). In jvm code, the ByteBuffer.allocateDirect() uses internally Unsafe.allocateMemory(), but only when there is enough memory (otherwise OOM exception)
You might be interested in these blogs from Andrey
http://andreylomakin.blogspot.it/2016/05/do-not-forget-to-set-xxmaxdirectmemory.html
http://andreylomakin.blogspot.it/2016/05/how-to-calculate-maximum-amount-of.html

You cannot control explicit usage of Unsafe.allocateMemory(), but is not used in orientdb code

At startup you can use -XX:+PrintFlagsFinal to see jvm XX flags, and -Denvironment.dumpCfgAtStartup=true to see orientdb settings

**Comment by laa** [comment]
@weixliu 

> storage.diskCache.bufferSize increase also

How did you find that ?

**Comment by weixliu** [comment]
@laa 
Sorry, I have a type error. It should be decrease.

I set storage.diskCache.bufferSize in config/orientdb-server-config.xml is not effective. So I set it in server.sh with -Dstorage.diskCache.bufferSize.

I also have the freeze problem. I record the orientdb process top record, when cpu high, the insert data freeze; when cpu very low(thread dump show checkLowDiskSpaceFullCheckpointRequestsAndBackgroundDataFlushExceptions), the insert data freeze. 
I also found that the memory is increasing all the time. Maybe because I use 2.2.14, there is off-heap leak.(Like #7007 )

https://gist.github.com/weixliu/291f9a11f3139232d8b445f1d3f610e6

I have a question, every once in a while the cpu will be high. Is that because orientdb implementing cause?

**Comment by laa** [comment]
@weixliu freeze problem is already solved in develop-cache branch I am integrating it in develop branch. 

@weixliu did you try latest 2.2.x to check whether direct memory leak issue is resolved ?

**Comment by weixliu** [comment]
@laa 
About the direct memory leak issue I have a test env is running latest 2.2.x orientdb. I'll execute massive inserting later and then feedback.

**Comment by laa** [comment]
@weixliu did you have a chance to run a test ?

**Comment by taburet** [comment]
CC from #7007:

@weixliu @lodrion @jamieb22 Guys, I have analysed all the provided information from #7047, #6922 and #7007, what I have learned:

1. Direct memory usage reported by JVM doesn't go far beyond `storage.diskCache.bufferSize`, information from `java.nio:type=BufferPool,name=direct` and `com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean` match with some minor differences, so I assume there is no leaks in ODB's direct byte buffers management. If you spotted a counterexample, please capture the jmx beans information and send it to me along with the actual `storage.diskCache.bufferSize` value. If you unhappy with the default/auto-configured `storage.diskCache.bufferSize`, just set the value you like.

2. `NonHeapMemoryUsage` doesn't include direct memory allocations, but it includes things like memory allocated for the stacks of running threads. The value is correlated well with the number of running threads, with the default JVM setting of 1MB thread stack size and 2000 threads running the usage may easily go above 2GB. In the one of the provided thread dumps I spotted about 1800 active threads and only minority of them are related to ODB. Please capture a thread dump and send it me if you suspect ODB is guilty.

3. _Mapped_ memory "usage" reported by `java.nio:name=mapped,type=BufferPool` bean may go really high, that's because of ODB full text indexing, which uses Lucene, which uses memory mapped files to do its job. As Lucene developers [claim](http://blog.thetaphi.de/2012/07/use-lucenes-mmapdirectory-on-64bit.html), there is nothing dangerous in this situation.

**Comment by laa** [comment]
@weixliu any updates on this issue ?

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.

**Comment by weixliu** [comment]
Sorry, I have a long holiday so that I can't do that test. It seems that the memory is controled.
I use 2.2.15-snapshot, when I insert data I get a deadlock in jstack information. 
https://gist.github.com/weixliu/305351c3eedb926c2d3cc7579cce7707

I see that 2.2.16 is released, I'll try that.
