### ISSUE TITLE
Security Issue: "writer" has no rights to create a class, but can import whole DB

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#7057]
Pretty strange situation: writer by default can't create a class due to absence of SYSTEM_CLUSTERS permissions, but at the same time he can easily import whole DB. Security Issue? Probably ODatabaseImport class needs more security checks.

## OrientDB Version, operating system, or hardware.
2.1.19

**Comment by lvca** [comment]
@SDIPro are you able to reproduce it in 2.2.x too?

**Comment by SDIPro** [comment]
This was reproduced and was caused by a lack of permission on updating the internal cluster (not SYSTEM_CLUSTERS).

We ultimately decided that the writer role should not be able to modify the schema as well.  Only admin roles can.

Additional checks, related to clusters and the schema were added throughout.

This was changed for 2.1.x and 2.2.x.  It's already live in the latest 2.2.15 release and is in the latest 2.1.x-snapshot.

@PhantomYdn please test with the latest 2.1.x-snapshot.  If this is still an issue, please re-open it.
