### ISSUE TITLE
Teleporter [question]: unable to view the imported database in studio

### ISSUE THREAD

**Issue by janag** [orientechnologies/orientdb#7061]
## OrientDB Version, operating system, or hardware.
orientdb-enterprise-2.2.14 [x]

## Operating System
- [x ] MacOSX

## Steps to reproduce the problem

1. start  the server.sh

2. start the Teleporter (localhost:2480-> Server Management -> Teleporter)

3. populate the fields:
    driver: mysql
    url: jdbc:mysql://localhost:3306/testdb
    username: xxxxx
    password: xxxxx
    orientdb url: plocal:$ORIENTDB-HOME/databases/testdb

4. click on "test connection"  and it should display "connection is alive" 

5. click on "run"

6. result:

<img width="856" alt="screen shot 2017-01-07 at 8 44 26 am" src="https://cloud.githubusercontent.com/assets/1167566/21742478/ab45a7cc-d4b5-11e6-88d3-53666ecbaad3.png">

## Expected behavior and actual behavior
Teleporter imported the mysql database successfully

Tried to view the imported database in Studio but did not see the imported database option in the dropdown control

## Question: 
How to view the imported database in studio?

========

Thanks!!!

**Comment by G4br13l3** [comment]
Hi @janag, do you see the "testdb" folder in "$ORIENTDB-HOME/databases/" path?

**Comment by G4br13l3** [comment]
Moreover in orientdb env variables are recognized when the canonical syntax with "_" is adopted. If you use $ORIENTD-HOME instead of $ORIENTD_HOME it's possible that orientdb does not recognize the env variable, so a $ORIENTDB-HOME directory is created in the root path.<br>
You should check that the name of the env variable defined in your system is $ORIENTD_HOME, then try again running teleporter with plocal:$ORIENTDB_HOME/databases/testdb path or with an explicit path as well.

**Comment by janag** [comment]
>> do you see the "testdb" folder in "$ORIENTD_HOME/databases/" path?
I didn't see the testdb folder

>> You should check that the name of the env variable defined in your system is $ORIENTD_HOME, then try again running teleporter with plocal:$ORIENTDB_HOME/databases/testdb path or with an explicit path as well.

Actually, I've used an explicit path instead of env variable.

Thanks,
Jana

**Comment by G4br13l3** [comment]
You can't find your database from Studio because is not located in $ORIENTDB_HOME/databases/ of course. As the process terminated without errors I guess that maybe it's just a typo in the path: in fact with plocal you can write the target database in any path, and no exception are thrown if the target directory is not located in $ORIENTDB_HOME/databases/.<br/>
I can just advise you to perform another migration in plocal paying attention to the path.
<br/><br/>
If it does not work again, you can import the database through the remote protocol following these steps:<br/>
- create a new database in the login page of studio, e.g. "testdb"
- go to the teleporter page and use as target path "remote:localhost/databases/testdb" (we use "testdb" in the path as the database just created in the login page).
<br/><br/>
Let me know if you succeed, thanks.

**Comment by janag** [comment]
>> create a new database in the login page of studio, e.g. "testdb"
>> go to the teleporter page and use as target path "remote:localhost/databases/testdb" (we use "testdb" in the path as the database just created in the login page).

AWESOME - I tried again with aforementioned steps and it worked like a charm!! :-)

Thank You,
Jana

**Comment by G4br13l3** [comment]
I'm glad to hear that, enjoy it!
Thanks.
