### ISSUE TITLE
Cannot index record #58:0: found duplicated  key 'null' in index 'v_user.ID' previously assigned to the record #59:

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#7068]
## OrientDB Version, operating system, or hardware.

2.2.14

## Operating System

- [ X] Linux

## Expected behavior and actual behavior

On Orient DB corruption, null values appear on vertex properties. Therefter, OrientGraph object cannot be constructed and database opened due to fact that multiple 'null' keys violate uniqueness constraint.

2017-01-10 07:17:23 p.c.s.a.d.DatabaseService [ERROR] failed to connect to database:Cannot index record #58:0: found duplicated 
key 'null' in index 'v_user.ID' previously assigned to the record #59:0

Question: How should Orient best handle this scenario? Shouldn't the properties be deleted, rather than represented as null values?

**Comment by laa** [comment]
@jamieb22 you should set option com.orientechnologies.orient.core.config.OGlobalConfiguration#INDEX_IGNORE_NULL_VALUES_DEFAULT to true it will solve given issue. About DB corruption we found what causes this issue and fix most of the issues in 2.2.x and some of the issues in 3.0 and 3.1 versions. The issues which are moved to 3.x version are very rare, and there is an extremely low probability that will affect database in your case.

P.S. Of course, OOM will be fixed in 2.2.x version.
