### ISSUE TITLE
java.lang.ClassCastException when execute asyn save

### ISSUE THREAD

**Issue by otaviojava** [orientechnologies/orientdb#7104]
## OrientDB Version, operating system, or hardware.
v    2.2.15

## Operating System
- [X] Linux

Even the save method on `OrientDBDocumentCollectionManagerAsync` allows anything that extends Number on createdCallback, when you use Integer a ClassCastException happened.

`OrientDBDocumentCollectionManagerAsync#public <RET extends ORecord> RET save(final ORecord iRecord, String iClusterName, final OPERATION_MODE iMode,
      boolean iForceCreate, final ORecordCallback<? extends Number> iRecordCreatedCallback,
      ORecordCallback<Integer> iRecordUpdatedCallback)`

## Expected behavior and actual behavior
Change `OrientDBDocumentCollectionManagerAsync` the save method to allow just number:

```java
  public <RET extends ORecord> RET save(final ORecord iRecord, String iClusterName, final OPERATION_MODE iMode,
      boolean iForceCreate, final ORecordCallback<Number> iRecordCreatedCallback,
      ORecordCallback<Integer> iRecordUpdatedCallback) {`

```

## Steps to reproduce the problem

```java
      ODocument document = new ODocument("Name");
       Map<String, Object> map = new HashMap<>();
        map.put("name", "Poliana");
        map.put("city", "Salvador");
        entityValues.keySet().stream().forEach(k -> document.field(k, entityValues.get(k)));
        ORecordCallback<Integer> oridentDBCallBack = (a, b) -> callBack.accept(entity);
        tx.save(document, null, ASYNCHRONOUS, false, oridentDBCallBack, oridentDBCallBack);

```

_____
The log

```
SEVERE: Exception on async query
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at com.orientechnologies.orient.client.remote.OStorageRemote$4.call(OStorageRemote.java:522)
	at com.orientechnologies.orient.client.remote.OStorageRemote$4.call(OStorageRemote.java:519)
	at com.orientechnologies.orient.client.remote.OStorageRemote$1$1.run(OStorageRemote.java:174)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tglman** [comment]
hi @otaviojava,

I was checking this but the stack trace you posted don't match the code of 2.0.18, are you sure you are using that version?

Thank you for reporting.

Regards

**Comment by otaviojava** [comment]
Hello @tglman I'm using the orienddb version,  2.2.15, latest from dockerhub, 
On my client I'm using:

```xml
     <dependency>
            <groupId>com.orientechnologies</groupId>
            <artifactId>orientdb-graphdb</artifactId>
            <version>2.2.14</version>
        </dependency>
```

**Comment by tglman** [comment]
hi @otaviojava,

Good, now i understood the problem, you are using the api like this:
```
      ODocument document = new ODocument(entity.getName());
        Map<String, Object> entityValues = entity.toMap();
        entityValues.keySet().stream().forEach(k -> document.field(k, entityValues.get(k)));
        ORecordCallback<Integer> oridentDBCallBack = (a, b) -> callBack.accept(entity);
        tx.save(document, null, ASYNCHRONOUS, false, oridentDBCallBack, oridentDBCallBack);
```

but acutally the first callback expect a Long, the signature of the api is to wide and not force you to do that, so the correct working code is:
```
      ODocument document = new ODocument(entity.getName());
        Map<String, Object> entityValues = entity.toMap();
        entityValues.keySet().stream().forEach(k -> document.field(k, entityValues.get(k)));
        ORecordCallback<Integer> update = (a, b) -> callBack.accept(entity);
        ORecordCallback<Long> create = (a, b) -> callBack.accept(entity);
        tx.save(document, null, ASYNCHRONOUS, false, create, update);
```

I'm going to change the api to force that.

To explain in a better way the create callback receive a rid and a Long that is the generated clusterPosition, that is te second part of the rid, and the update riceive an rid and a Integer instead because is the integer is the new version of the record.

Hope this helps, going to give you more detail on the rid management on the other issue.

Bye

**Comment by tglman** [comment]
hi @otaviojava,

I cannot change that in 2.2.x ,because it would break all the existing code, so I'm going to keep it like this in 2.2.x and change it in 3.0, reading the other issue you were already aware of the workaround i proposed.

In any case what is the use case for this API for you ? I see that you work on the Diana Project and due to the fact i was deprecating this API in 3.0 in favor to a completely different approach to async operations, i would like to know better how you use it (you can point me the code ;) ) so I can provide a better design for 3.0.

In any case this async API is poorly documented and often used by user only on specific case after our suggestion, so we can clearly do better on this.

Regards

**Comment by otaviojava** [comment]
Sure.
Basically, I created a wrapper to orientdb implementation:

https://github.com/JNOSQL/diana-driver/blob/master/orientdb-driver/src/main/java/org/jnosql/diana/orientdb/document/OrientDBDocumentCollectionManagerAsync.java

What I'm doing now is:
After the orientdb saves my entity my next step is to append the RID and then call the callback:

https://github.com/JNOSQL/diana-driver/blob/master/orientdb-driver/src/main/java/org/jnosql/diana/orientdb/document/OrientDBDocumentCollectionManagerAsync.java#L73-L87

Once I just found this documentation, I'm using this way.

**Comment by tglman** [comment]
hi @otaviojava,

Yes for the version 2.2.x is the correct implementation, in 3.0 we will have different API, but they fit well your use case, it will need a bit of work from your side but it will provide higher flexibility. we will write some docs about it when we release it.

For this specific issue as you figured out the callback it cannot be Integer it can be Long or Number, but due the fact i cannot change this api in 2.2.x i'm going to mark this as question, and close it.

Regards
