### ISSUE TITLE
Async save returns invalid ORecordId

### ISSUE THREAD

**Issue by otaviojava** [orientechnologies/orientdb#7105]
## OrientDB Version, operating system, or hardware.
- v    2.2.15 

## Operating System
- [X] Linux

## Expected behavior and actual behavior

When I'm running an async save on callback it returns an invalid **rid**.

## Steps to reproduce the problem

```java

      ODocument document = new ODocument("Name");
       Map<String, Object> map = new HashMap<>();
        map.put("name", "Poliana");
        map.put("city", "Salvador");
        entityValues.keySet().stream().forEach(k -> document.field(k, entityValues.get(k)));
       ORecordCallback<Number> createCallBack = (a, b) -> {
            System.out.println(a.toString());//#-1:-1
        };
        ORecordCallback<Integer> updateCallback = (a, b) -> callBack.accept(entity);
        tx.save(document, null, ASYNCHRONOUS, false, createCallBack, updateCallback);

```

**Comment by tglman** [comment]
hi @otaviojava,

I did a quick look to the 2.0 code and seems that it should work, in any case the 2.0.x is not supported anymore, so please try 2.2.x I feel that similar issues have bean fixed in later versions, be aware that also the 2.1.x is going out of support at the end of January 2017.

Regards

**Comment by otaviojava** [comment]
Hello @tglman I'm using the orienddb version,  2.2.15, latest from dockerhub, 
On my client I'm using:

```xml
     <dependency>
            <groupId>com.orientechnologies</groupId>
            <artifactId>orientdb-graphdb</artifactId>
            <version>2.2.14</version>
        </dependency>
```

**Comment by tglman** [comment]
hi @otaviojava ,

about the RecordId on create callback, the original intention was that you receive the temporary rid as first parameter of the callback, and the server generated cluster position as second parameter of the callback, that's why you have the #-1:-1 id, in any case I am double checking this if is still valid today, this api is quite old in time.

Regards

**Comment by otaviojava** [comment]
@tglman could you send me the documentation to the newest one?
I didn't find on the site:
http://orientdb.com/docs/master/Tutorial-Document-and-graph-model.html

**Comment by tglman** [comment]
hi @otaviojava,

I checked and i figured out that there is no meaning anymore for invalid rid on that API, so i change it and i'm closing this issue.

Please let's follow up on the API/docs on the other issue.

Regards
