### ISSUE TITLE
What's the correct permission for the OrientDB `config` directory

### ISSUE THREAD

**Issue by finid** [orientechnologies/orientdb#7154]
## Expected behavior  
In [this doc](http://orientdb.com/docs/last/Server-Security.html), it says that:

>  It is strongly recommended that you allow read/write access to the entire config directory only to the user that starts the OrientDB server.

Now the default permission for that directory is 755. Based on the recommendation, would it be proper to set the permission to 700. If so, why is it necessary to have execute permissions for that directory?

**Comment by 1283386** [comment]
Btw, when I configure some software I would like to be sure it is configured the way I did it and does not rewrite its config itself. With 2.0.15 it was enough to let orientdb user read permissions only, but upgrading to 2.2.x I found out that standalone version expects to see "guest" user in orientdb-server-config.xml and completely rewrites it, swapping "name" and "value" in lines, which makes it very hard to diff. Even worse, distributed version just won't start on distributed ports even if I let it change config and then set it to read-only, complaining about "[Class]com.orientechnologies.orient.core.exception.OConfigurationException: Error on deleting 'replicator' user"

Is there any real need to keep configuration writable to the user which runs the process?

**Comment by tglman** [comment]
hi,

@finid yes the permission of the config folder can be set to 600, i need to double check with the release team to understand why now is 755 by default.

@1283386 yes as today we need to rewrite the configuration because we don't have any other place to store some settings, also some settings are created at runtime, for now we cannot do anything for avoid it, we will take this in consideration for future implementations and we will see if we can avoid somehow.

Regards

**Comment by tglman** [comment]
hi @finid,

Did I answer your question? can i close this ?

Regars

**Comment by finid** [comment]
If you've double-checked with your guys and they agree that the permission can be 600, you may close it. But why is the default 755?

**Comment by robfrank** [comment]
single files are now 644 in config folder. Trying to port them to 600 let the folder in an inconsistent state ( unaccessible ).
