### ISSUE TITLE
Select expand of Vertex order by Edge property

### ISSUE THREAD

**Issue by DienNM** [orientechnologies/orientdb#7197]
### OS: Ubuntu 14.06  

Hi team,
I am quite a newbie to OrientDB, just have used 1 week so far. I am using java api to manipulate OrientDB Graph
## Expected behavior  
I created the relationships of Products and the weight of those relationships. I would like to query top X of the highesh weights on Edges. 

It seems has not supported by OrientDB 2.2? Could you please give me some advice on this?

**Comment by luigidellaquila** [comment]
Hi @DienNM 

You can easily do it with an inner SELECT statement

```sql
SELECT expand(outV()) FROM (
   SELECT FROM EdgeClass ORDER BY theProperty
)
```

(not sure if outV() is what you need, maybe you need inV(), depending on if you need incoming or outgoing edges)

I hope it helps

Thanks

Luigi

**Comment by DienNM** [comment]
Thank you very much!
By the way, Could you please tell me how to create the undirect edges? I did search but I cannot find any answer

**Comment by luigidellaquila** [comment]
Hi @DienNM 

There is no way to create undirected edges. In the Property Graph Model (database) edges have a direction, AFAIK it's true for all the graph databases in the market.

This is not a limitation, because you can traverse edges regardless their direction, using `both()` operator

Thanks

Luigi

**Comment by DienNM** [comment]
I got it. Thank you for your support.
