### ISSUE TITLE
'DELETE VERTEX' does not decrease size of out-collection of linked Vertex

### ISSUE THREAD

**Issue by thePunIssuer** [orientechnologies/orientdb#7275]
## Expected behavior  
Deleting linked Vertices should decrease size of linked Vertex's out-collection.
`select out('hasValue').size() from #70:0` returns 2641.
`DELETE VERTEX FROM (SELECT expand(out('hasValue')) FROM #70:0 ORDER BY latestChange ASC LIMIT 141`
`select out('hasValue').size() from #70:0` returns 2500.

## Actual behavior  
Out-collection stays same size.
`select out('hasValue').size() from #70:0` returns 2641.
`DELETE VERTEX FROM (SELECT expand(out('hasValue')) FROM #70:0 ORDER BY latestChange ASC LIMIT 141`
`select out('hasValue').size() from #70:0` still returns 2641.

`select count(*) from (select expand(out('hasValue')) from #70:0)` returns 2500, so Value Vertices did get deleted.

## Steps to reproduce  
Vertices were created and linked via Java API: 
```
	Vertex capabilityVertex = graph.addVertex(SConstants.V_CLASS_PREFIX + capabilityClassName,
		SConstants.P_CAP_ID, capability.getCapabilityId(),
		SConstants.P_CAP_BASIC_COMMANDS, capability.isBasicCommands());
```
...
```
	Vertex newValueVertex = graph.addVertex(SConstants.V_CLASS_PREFIX + valueClassName,
		SConstants.P_CAP_LATEST_CHANGE, timestamp.toString(),
		SConstants.P_CAP_CURRENT_VALUE, newCurrentValue);
	capabilityVertex.addEdge(SConstants.Edge.CAPABILITY_VALUE.getName(), newValueVertex);
```
[data.zip](https://github.com/orientechnologies/orientdb/files/872617/data.zip)

**Comment by luigidellaquila** [comment]
Hi @thePunIssuer 

I checked your dataset, it seems to be broken already.
I tried to execute your script on your db and I could reproduce the problem on existing data.
I also tried to insert data in a newly created class and then drop vertices in the same way, but in this case I had no problem, everything works as expected.

After some debugging, I'm pretty sure that the problem is in the RidBag that contains the edges, I'm forwarding the issue to the storage team for a check

Thanks

Luigi

**Comment by taburet** [comment]
@luigidellaquila The rid bag data is not broken, at least on the binary level, there are just some rids pointing to the deleted cluster records. While iterating over the rid bag vertex iterator just silently skips such unresolved records, see `OrientVertexIterator#getGraphElementRecord`, that's why the rid bag size differs from the resulting vertex collection size.

**Comment by luigidellaquila** [comment]
uhm... ok, I'll check at the higher level

Thanks

Luigi
