### ISSUE TITLE
Is it possible to support unsigned integer?

### ISSUE THREAD

**Issue by HuangKBAaron** [orientechnologies/orientdb#7306]
## Expected behavior  
There are lots of cases that both large integers and unsigned integers for different purposes and distinguish is vital.

## Actual behavior  
doesn't support with  2.2.17  

## Steps to reproduce  
n/a

**Comment by luigidellaquila** [comment]
Hi @HuangKBAaron 

Right now OrientDB supports five types of numbers
- Integer: 32bit signed
- Long: 64bit signed
- Float: 32bit
- Double: 64bit
- Decimal: absolute precision (same as Java BigDecimal)

For now, you can use Long instead of unsigned int. 

Supporting unsigned integers is not in the roadmap, but we can consider it of course.

Thanks

Luigi

**Comment by HuangKBAaron** [comment]
most of the ids are using unsigned long (64bit), it would be common to support it. because most of the CPUs are 64bit, so unsigned long value can be load/save with one operation. If not supported, the work around would be 'Decimal', which take more than one operation. Because it is a primary job for sorting, comparing, and etc., it is bad for high performance situation.

**Comment by tglman** [comment]
hi @HuangKBAaron 

I see your point, orient does not have unsigned integer and right now and we cannot support it in short term, if your id is a sequential you may try to re-map it to a signed long that support anyway from 0 to 9,223,372,036,854,775,807 and should anyway contain your load.

Regards

**Comment by lvca** [comment]
Such enhancement is too expensive in comparison to the benefits. Sorry, I'm closing it unless a lot of users would +1 this.
