### ISSUE TITLE
Create vertex java api followed by sql create edge - lazy execution

### ISSUE THREAD

**Issue by karolmie1** [orientechnologies/orientdb#7319]
### OS: linux

1. create vertex from java api: graph.addVertex("class:${Task.CLASS}", params))
2. create edge from sql:  "CREATE EDGE hasTask FROM (SELECT FROM Project WHERE id=:projectId) TO (select * from Task where seq=:seq)"

Now I get the error: source vertex not found
If I put graph.commit() before creating the edge the source vertex is found, and edge is created succesfully.

I like Java Api when creating vertices, but its not particulary usefull for any more complex queries, so I tend to mix them up.

Does it look like bug or something you would be interested in investigating? If so, I can provide a way to reproduce. Otherwise just please say so, and I'll close.

Is there any other command that I can "flush" the database with? I would be interested in something like graph.commit(), but without commiting.

**Comment by luigidellaquila** [comment]
Hi @karolmie1 

This is an expected behavior in v 2.2.x, in this version the transaction is fully executed on the client and propagated to the server only at commit time; on the other hand, the SQL statements are executed on the server, so they don't know anything about the transaction until it's committed.
See http://orientdb.com/docs/2.2.x/Transactions.html

The only alternative you have now is executing a server-side script as follows:

```java
String script = 
   "BEGIN;"+
   "CREATE VERTEX TheClass SET foo = 'bar';"+
   "CREATE EDGE hasTask FROM (SELECT FROM Project WHERE id=:projectId) TO (select * from Task where seq=:seq);"
   "COMMIT;"

graph.command(new OCommandScript(script)).execute(params);
```

This is going to change in v. 3.0, we added a mechanism to propagate tx to the server when SQL statements happen, so the behavior in 3.0 will be exactly what you expected

Thanks

Luigi

**Comment by karolmie1** [comment]
Hmm, I've just noticed, that this happens even if I do commands one by one. Thats upsetting. Only this one blob way works.
