### ISSUE TITLE
Memory Leak in Profiler: Disabling the profiler is still collecting stats, and holding the instance of deleted DB

### ISSUE THREAD

**Issue by prabodhshrivastava** [orientechnologies/orientdb#7320]
## Expected behavior  
If Profiler is disabled then it should not collect any type of stats. And it should not hold the reference of deleted DB

## Actual behavior  
If OProfiler is disabled then its should not collect stats. In our application we are creating lots of temporary memory based DB(memory) and then when trying to delete it, Db is getting deleted but profiler is holding the reference of the DB. Thus profiler is preventing it in GC cycles. Application is going out of memory.

## Steps to reproduce  
Create many OMemory DBs on fly and then call delete on that datastore one after other.
After some time take the heap dump of Java process, check if HashMap inside OProfilerStub is holding the reference of that DB

Please let me know if you have questions

**Comment by tglman** [comment]
Hi @prabodhshrivastava,

I removed the reference to the storage from the profiler, so now will be garbage collected, some counter are kept inside the storage for internal purpose and after exposed by the profiler, so that's why it seems that if you torn off the profiler the count continue to go on.

If you don't mind I close this.

Regards
