### ISSUE TITLE
Database list is being displayed on Studio without authentication

### ISSUE THREAD

**Issue by gilbertomueller** [orientechnologies/orientdb#7325]
## Expected behavior  
Dropdown list of currently available DBs is NOT displayed, or at least not without authentication

## Actual behavior  
Dropdown list of currently available DBs is displayed without authentication 

## Steps to reproduce  
Just open Studio's landing page

FYI @luigidellaquila 

![7325](https://cloud.githubusercontent.com/assets/15326294/24916221/3894902c-1ee2-11e7-8b57-c5fdc44c2a23.PNG)

**Comment by lvca** [comment]
Look in `config/orientdb-server-config.xml` file and you will find the auto-generated guest user with the permission of `server.listDatabases`:

```
        <user resources="connect,server.listDatabases,server.dblist" password="{PBKDF2WithHmacSHA256}DC2AF142897E08F859E10FEBEF104703AC07DF24619C1982:57D9F805AA03C8B2D916A84BC252D832FC10732D314B5D87:1" name="guest"/>
```

If you don't want this, remove the resource in the permissions or remove the guest user completely.

**Comment by luigidellaquila** [comment]
@lvca just tested it and it doesn't seem to work... 
Anyway, in Studio the db is a dropdown menu, how is it supposed to work if it's not populated? You cannot write into it...

Thanks

Luigi

**Comment by lvca** [comment]
If it's disabled studio won't work unless you bypass the login page going directly to the studio page? I didn't try it recently.

**Comment by santo-it** [comment]
Hi,

To solve this, what do you think to let Studio allow to write the database name in case it cannot list the current databases?

This would mean that instead of a dropdown menu (to select the database) in this case a "text" field is shown, so that users may write the name of the database. Ideally we can have an editable dropdown menu (e.g. you can pick one db, but also are allowed to write your own db name).

This would allow maximum flexibility and handle the (important) use case of those Organizations that have more strict security rules.

@maggiolo00 ?

Thanks,
