### ISSUE TITLE
Feature request: Support for multiple configuration files

### ISSUE THREAD

**Issue by zcatbear** [orientechnologies/orientdb#7353]
New Feature request:

`orientdb-server-config.xml` is the only supported configuration file. I would like to ultimately be able to split out my server, properties, and user configuration files to separate files and handle them independently. 

Ultimately I would like to be able to add a `conf.d` directory, which could be referenced with `include conf.d/*`,  like many other applications have so I can include any of the configurations that may be necessary.

**Comment by robfrank** [comment]
At the moment we have more than one file, because distributed configuration is on a separated json file. We planned to consolidate almost all conf in a single file, avoiding multiple files/formats. Moreover, it would be quite hard to modify the code to manage multiple files. So, thank you for your request, it will not be implemented. 
Obviously, it's open source, feel free to develop it and submit a PR .
