### ISSUE TITLE
transaction with batch of JSON/SQL commands, returns not array of values, only single value

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7381]
## Expected behavior  
I send batches of JSON instructions to UPDATE documents into my class.
For **each** such document, after its UPDATE, I want to retrieve the new value of their SESSION_STOP property:
```
{ "transaction": true, "operations": [ {"type": "script", "language": "sql", "script": "begin; UPDATE...  RETURN AFTER $current.SESSION_STOP; } ;commit; " }, {"type": "script", "language": "sql", "script": "begin; UPDATE...  RETURN AFTER $current.SESSION_STOP; } ;commit; " }  ] }
```
The example is simplified to send 2 operations in a single transaction.

I expect this transaction to return an array with the 2 returned SESSION_STOP values, but this is not happening:
only an array with a single element is returned:
```
{"result":[{"@type":"d","@version":0,"value":"2017-04-20 22:10:34.000","@fieldTypes":"value=t"}]}
```
-> why ?
-> how to get the returns for each operation in the batch?

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

the script returns the result of last operation, this is why you are having this result.
The solution to your problem is to manually aggregate the results, eg.

LET $a = UPDATE...  RETURN AFTER;
LET $b = UPDATE...  RETURN AFTER;
RETURN [$a, $b];

Just an example, for sure you will have to change something in the syntax, but I hope you got what I mean

Thanks

Luigi

**Comment by rdelangh** [comment]
hi Luigi,

my different operations in the batch are each individual scripts, one per record, from "begin" till "end";
so I don't think that each such one can return a value, which is then collected with a "LET" , am I correct?
