### ISSUE TITLE
select issue

### ISSUE THREAD

**Issue by KishoDai** [orientechnologies/orientdb#7389]
## Expected behavior  
Get the query result quickly!  

## Actual behavior  
Get the query result so slowly.

## Steps to reproduce  
1. The below SQL is OK.
    select from V let $a = (select from V limit 10) where  $a.size() <= 10 limit 10
    select from V let $a = (select from V limit 10) where  $a.size() >= 0 limit 10
2. The below SQL is not OK. It's very slow so that can't get the query result.
     select from V let $a = (select from V limit 10) where  $a.size() <= 9 limit 10
     select from V let $a = (select from V limit 10) where  $a.size() > 10 limit 10

**Comment by luigidellaquila** [comment]
Hi @KishoDai 

Two problems here:

1.  $a.size() is always = 10, so in the first two queries the WHERE condition it always true. Both queries will return the first 10 elements of V. In the third and fourth query, the WHERE condition is always false, so the executor will try to scan V until the end and calculate the WHERE condition for each record. This full scan will take a lot of time if you have a lot of records
2. in V 2.2 the executor is not smart enough to understand that the subquery can does not depend on the parent query, so it can be executed only once and the result can be used to calculate the WHERE condition on each record on the parent query. This will lead to the execution of the subquery once per record in V. Of course this will slow down the query even more. Good news is that this problem is already fixed in the new 3.0M1, so the GA won't suffer from this problem.

Out of curiosity, which is your real use case? I guess this one is just an example to demonstrate the problem...

Thanks

Luigi

**Comment by KishoDai** [comment]
Hi  Luigi,
     Thank you for your detailed explaination.
     Your guess is correct ,I'm just test it.

Thank you 
Kisho
