### ISSUE TITLE
Selective Property key is reserved: id error

### ISSUE THREAD

**Issue by karolmie1** [orientechnologies/orientdb#7432]
### OrientDB Version: 2.2.20

I've created class Project with property id: 

```
CREATE CLASS Project extends Assignable
CREATE PROPERTY Project.id STRING (MANDATORY TRUE, NOTNULL, MAX 10)

CREATE VERTEX Project set id = 'KSG2016'
```

However, when trying to do that from java api: 

```
graph.addVertex("class:${Project.CLASS}", project.getParams())
```

I receive error: `java.lang.IllegalArgumentException: Property key is reserved for all elements: id`

This is ok, I found related issue, and I understand why this exception has to be thrown, and how to disable it: https://github.com/orientechnologies/orientdb/issues/5688

Supposedly (as in the mentioned issue) CREATE EDGE throws this error too.

This is inconsistent. Either everything by default should throw error (fail fast), or nothing.

**Comment by tglman** [comment]
hi @karolmie1,

Yes this is a inconsistency due to the fact that the TinkerPop has some constraint that orientdb itself don't have, so the "id" field is an reserved field in TinkerPop(that is third party standard), and we have no reason to have the "id" field reserved in OrientDB core itself, anyway since 3.0 we are deprecating TinkerPop 2.x supporting TinkerPop 3.0 and providing a orient specific API for graph operation completely independent to TinkerPop so we can have a more coherent environment.

Hope this answer to your problem.

Regards
