### ISSUE TITLE
why lost node but none of log error or exception

### ISSUE THREAD

**Issue by j782070772** [orientechnologies/orientdb#7482]
## Expected behavior  
<add here>  
I have 3 nodes on 3 mechines,  and i run 3 etl processes on 3 mechines.
it should load data successfully

## Actual behavior  
but，after 4 hours, it lost node1 process first and node2 process losted after 13 hours,
finally, node3 also lost.  
i look up logs, there is none of exception why it lost process？

## Steps to reproduce  
<add here>

**Comment by lvca** [comment]
Can we have the logs of 3 servers? What do you mean with "lost node"? It was crashed, network problems?

**Comment by j782070772** [comment]
“lost node” means "OServerMain" process exit  when i loading csv data use oetl.sh . but there is no error or exception.  my english is bad, sorry.

 here are logs:
thank you 

[node1-orient-server.txt](https://github.com/orientechnologies/orientdb/files/1070088/node1-orient-server.txt)
[node2-orient-server.txt](https://github.com/orientechnologies/orientdb/files/1070089/node2-orient-server.txt)
[node3-orient-server.txt](https://github.com/orientechnologies/orientdb/files/1070090/node3-orient-server.txt)

**Comment by lvca** [comment]
usually when a process dies without any log is the Linux kernel that take initiative on killing the process because it eats too much RAM. Can you check that? How much RAM do you have before starting OrientDB? How much heap and diskcache did you reserve for the OrientDB process? Are the 3 servers running on the same server?
