### ISSUE TITLE
asList returns undefined when no records found rather than an empty list

### ISSUE THREAD

**Issue by igasparetto** [orientechnologies/orientdb#7602]
Hi guys,

When we use query filters combined with asList() and the result of the query is nothing, we get "undefined" instead of an empty list. I was expecting an empty list rather than undefined. Is that expected behaviour or there is something to be improved here?

`[myAttribute=false]
[out=${contact.rid}]
   .@class.asList()`

**Comment by luigidellaquila** [comment]
Hi @igasparetto 

I'd say an asList() should always return a list...
Let me check it, I'll let you know shortly

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @igasparetto 

I had a look at the code, the `asList()` function works fine, this behavior comes from the implementation of the query executor.

There a two null-checks that short circuit operation chains; I could remove them and you would have the behavior you expect, but frankly speaking I don't think that doing this in a hotfix release is a good idea, as it could lead to NullPonterException in some corner cases.

The work-around to this is following:

```
SELECT coalesce(yourNullField.asList(), []) FROM V
```
the `coalesce()` function returns the first value if it's not null, the second one otherwise

Thanks

Luigi

**Comment by igasparetto** [comment]
Luigi,

We have coded here in a way we map undefined back to an empty. 
Thanks for looking into it.

Ivan

**Comment by luigidellaquila** [comment]
OK, closing then, please reopen if you need further info

Thanks

Luigi
