### ISSUE TITLE
Under some conditions 50% transactions are not being commited

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#7646]
### OS: ubuntu

2 days I was catching very tricky bug. In Orienteer it looked like the following: on some document in half cases data was not being saved at all. Looks like a magic, right?:)

After investigation we found the following:
During saving of document there are 2 records added through OTransactionOptimistic.addRecord(). One for old document and one for updated. And order is unpredictable, so last wins. 
Digging deeper we found quite interesting stuff: ODirtyManager.merge() and this method is merging those old record and new record.

And here 2 facts leads to mentioned results:
1) We are using ODocument as container for fields with type EMBEDDED. And this document is serialized between requests till being saved within parent document 
2) ODocument.dirtyManager is not transient - so it's serialized between calls.

After adding `ORecordInternal.setDirtyManager(doc, null)` before serialization issue is gone.

Proposal: **please make `ODocument.dirtyManager` transient. I  don't see any good reason to keep it as is.**

**Comment by tglman** [comment]
hi @PhantomYdn,

To better understand, do you have two instances for the same record (that have same rid )?

The dirty manager is thought to outlive the save method, it actually get created when the data is loaded and is needed for keep track of the changes of a loaded graph of document and save them all together when one is saved, this is quite important for graph structures or for any looped graph of documents, because orient can manage correctly the generation of id of looped structures, that would be quite complex to solve if this case was left in the hand of the user.


If I understood well your case probably the solution is not to have two instances of the same record saved, this can be achieved or starting a clear session(new instance of `ODatabaseDocument`) or loading the record from the database and merge it with the one that come from outside.


Regards

**Comment by PhantomYdn** [comment]
@tglman, Our software's logic doesn't assume to have several instances for the same record. But it's happening due to undirect saving old version in dirtymanager and resurection on new request.

So sequence which leads to the problem is the following:

1) User is on a page for editing a document.
2) The document has EMBEDDED property with defined linkedClass.
3) It's web application - so user can work with the same document through several interactions/requests
4) During every request document instantiated from DB only once. Fresh DB from pool and new transaction.
5) But for p.2 there is dummy ODocument which created at the begining and than serialized/deserialized every request till user click "Save" and commit by that all changes to DB
6) It's happend that DirtyManager of that embedded ODocument contains parent document.
7) Due to p.6 and fact that ODocument.dirtyManager is not transient: after every desirialization there is new copy of our main document being created. 
8) And there is merge of dirtyManagers: which adds 2 instances of the same record to transaction and at the end last instance in dirtyManager wins during commit. 

So: there is not intent to create second record. But it's being created due to undirect/strange behavior or OrientDB with persisting DirtyManager.

And as I said previously: if I explicitly call `ORecordInternal.setDirtyManager(doc, null)` - everything become fine.

**Comment by PhantomYdn** [comment]
Dear OrientDB team,
Do you have any news about this issue?

**Comment by tglman** [comment]
Hi @PhantomYdn,

This has been probably fixed i while ago, i would suggest to retry the case.

bye
