### ISSUE TITLE
teleporter with conf error

### ISSUE THREAD

**Issue by zygift** [orientechnologies/orientdb#7821]
## Expected behavior  
Import relational database into OrientDB with the Teleporter using conf parameter.

## Actual behavior  
I used Teleporter through the script, as follows:
sh oteleporter.sh -jdriver Oracle -jurl jdbc:oracle:thin:@192.168.xxx.xxx:1521:orcl -juser root -jpasswd root -ourl plocal:/opt/orientdb-enterprise-2.2.27/databases/testdb -include ACTOR,FILM,ACTOR_FILM -s naive -nr original -v 2 -conf /opt/data/teleporter-config/migration-config.json

migration-config.json file:
{
  "edges": [{
  "Performs": {
    "mapping": {
      "fromTable": "ACTOR",
      "fromColumns": ["ID"],
      "toTable": "FILM",
      "toColumns": ["ID"],
      "joinTable": {
  			"tableName": "ACTOR_FILM",
				"fromColumns": ["ACTOR_ID"],
				"toColumns": ["FILM_ID"]
			},
			"direction": "direct"
		},
		"properties": {
        "PAYMENT": {
        "type": "STRING",
        "mandatory": false,
        "readOnly": false,
        "notNull": false
		}
	}
	}
	}]
}

## Steps to reproduce  
Exception in thread "main" java.lang.NullPointerException
	at com.orientechnologies.teleporter.context.OTeleporterContext.printExceptionMessage(OTeleporterContext.java:152)
	at com.orientechnologies.teleporter.util.OMigrationConfigManager.loadMigrationConfigFromFile(OMigrationConfigManager.java:64)
	at com.orientechnologies.teleporter.main.OTeleporter.execute(OTeleporter.java:250)
	at com.orientechnologies.teleporter.main.OTeleporter.main(OTeleporter.java:219)

Is the import configuration file any problem?

**Comment by johtor2** [comment]
#7929 - Same issue with configuration file.

**Comment by Kyserbyte** [comment]
Having the same problems, i have taken a look on the code of _teleporter_ tool and I found a couple of issues.
First of all you need to have a config JSON file with this format, otherwise the script will crash:
```
{
    "vertices": [],
     "edges": [{
        "EDGE_NAME": {
            "mapping": [{
                "fromTable": "FROMTABLE",
                "fromColumns": ["ID"],
                "toTable": "TOTABLE",
                "toColumns": ["ID"],
                "direction": "EDGE_DIRECTION"
            }],
            "properties": {
            }
        }
    }]
}
```
You need to have an entry for "vertices" and the "mapping" property must to be an array of object and not an object.

After that, there is a bug on the config file loader method (_OMigrationConfigManager.loadMigrationConfigFromFile_) that attempt to use a singleton class (_OTeleporterContext.getInstance_) that is not initialized when is used. I will submit a pull request with a fix for that.

**N.B:** _This is valid for the 3.0.1 version of OrientDB and Teleporter. I did not check other versions._
