### ISSUE TITLE
Pinned Pages Usage

### ISSUE THREAD

**Issue by rbaarathinms** [orientechnologies/orientdb#7858]
Hi,
   Our orient version is 2.2.20,
   Regarding storage.diskCache.pinnedPages I need to know whether increasing the parameter from default value can cause any improvements in performance ??? Our storage size is around 50 GB.
We have got input from orient database support team that the default value is 20 and to the maximum it is 50.
(the number represents % of pinned pages, ie. pages that tend to stay in memory, on the total of disk cache pages) Is this right..?? Then if we set the value to 50 what will happen..???

**Comment by laa** [comment]
Hi, the reason for this warning is following. If you reach percent of pinned pages limit, the next addition of data will slow down system performance. There are two recommended ways to handle this situation:
1. Try to use tree indexes instead of hash indexes. It is very likely that you will not have any performance degradation.
2. Increase amount of RAM on the server or RAM provided to OrientDB server.

I do suggest you try the first option first.

**Comment by rbaarathinms** [comment]
Can you explain when will be the pinned pages limit reached ? Like during which orient operation while writing or while just starting orient server ? Because we just deployed new version of orient 2.2.20 , there was no changes in code, suddenly we are getting this warning

**Comment by laa** [comment]
@rbaarathinms this limit is reached because the in-memory index of hash index becomes too big. Typically that does not happen, and that is why you and many other users did/do not notice it. Size of in-memory index depends not on size/amount of data but on low of distribution of this data. That is just bad luck that distribution of data changed in such way that you got this exception.

**Comment by lvca** [comment]
@laa how to prevent this problem?

**Comment by laa** [comment]
@lvca First of all that is a performance warning. So if performance is still OK for you do not need to do anything. Otherwise, 3 variants are possible, here users should experiment:
1.  Increase amount of RAM
2.  Increase percent of pinned pages
3. Recommended one, use SB-Tree indexes instead, they are more "durable" in the sense of data distribution as result your memory consumption will be decreased.

**Comment by laa** [comment]
Hi @rbaarathinms does the migration to SB-Tree indexes help you to solve the issue ?

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.
