### ISSUE TITLE
System slow when the orient storage is building

### ISSUE THREAD

**Issue by rbaarathinms** [orientechnologies/orientdb#7860]
Hi,
   Our orient version - 2.2.20
   Java version - jdk1.8.0_121
   We are measuring the time taken to add some objects in orient storage. Initially the persistence rate is high and after some time the persistence rate slows down gradually. If we restart the server, again the persistence rate becomes high and then it slowly decays. What might be the reason for this..??

**Comment by laa** [comment]
It is really hard to say from the general description, but probably you have a memory leak which was fixed in latest versions. So first steps which I suggest you:

1. Do upgrade to the latest version which is 2.2.29 at this moment.
2. Lest resolve the issue https://github.com/orientechnologies/orientdb/issues/7858 first. Maybe after that, this issue also will be resolved.

**Comment by laa** [comment]
Closed because of no reply on related issue.
