### ISSUE TITLE
the edge count is error

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7946]
### OS: CentOS

The count of subclass of E is different from the count of subclass, as below
![screenshot from 2017-12-17 21-47-07](https://user-images.githubusercontent.com/31640567/34080124-22789354-e374-11e7-9d52-44bb84fcde5e.png)

**Comment by luigidellaquila** [comment]
Hi @weickdev 

This reminds me a problem we already fixed in v 2.2, where some clusters had an unaligned value of total count (the data were still correct though).

Anyway, it could also just be a problem with the data, could you please run this query and post the results:

```
SELECT FROM E WHERE @Class <> "invest"
```

(it will take some time to execute...)

Thanks

Luigi

**Comment by weickdev** [comment]
@luigidellaquila the count is the same now! I think there must be an inserting operation when I refresh the page, the E counting is done before invest counting, so the E counting is less than invest. Can it causes this issue?

**Comment by luigidellaquila** [comment]
Hi @weickdev 

Yes, it's definitely possible. Studio interface does multiple queries to fetch cluster information, so probably you just got that info in the middle of an update.

As I wrote before, we had an issue so that sometimes cluster count metadata did not match actual cluster size, but it was fixed a few months ago, and anyway if that was the case you would still see the difference (it didn't fix by its own)

I think we can close this issue, please feel free to re-open if you still see this problem

Thanks

Luigi

**Comment by weickdev** [comment]
OK, Thanks for your reply. @luigidellaquila
