### ISSUE TITLE
with bigger traverse depth comes smaller resultset

### ISSUE THREAD

**Issue by blueAnger** [orientechnologies/orientdb#7958]
### OS: <CentOS 7> 

when executing traverse, sometimes with bigger 'maxdepth', orientdb returns fewer result. That's kinda confusing. SQL command like:

```
traverse * from (select from Company where name = 'example') maxdepth 11
```

It returns 15340 records. However, if I change maxdepth to 12, that is:

```
traverse * from (select from Company where name = 'example') maxdepth 12
```

it returns 6043 records.
## Expected behavior 
with bigger maxdepth comes bigger result

## Actual behavior  
sometimes, the result size can be smaller

**Comment by luigidellaquila** [comment]
Hi @blueAnger 

Which API are you using to do the query?

In general, the TRAVERSE never re-traverses the same vertices, so it can happen that you traverse a node at depth `N` and then you re-traverse it at depth`M < N` from another path. In this case the depth of the nodes could not be updated and you will lose some nodes after that (it's still considered at depth N). This happens because by default the traversal strategy is `depth first`, but you can force it to `breadth first` and solve the problem:

```
traverse * from (select from Company where name = 'example') maxdepth 12 STRATEGY BREADTH_FIRST
```

I hope it helps

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Ah, by the way, typically `TRAVERSE *` does not make much sense in a graph scenario.
What you typically want to do is `TRAVERSE out()` (outgoing edges), `TRAVERSE in()` (incoming edges) or `TRAVERSE both()` (all the edges)

Thanks

Luigi

**Comment by weickdev** [comment]
> so it can happen that you traverse a node at depth N and then you re-traverse it at depthM < N from another path. In this case the depth of the nodes could not be updated and you will lose some nodes after that

Is this a bug or do you design this?  As I know `depth first` can reach all nodes too.

**Comment by luigidellaquila** [comment]
let's say that it's a legacy behavior

**Comment by blueAnger** [comment]
Hi @luigidellaquila 
I don't quite understand your original explanation. Is there any chance you can express more clearly? Thanks a lot.

**Comment by weickdev** [comment]
@luigidellaquila 
> let's say that it's a legacy behavior

Can you take an example scenario using this kind of  `depth first`?

**Comment by luigidellaquila** [comment]
Hi @blueAnger 

Here is an example. Suppose you have a graph of four vertices as follows:

```
A -e1-> B -e2-> C -e3-> D
A -e4-> C
```

The C vertex is at depth 2 from A through edges `e1` and `e2`, but it's at depth 1 through edge `e4`.

The edges are not ordered so the engine can traverse `e1`, `e2` first, or it can traverse `e4` first.

Now consider this:

```
A -e1-> B -e2-> C -e3-> [D1...D100] 
A -e4-> X1 -e5-> X2 -e6-> X3 -e7-> C 
```
also suppose that OrientDB starts traversing from the X... path

*if you do the query with MAXDEPTH = 3* OrientDB loads the vertices as follows:
- A: depth = 0
- X1: depth = 1
- X2: depth = 2
- X3: depth = 3 //and stop traversing
- B: depth = 1
- C: depth = 2
- D1 to D100: depth = 3

So in total you have 106 vertices loaded

*if you do the query with MAXDEPTH = 4* OrientDB loads the vertices as follows:
- A: depth = 0
- X1: depth = 1
- X2: depth = 2
- X3: depth = 3 
- C: depth = 4 //and stop traversing
- B: depth = 1
- C: already traversed, discard and stop traversing

So in total you have 6 vertices

With BREADH_FIRST this problem doesn't happen, because the depth is always the minimum depth from the root node

I hope it helps

Thanks

Luigi

**Comment by weickdev** [comment]
@luigidellaquila Above example is quite clear. There is another question, how do you process the cycle path with 'breadth first'? For example, there is path: `A -> B -> C -> B -> A`, and there is a path A->D. If the `MAXDEPTH = 5`, will I get a path `A->B->C->B->A->D`?

**Comment by luigidellaquila** [comment]
Hi @weickdev 

For this path:

```
A -> B -> C -> B -> A
A -> D
```

you will get

```
A: depth 0
B: depth 1
D: depth 1
C: depth 2
```

Thanks

Luigi

**Comment by blueAnger** [comment]
@luigidellaquila The example is very helpful. Thank you.
