### ISSUE TITLE
[BUG]fetchplan not work fine

### ISSUE THREAD

**Issue by lightjiao** [orientechnologies/orientdb#8030]
## Expected behavior  
return result *NOT* include schema `age`

## Actual behavior  
return result  include schema `age`

## Steps to reproduce  
```
create vertex v content {name: "pete", "age": 22, "age2": 18}
select * from v fetchplan age2:1 age:-2
```

I know 3.0.0 don't support fetchplan, but now, fetchplan is a important feature for me

any way or any plan to fix this bug?

I use sql below to solve my problem, but this is still a bug.
```
select age2 from v fetchplan age:-2
```

**Comment by metametametameta** [comment]
As per https://orientdb.com/docs/3.0.x/release/3.0/Upgrading-to-OrientDB-3.0.html#fetch-plan, the fetch plan feature is deprecated - but shouldn't it continue to work in 3.x as in 2.x until it the feature is actually taken out in the future (i.e., assuming it can be actually taken out in favor of an equivalent nested projections constructs.)

I'm concerned that nested projections and fetch plan may not be equivalent. I posted this question on SO earlier (https://stackoverflow.com/questions/48467938/how-to-migrate-from-fetch-plan-to-nested-projections) and is reproduced below)

### OrientDB Version: 3.0.0 RC1  
### Java Version: Java 8
### OS: Windows 8.1

I'm attempting to convert a basic fetch plan use case to use nested projections.

The query below with a fetch plan of *:2 works fine. Note that I'm able to get an OElement as expected.

```java
String queryWithFetchPlan = "select from MyClazz fetchplan *:2";
try (OResultSet rs = graph.query(queryWithFetchPlan);) {
  while (rs.hasNext()) {
    OResult r = rs.next();
    OElement v = r.getElement().get();
  }
}
```

After looking at the user guide for nested projections at https://orientdb.com/docs/3.0.x/sql/SQL-Projections.html, my first attempt at converting the above query to nested projections looks like this. The query itself appears to work and returns an OResult. However, it is not an OElement. Is there a different way to write this query and still get an OElement (instead of just OResult?). If not, can fetch plan really be replaced with nested projections in all cases?

```java
String queryWithProjections = "select *:{*:{*}} from MyClazz";
try (OResultSet rs = graph.query(queryWithProjections);) {
  while (rs.hasNext()) {
    OResult r = rs.next();
    //Not quite an OElement because of the projection syntax
    //OElement v = r.getElement().get();
  }
}
```

If testing on 3.0 demodb, you can replace MyClazz with say Customers.

**Comment by tglman** [comment]
hi @lightjiao,

You can translate this: `select * from v fetchplan age:-2` to this this  `select *:{!age} from v `.

@metametametameta yes you cannot get an OElement from a projection query, this is done on purpose because OElement are data that can be changed and saved, OResult may not be, and for sure is not if an OResult is a projection.

Regards

**Comment by metametametameta** [comment]
@tglman I understand that we cannot get an OElement from a projection query. But then how can I rewrite the old style of fetch plan for example below (which no longer works in 3.x). As you have mentioned, projections will not give OElement and cannot be used in example below. But now fetch plan is not working either.

```java
String queryWithFetchPlan = "select from MyClazz fetchplan *:2";
try (OResultSet rs = graph.query(queryWithFetchPlan);) {
  while (rs.hasNext()) {
    OResult r = rs.next();
    OElement v = r.getElement().get();
    //Inspect values on v & its connected "pre-loaded" vertices
   //...

   //Finally persist changes on v (and maybe a few other connected vertices)
   v.setProperty("propagated_", true);
   v.save();	
  }
}
```
