### ISSUE TITLE
Revert on an OVertex

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8043]
### OS: Centos

Hi guys,

I'm porting over to 3.0 as you know.  I've hit a couple of issues.  If I have an OVertex  and I make changes to it. so far I have to do save() to make sure the transaction commits it.  however, I cannot find a way to revert a record without the full transaction.

Question 1:
how to revert a single OVertex changes.  I tried clear() but that was rejected in a transaction.

Question 2:
how to get the old value after the change.

if I do node.setProperty("name", "Luca"), can I retrieve the previous value?

Regards,
Safwan

**Comment by tglman** [comment]
Hi,

We have internal API for revert a single vertex(undo), but we cannot expose them for now, because a undo of a vertex where in the same transaction has been connected to another vertex with an edge will loose the connection from a side, we can consider to do a new connection aware API, in the next release.

Regards
