### ISSUE TITLE
3.0 change in SQL result behavior regarding count(*) result. Breaking code

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8047]
### OS: Centos  

in 2.2, **Select Count(*) from bla** would return property **count** in the result.  now it returns **count(*)**.  I've changed my code to do "count(*) as count".  Not sure if this was intentional, so FYI.

Safwan

**Comment by metametametameta** [comment]
I found the same thing - just added a count alias as well since it would be pretty future proof.

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

yes, it is intentional, in v 2.2 the default projection aliases were just the function name; if you had collisions, OrientDB added a suffix (eg "_1", "_2") to remove ambiguity, but it was far from being deterministic.

Now, in v 3.0, the default projection aliases are just the string version of the projection itself

Thanks

Luigi
