### ISSUE TITLE
garbled ansi logs

### ISSUE THREAD

**Issue by hrstoyanov** [orientechnologies/orientdb#8090]
## Expected behavior  
[WARNING ] Storing configuration for property:'server.database.path' not existing in current version

## Actual behavior  
[WARNING ] $ANSI{green {db=OSystem}} Storing configuration for property:'server.database.path' not existing in current version

## Steps to reproduce  
I am getting this $ANSI {} stuff in log messages. I am assuming someone wanted to color things on the screen (assuming ANSI terminal always) making a huge mess in the process.

Second question: Why am I getting 'Storing configuration for property:'server.database.path' not existing in current version'

**Comment by tglman** [comment]
Hi @hrstoyanov,

there is some autodetection of ansy console, but probably in your case is not working as expected, you can run the server with ` ./server.sh -Dlog.console.ansi="false" ` and the ansi log will be disabled, the `server.database.path` logging is some missing internal mapping, is going to be fixed in future version.

Regards
