### ISSUE TITLE
Orientdb driver

### ISSUE THREAD

**Issue by zer09** [orientechnologies/orientdb#8122]
Is there plan for implementing official driver for golang?

https://github.com/istreamdata/orientgo seems dead.

Thanks

**Comment by tarunwadhwa13** [comment]
Reviving this thread because this seems to be a big concern now. 
Most of the API Drivers(mainly ones in Python and Golang) are now not maintained. 
Even connecting to OrientDB 3.x is now not possible. 

This becomes a blocker while using Orient in most stacks as most of the features aren't available in bare HTTP API. 

Is any plan for implementing official API driver for few more languages?

**Comment by laa** [comment]
Hi @tarunwadhwa13, could you be more specific, what is absent in HTTP API as for now? Your feedback would be helpful in improving it.

**Comment by tarunwadhwa13** [comment]
Hi @laa , please don't take me wrong. The HTTP API provides much more options and flexibility more than what one can expect. But features like TRAVERSE, LIVE QUERY, single query transaction control or multi-threading becomes more like devolepers' ownership (which isn't bad but can lead to errors when multiple dev are working on a system)
Having a library not only provides stronger cohesion with code base but also ensures security measures and limits are implemented across
