### ISSUE TITLE
remove restriction to query on all properties when multi-property index needs to be used

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#8170]
## Expected behavior  
When a multi-field index (can be Lucene or non-Lucene) is created with 3 or more properties, and I want to run a query that specifies a value/criterium for any of this properties but not all properties, then all properties used in the index definition and preceeding the ones for which I specify a criterium need to be included with a criterium as well.

For example:
  - my index is defined with properties A, B and C
  - I have a query in which I want to specify a criterium for B and C, but not for A (can be anything)
  - I **have** to specify also a criterium for A, otherwise the index is not used (in case of non-Lucene index), or an error is returned (in case of Lucene index)
  - alternatively, when I want to specify a criterium for A and C, but not for B (can be anything), again the index is not used (in case of non-Lucene index) or an error is returned (in case of Lucene index)

Lucene example:
```
select * from $myClass WHERE [A,C] LUCENE 'A:[20180320073000 TO 20180320073959] AND C:12345 '
```
returns
```com.orientechnologies.orient.core.exception.OCommandExecutionException: Cannot evaluate lucene condition without index configuration. DB name="testdb"```

Only this style works:
```
select * from $myClass WHERE [A,B,C] LUCENE 'A:[20180320073000 TO 20180320073959] AND B:* AND C:12345 '
```

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

OrientDB index  data structures are not designed to query a random subset of properties, so it cannot be done in general.
You can query a *prefix* of the index declaration though, eg. if the index is defined on A, B, C you can query it on A or on A, B

For Lucene I think it's a bit more complex, because it's completely out of our control, when you query with a condition like `LUCENE 'A:[20180320073000 TO 20180320073959] AND B:* AND C:12345 `, the `'A:[20180320073000 TO 20180320073959] AND B:* AND C:12345` part is completely delegated to Lucene engine and is outside of the control of OrientDB

Thanks

Luigi
