### ISSUE TITLE
Pre-Compiling Queries in OrientDB

### ISSUE THREAD

**Issue by kmhughes** [orientechnologies/orientdb#8244]
### OS: Linux

Is there a way to pre-compile queries in OrientDB so I needn't have to spend the time to parse the query, come up with a fetch plan, etc, every time the query is issued?

**Comment by luigidellaquila** [comment]
Hi @kmhughes 

There is no explicit way to pre-compile statements in OrientDB.

In v 2.2 the parsed queries are cached, so if you execute the same query twice OrientDB will just pick the AST from the cache, avoiding to parse it again.

In v 3.0 also the execution plan is cached, so also the query optimization is performed only once.

My advice is to always use parameters (positional `?` or named `:paramName`) instead of hard-wiring values in the SQL, this will help in the caching process and will also avoid SQL injection

Thanks

Luigi

**Comment by kmhughes** [comment]
Cool, many thanks!

Yes, I always use parameters in my queries, it became a habit years ago.

When is the official release for 3.0? I saw a 3.0 tag in github, but have seen nothing on the main site.

**Comment by luigidellaquila** [comment]
Hi @kmhughes 

I can only tell you that it is very close to be released, it's just a matter of completing side activities for the official launch

Thanks

Luigi

**Comment by kmhughes** [comment]
Hi @luigidellaquila 

OK, many thanks. I am hoping we can upgrade to 3.0 before our MVP release, while things are quiet and there is time to try the new release and shake out any issues, hence my interest. I imagine doing a major release takes some time to get all of the side activities done. Exciting time!

Best,
-Keith
