### ISSUE TITLE
[v3.0.1] Using Square brackets in projection to get a range of items always return an empty array

### ISSUE THREAD

**Issue by mehdizarepour** [orientechnologies/orientdb#8289]
### OS: Linux

Hi, I want to use square brackets in my projection.

## Actual/Expected behavior  
I want to use brackets in projection to get a range of items(`[x-y]`), But it doesn't work, I mean it returns an empty array instead of array of users.

It doesn't work:
```sql
select expand(out("E")[0-2]) from User where id =  1;

select expand(friends[0-2]) from User where id =  1;
```

Result:
```json
{
   "result": [
        
    ],
}
```

## Steps to reproduce  
```sql
/* Schema */
create class User extends V;
create property User.id Integer;
create property User.name String;
create property User.friends LinkSet;

insert into User set id = 1, name = "A";
insert into User set id = 2, name = "B";
insert into User set id = 3, name = "C";
insert into User set id = 4, name = "D";

Update User set friends = (select from User where id in [2,3,4]) where id = 1;

CREATE EDGE E FROM (SELECT FROM User WHERE id = 1) to (SELECT FROM User WHERE id IN [2, 3, 4]);

/* Query */
select expand(out("E")[0-2]) from User where id =  1;

select expand(friends[0-2]) from User where id =  1;
```

**Comment by luigidellaquila** [comment]
Hi @mehdizarepour 

In v 3.0 we changed the syntax for ranges. We don't use `-` anymore because it's ambiguous (minus is used for subtraction, as it should be) and we replaced it with a much more natural `..` and `...` syntax, eg.

- `out("E")[0..2]` takes the first two elements of the collection (right index excluded)
- `out("E")[0..2]` takes the first three elements of the collection (right index included)

Here you can find the full syntax https://orientdb.com/docs/3.0.x/sql/SQL-Syntax.html#square-bracket-filters

I'll also add a note about this in the migration guide, it seems it we forgot it

Thanks

Luigi

**Comment by luigidellaquila** [comment]
As a side note, when OrientDB calculates `out("E")[0-2]`, it first executes the subtraction `0-2` that results to -2. So that expression is equivalent to `out("E")[-2]` that takes the -2th element of the collection, that does not exist of course

Thanks

Luigi
