### ISSUE TITLE
`path` command doesn't show anything on grapheditor(studio)

### ISSUE THREAD

**Issue by anukul-mohil** [orientechnologies/orientdb#8387]
## Expected behavior  
`path` command on graph editor should show the path(s) returned by the query.

## Actual behavior  
`path` command doesn't show anything on grapheditor(studio) but shows correct output on browse section of the studio.

## Steps to reproduce  
I tested it on queries from [here](http://tinkerpop.apache.org/docs/current/reference/#path-step).
Ex: g.V().out().out().values('name').path()

May be helpful: https://github.com/orientechnologies/orientdb/issues/8327

**Comment by maggiolo00** [comment]
Hi @anukul-mohil 

The graph editor of OrientDB is built primary against ODB SQL. 
It's not optimized against Gremlin, since it's an external plugin. 

OrientDB has a TP3 edition that embed a GremlinServer.

Did you check some visualization tool built around gremlin?

Something like this

https://github.com/bricaud/graphexp

**Comment by anukul-mohil** [comment]
@maggiolo00 Thanks for the info, will look in to graphexp.
Also, Is there an orientdb google group or any other chat group where we can ask questions first or the recommended way is to create an issue here.
