### ISSUE TITLE
Invalid format for configuration file

### ISSUE THREAD

**Issue by StrangeTcy** [orientechnologies/orientdb#8440]
## Expected behavior  
working with VehicleHistoryGraph databases

## Actual behavior  

And then from the console I try to `connect plocal:/opt/orientdb/databases/VehicleHistoryGraph admin admin` and get an error:

    Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'VehicleHistoryGraph'
    
    Error: com.orientechnologies.orient.core.exception.OStorageException: Invalid format for configuration file /opt/orientdb/bin/../databases/VehicleHistoryGraph/database.ocf for storageVehicleHistoryGraph

Is there a way for me to fix the configuration file?

ETA: downloading and unzipping a public database over the version that I had didn't fix the issue.

ETA: `GratefulDeadConcerts` and `Tolkien-Arda` work just fine.

## Steps to reproduce  
Install orientdb, download a public database, try to connect to it from console.

**Comment by laa** [comment]
Hi @StrangeTcy , if I get you correctly you downloaded VehicleHistoryGraph database and when you tried to open it, you have got this error on 3.0.4 version did not you?

**Comment by StrangeTcy** [comment]
Not exactly. First I downloaded the VehicleHistoryGraph database and tried to open it on orientdb 3.0.2., but I got this error. Then I downloaded a fresh orientdb 3.0.4, installed it, downloaded the  VehicleHistoryGraph database from Studio and tried to access it, but still got the same error.

**Comment by ellisgl** [comment]
I'm getting this on 3.0.4 when I imported from the "cloud" icon. I can't login into the DB nor can I remove it from the list in the GUI. Running on Win 10.

**Comment by diversit** [comment]
Same problem running latest (=3.0.7) OrientDB from docker. After successful downloading db from cloud, cannot acces it or remove it.

**Comment by rabinnh** [comment]
Ditto

**Comment by owennewo** [comment]
I'm new to OrientDB and experiencing the above issues.  So what I think is going on is that the VehicleHistoryGraph.zip is in binary format 1.x (all the files in zip are from 2014) and orientdb 3.x is refusing to open it.  i.e. orientdb only suppport opening binary files from the previous major version (2.x).

The zip files are (I believe) not an 'export' but the raw binary data files.  I think someone (in orientdb) needs to delete that evil 1.x zip that is causing us newbies so much confusion and replace it with a 2.x zip.  :0)

The issue is compounded by the fact that the oriendb studio happily dowloads and 'imports' (i.e. unzips) zip files it is not able to actually connect to.  Furthermore 'drop database' doesn't work against these databases because you can't connect to them.  All very silly and a bad first impression.

**Comment by jamendub** [comment]
So, I am trying to do the same stuff in 2019 and the problem is still there...!
I have to agree with @willyrj that this doesn't sound really good if you have a problem in a production environment....
Is it just the set of data that is corrupted (which seems to be the case) or the core of OrientDB, though ?

**Comment by adadouche** [comment]
Hi @jamendub , @willyrj , @owennewo , @rabinnh and others, 

Looking at the logs you should see a message saying the following after the ***VehicleHistoryGraph\database.ocf for storageVehicleHistoryGraph*** message: 
```
com.orientechnologies.orient.core.exception.OStorageException: cannot open database created with a version before 2.0 
```
So, I tried to export the VehicleHistoryGraph  from a version 2.2.x instance and import it into my 3.0.18 but it failed because of the existence of a property named ***rules** of type EMBEDDEDSET in the ORole records for admin etc.

So, I dropped the property from the ORole records, exported again.

Then I was able to import it in my 3.0.18 instance.

Hope this helps

**Comment by laa** [comment]
Hi, if this still an issue we can work on this, otherwise, it will be closed.
