### ISSUE TITLE
Subquery as a field in select

### ISSUE THREAD

**Issue by freeart** [orientechnologies/orientdb#8458]
Hi, I have a question about orient 3.0.5 (official docker image). 
I'm trying to select a document with subquery as field:
```sql
select id, (SELECT id, code FROM Table2 WHERE table1_id = Table1.id) as status from Table1
```
What I'm doing wrong? 
Query returns ```"abc", []```, 
but when I put the value "abc" instead of Table1.id 
it returns ```"abc", [{id: "a", code: "123"}]```.
How to use row values (ex. ```table1_id = Table1.id```) in a subquery as a condition?
Is it issue?
___P.S. I know about LINK data type in orientdb, but in this case I can't use it. I should use string.___

**Comment by luigidellaquila** [comment]
Hi @freeart 

your query doesn't work because in the context of the inner query you cannot access the LET values of the outer query. The following will work though

```
select id, (SELECT $parent.$current.id) from Table1
```

Luigi

**Comment by sjurco** [comment]
Hi @luigidellaquila 

that's not completely true.


Using `Table1` with content:


    @rid     @version   @class   id
    #69:0    1          Table1   1
    #70:0    1          Table1   2



Your query works as expected but you can write it using LET values too:

    select id, (SELECT $parent.$current.$a) from Table1 LET $a = id;

result:

    id   (_$$$SUBQUERY$$_0)
    1    [{"$parent.$current.$a":1}]
    2    [{"$parent.$current.$a":2}]

you can still access the LET values of the outer query in select:

    select id, (SELECT id from Table1 where id = $parent.$current.$a) from Table1 LET $a = id;

and it returns the very same results as query:

    select id, $a from Table1 LET $a = (SELECT id from Table1 where id = $parent.$current.id);

so it looks like you cannot access LET values only within LET itself since this query does not work:

    select id, $a from Table1 LET $id = id, $a = (SELECT id from Table1 where id = $parent.$current.$id);

Taking that into account I've written the same query using nested select assuming it should work:

    select id, letId, $a from (select id, $letId as letId from Table1 LET $letId = id) LET $a = (SELECT id from Table1 where id = $parent.$current.letId);

but the result is not correct:

    id   letId   $a
    1    1       []
    2    2       []

even using "static" variable not calculated from LET does not work:

    select id, letId, dummy, $a from (select id, $letId as letId, 1 as dummy from Table1 LET $letId = id) LET $a = (SELECT id from Table1 where id = $parent.$current.dummy);

result:

    id   letId   dummy   $a
    1    1       1       []
    2    2       1       []

The most "interesting" thing I've discovered is that this query returns something but not what I've expected:

    select id, letId, $a from (select id, $letId as letId from Table1 LET $letId = id) LET $a = (SELECT id from Table1 where id = $parent.$current.$letId);

result:

    id   letId   $a
    1    1       [{"id":1}]
    2    2       [{"id":1}]

As you can see `$letId` is not returned from nested query therefore it should not be visible for outer query but it is and contains value from the first row only

And the same incorrect result is returned for query using `id` (which is visible) instead of `$letId`:

    select id, $a from (select id from Table1) LET $a = (SELECT id from Table1 where id = $parent.$current.id);

result:

    id   $a
    1    [{"id":1}]
    2    [{"id":1}]

The best of all is using query that should never return number `1`:

    select id, $a from (select 2 as id from Table1) LET $a = (SELECT id from Table1 where id = $parent.$current.id);

but the result is:

    id   $a
    2    [{"id":1}]
    2    [{"id":1}]
