### ISSUE TITLE
Change Hazelcast version to 3.9

### ISSUE THREAD

**Issue by vitalii-honchar** [orientechnologies/orientdb#8500]
### OS: Ubuntu 18.04
We run our project Orienteer in distributed mode, so we need to run OrientDB in distributed mode.
As we want to use Docker Swarm and dynamically increase Orienteer (OrientDB instances too) instances, so we need automatically detect new OrientDB instances in network.

Hazelcast with version 3.8.4 which uses in current version of OrientDB can't dynamically detect new instances. With config:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast
	xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.3.xsd"
	xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<group>
		<name>orientdb</name>
		<password>orientdb</password>
	</group>
	<network>
		<port auto-increment="true">54327</port>
		<join>
			<multicast enabled="true">
				<multicast-group>235.1.1.1</multicast-group>
				<multicast-port>54327</multicast-port>
			</multicast>
		</join>
        <interfaces enabled="true">
            <interface>10.0.1.*</interface>
        </interfaces>
	</network>
	<executor-service>
		<pool-size>16</pool-size>
	</executor-service>
</hazelcast>

```

But it was fixed in Hazelcast version 3.9. Issue https://github.com/hazelcast/hazelcast/issues/10477
I tested OrientDB with Hazelcast version 3.9.4 and all works as expected. (I can dynamically create new replicas and they found each other).

But Hazelcast with version 3.9.4 contains big changes and there are present compilation in [this lines](https://github.com/orientechnologies/orientdb/blob/2.2.x/distributed/src/test/java/com/orientechnologies/orient/server/distributed/ServerRun.java#L121-L122)

Please, use new version of Hazelcast if it is possible. We need feature from issue https://github.com/hazelcast/hazelcast/issues/10477

Thanks,
Vitaliy

**Comment by PhantomYdn** [comment]
Can you please update Hazelcast version in next 2.2.x version?

**Comment by lvca** [comment]
Hi WeaxMe, the compilation problem is just with the test case that simulates a network failure. We could try to upgrade and see if the tests are ok.

**Comment by PhantomYdn** [comment]
@lvca , thank you! But we figured out one more problem in OrientDB which prevent scaling through docker swarm. Let me explain step by step:
1) By default OrientDB binds to 0.0.0.0: so to all available interfaces
2) Multicast in Hazelcast successfully allows to find other nodes in a docker swarm. So NodeA see NodeB
3) But OrientDB on NodeA provides just one internet-address to which it is bind and unfortunately it provides wrong IP which is not available from NodeB.

Please check this article: https://neuvector.com/network-security/docker-swarm-container-networking/
It's enough to check just last diagram.
So OrientDB on Node A provides 10.255.0.X instead of 10.0.0.X.

Yes - there is a work around: specify particular IP address to which OrientDB should bind, but it's pretty inconvenient, because config files should be altered.

**Comment by WeaxMe** [comment]
@lvca we found how to specify IP address in config for OrientDB server

```xml
 <listener protocol="binary" ip-address="${ip.address}" port-range="2424-2430" socket="default" />
```

`${ip.address}` - this is IP address of container where OrientDB runs. 

(Can be used environment variable `$HOSTNAME` instead explicit IP.)

With this config we successful run OrientDB inside Docker Swarm.

Thanks,
Vitaliy.
