### ISSUE TITLE
Broken contract of aggregate functions

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#8644]
### OrientDB Version: 2.2.37

Writing custom OSQLFunction. Per documentation: if function is to aggregate (`aggregateResults()` returns true) the final result should be taken through method `getResult()`. But in fact, result of last `execute(...)` is being returned. 

## Expected behavior  
`getResult()` should be used on aggregate functions to obtain the final result;

## Actual behavior  
`getResult()` never invoked

## Steps to reproduce  
Trace any aggregate function: for example `count()` or `sum()`

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

Is it creating any bugs in query execution?
I'm asking because I checked the code in v 2.2 and 3.0 and I agree with you that the javadocs are misleading for the old executor, but they are OK for the new one (v 3.0 and following), so I don't know if it's worth changing it now...

Thanks

Luigi

**Comment by PhantomYdn** [comment]
@luigidellaquila , yes - it does. Problem is the following: calculation of a result require pretty good effort in our case and do calculations everytime instead of caclulate once at the end - it's killing performance.

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

In v 3.0 `getResult()` is used at the end of the elaboration to collect the results, as the javadoc says.
I got your point about performance, I'll check the old executor and see if I can optimize it

Thanks

Luigi
