### ISSUE TITLE
LUCENE search not returning all records

### ISSUE THREAD

**Issue by DiarmaidEverycs** [orientechnologies/orientdb#8645]
## Expected behavior  
Search using a LUCENE FULLTEXT index and find strings which includ brackets and dashes

## Actual behavior  
Only finds items without brackets and dashes

## Steps to reproduce  
Create a new database
Create a new vertex test
Create a field name on the vertex
Create an LUCENE FULLTEXT index on the field

Then insert some items into the vertex
insert into test content {"name": "A()"}
insert into test content {"name": "A-"}
insert into test content {"name": "B()"}
insert into test content {"name": "B-"}
insert into test content {"name": "AAA"}
insert into test content {"name": "BBB"}

Now run a test search to find all of the names with A in them
select from test where [name] lucene "A*" limit 5
Results: 1 record, name of AAA
select from test where [name] lucene "B*" limit 5
Results: 3 records, name of B-, B() and BBB

Why are these different?   Also, is it possible to use search for lucene special characters in orientdb, and if so, how?

**Comment by luigidellaquila** [comment]
Hi @DiarmaidEverycs 

I think it's because of the analyser Lucene is using, that considers "A" as a stop word (see https://stackoverflow.com/questions/17527741/what-is-the-default-list-of-stopwords-used-in-lucenes-stopfilter) and discards it.

In general, it is not related to OrientDB query engine, but to Lucene itself

Thanks

Luigi
