### ISSUE TITLE
open db very slow ( like a minute ) in spring boot

### ISSUE THREAD

**Issue by grimace** [orientechnologies/orientdb#8704]
## Expected behavior  
open should not take over a minute to open a database

## Actual behavior  
when run inside SpringBoot application db.open takes 84 seconds

## Steps to reproduce  
``` 
       orient = new OrientDB("remote:" + dbserver, OrientDBConfig.defaultConfig());
        db = orient.open(dbName, "userid", "blablabla");
        logger.log(Level.INFO,"opened db");
```
same code in a straight up Test class works quickly.

I'd love to point to some issue in my code though I'm not sure how to proceed.  How can I profile this?  Also how do I turn on debugging for network?

**Comment by grimace** [comment]
I bumped the orientdb-client version to 3.0.12 ( to match the server? ) and this problem went away.  Open DB is now about 2.5 seconds.  Still don't know what the issue was and would still like to know how to really debug this problem.   I'm happy to close this if someone can point me to docs on how to trouble shoot slow opens.

**Comment by luigidellaquila** [comment]
hi @grimace 

Thank you for the details, probably the problem is with some incompatibility with the drivers of different versions. OrientDB client tries to adapt and re-submit requests when they fail, also scaling to old protocol versions, but of course it takes time and can give some slowdown.

In general, profiling this kind of behaviour is not easy, there are no built-in tools, so we rely on general purpose profilers (eg. YourKit)

Happy to know it now work fine

Thanks

Luigi

**Comment by mmacfadden** [comment]
Just one other thought? Are you running the database in the spring app itself or as a separate process. I have noticed that if you are running the database embedded in your app, and you are quitting the JVM abruptly that OrientDB will have to go through a repair cycle when you next start up. This might not be your case, but something else to consider.

**Comment by grimace** [comment]
No, the server is running as a standalone instance.
