### ISSUE TITLE
Query @rid by JDBC ,Return '#-1:-1'

### ISSUE THREAD

**Issue by ASXHOLE** [orientechnologies/orientdb#8740]
## Expected behavior  
I want to query the @rid of the Node  by JDBC Driver

## Actual behavior  
My JDBC Driver Version : 3.0.13

Java code as below:
```
Properties info = new Properties();
info.put("user", "root");
info.put("password", "xxxx");
Connection conn = (OrientJdbcConnection)DriverManager.getConnection("jdbc:orient:remote:192.168.5.99/chedaidb", info);

Statement stmt = conn.createStatement();

ResultSet rs = stmt.executeQuery("SELECT @rid as rid FROM NODE1 where node_id='46247'");
rs.next();
String rid = rs.getString("rid");
logger.info("@rid is:"+rid);
```

my console print :
`@rid is:#-1:-1`

When i use studio it can return correctly : 
```
{
    "result": [
        {
            "rid": "#31:5780"
        }
    ],
    "executionPlan": {
        ...
    },
    "elapsedMs": 1,
    "notification": "Query executed in 0.045 sec. Returned 1 record(s)"
}
```

## Steps to reproduce  
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by mmacfadden** [comment]
@ASXHOLE this may not work, but I know OriendDB has some "magic" string conversion with some of the protected fields (class, rid, etc.). It may be returning the ORID of the projected document which will be `#-1:-1`

Can you try the following:

```
Properties info = new Properties();
info.put("user", "root");
info.put("password", "xxxx");
Connection conn = (OrientJdbcConnection)DriverManager.getConnection("jdbc:orient:remote:192.168.5.99/chedaidb", info);

Statement stmt = conn.createStatement();

ResultSet rs = stmt.executeQuery("SELECT @rid as nodeRid FROM NODE1 where node_id='46247'");
rs.next();
String nodeRid = rs.getString("nodeRid");
logger.info("@rid is:"+nodeRid);
```

It very well might yield the same result. Just trying to eliminate some possibilities.

**Comment by ASXHOLE** [comment]
Hi, @mmacfadden  
Thank you very much ! It worked ,using the  'AS'  keyword. 
But I still feel a little bit puzzled , isn't it a bug?

**Comment by mmacfadden** [comment]
It might be a bug. But I can somewhat explain what is going on.  When you use a projection, OrientDB creates a "fake" document with the results of the projection.  For example, assume you had a document with 10 fields. But when you do a SELECT you only select 3 of them through a projection. Then assume you get ahold of one of those selected documents.  If you were then to call `doc.save()` on that record, what would you expect to happen?  You can't really save that document because it doesn't have all of the required properties.

Moreover, you can actually project child fields into the parent record, etc. so it just becomes messy. So when you project, the document you get back is not actually a document of the Class that you selected from, and the records that come back are not actually the original documents with the original RIDs.  OrientDB creates "anonymous" documents with no class and no rid.

So when you do this:

`String rid = rs.getString("rid");`

You are asking OrientDB for the rid of the anonymous record that was returned. It's a bit confusing, because you asked the projection to get you the RID of the original record, but the anonymous document will also have an "rid" field, which seems to take precedence.

So by giving the RID you actually want an alias, it will deconflict the source document's RID and the RID of the anonymous projected document.

@luigidellaquila Can you confirm I have this correct?
