### ISSUE TITLE
Multi threading : how transactions are maintained across multi threading

### ISSUE THREAD

**Issue by rbaarathi** [orientechnologies/orientdb#8834]
## Expected behavior  
How to achieve transactions in multi threading on clusters.

## Actual behavior  
In Orient database, we have n number of tables created and for each table we are creating unique clusters based on the count to be added in that table and adding those records in that cluster by specifying the cluster name.

After this, we have introduced multi threading to add multiple records in multiple clusters parallely. Database instances are created in each thread either in run() or call() method.

Now I want to know how transactions are achieved in multi threading across clusters..??

I have a small code snippet so that you can understood easily.

I have 5 cluster namely cluster-A, cluster-B, cluster-C, cluster -D and cluster -E. 5 records to be added in each cluster. Now,I will create 5 thread so that each thread can write in parallely in 5 individual clusters.

@Override
        public Boolean call() throws Exception
        {
            try (DocDB db = new DocDB(databaseID))
            {
                db.setAsActiveThread();
                for (InventoryEntity ie : entities)
                {
                    try
                    {
                        addEntity(db, ie.getUniqueKeyAndType(), ie, clusterName);
                    }
                    catch (Exception e)
                    {
                        return false;
                    }
                }
            }
            return true;
        }

I have a multiple JAVA object that has been broken in many smaller records, and those are grouped in some ways to add to cluster parallely so that records are mingled together and if some exception occurs how can we rollback() the transaction..???????

**Comment by laa** [comment]
Hi, transactions are not maintained across multithreading and I am not aware of any database which supports transactions across multiple threads.

**Comment by adithyank** [comment]
@laa 

Our initial data loading in to orientdb took more than 25 hours. 

We then used the stored the records of one class to multiple clusters. Writing in clusters is now done in multiple threads. i.e., one cluster writing is done by only one thread. 

This improved our writing performance from 25 hours to 7 hours. Since it is done in multiple threads, we have lost the ATOMIC writing and hence rollbacks have become impossible. This has created lot of CONSISTENCY issues across the classes...

We are trying to solve this issue now... 

**Solution at hand is** : if we write all cluster records in one thread, we can bring back Rollback facility. But, the improvement due to multi threads will be lost again....!

Pls give feedback if you need more details to give solution for this

**Comment by rbaarathi** [comment]
@laa  Please change the state from closed to open..

**Comment by laa** [comment]
@rbaarathi, unfortunately, we do not have plans to support transactional behaviour across multiple threads in the foreseeable future.

**Comment by adithyank** [comment]
@laa Andrey, 

That is understood.. Pls see my above comment and just comment whether that is the only way...
(i.e., writing all the records of different clusters in one thread within transaction. This will worsen our writing time.. But, is that the way to it...)

If we want to achieve better writing speed, we cannot have Transaction?
If we dont want ATOMIC writing, then we can do multi-threading with clusters..


Am I right??

**Comment by laa** [comment]
Hi @adithyank if you do not want atomic writes sure, you can do writes in several clusters without problems. I am working right now to speed up things in a couple of times during data load, but unfortunately, that will be only in 3.1 version.
