### ISSUE TITLE
OrientDB 3.x doesn't support multi pools

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#8845]
### OrientDB Version: 3.x

OrientDB 3.x doesn't provide the ability to have a multi-pool - when next connection can be retrieved for a specified username and password.
OrientDB 2.x supports that through OPartitionedDatabasePoolFactory, but there is a lack of such capability in 3.x. Apparently, OrientDB has a great security model and it's really strange that it lost this ability of multi-pools in version 3.x. Please help with returning it back.

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

This is a quite simple addition if you do it with a naive approach, but doing it efficiently is not easy.
When you open a DB connection, you have to do it using a username and a password and you cannot change them later. Adding such connection to a pool means that it can be used only if user and password match, otherwise you have to open a new connection and pool it.
This leads to at least two problems:
- the pool size is one for all the users, so if the pool is full with "free" connections but none of them matches the credentials, you have to close one of them and create a new one. The eviction strategy is not rocket science, but different choices (FIFO, LRU, LFU) can lead to different behaviours and be more or less performing for different scenarios.
- the username and the password have to be kept in memory for a long time, that is not a very good practice. This can probably be mitigated with some hashing

I'm marking this as an enhancement, we'll discuss it for future implementation.

In the meantime, what I can suggest is to write a higher level connection pool that uses a set of connection pools for different credentials

Thanks

Luigi
