### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by thenesk** [orientechnologies/orientdb#8852]
### OrientDB Version: <3.x>  

What is the official / recommended way for python to communicate with OrientDB 3.x?  Is it pyorient from pypi, or is there another recommended way?

**Comment by brucetony** [comment]
The current published pyorient on PyPI does not work with OrientdB 3.x by default, but that is simply because of a few lines of code that check for the version. The pyorient repo was forked and those lines were commented out:  

https://github.com/orientechnologies/pyorient

If you install this repo, OrientDB 3.x with work with it, so long as your functions do not start with an underscore "_"
