### ISSUE TITLE
[Question] SQL vs Java API (from java) - Performance and "feasibility" 

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#8894]
I was wondering what is the recommended approach on queries using java code.
As far as I know my 2 options are either SQL using `ODatabase.query(..)` or the java api using methods such as `ODatabase.save(..)`.

Regarding feasibility, I'm referring to "complex" queries that includes sub-selects or let, such as
`CREATE EDGE friend FROM (select FROM user where id=52) TO (select FROM user WHERE id=93)`.
Can this be even done using the java api? If so, how? 

Regarding performance - which one would be more performant?
If needed, we can split this up to 2 parts:
(a) "Simple" queries such as the one easily supported b the java api (e.g. save as mentioned above)
(b) More complex queries such as the create edge sql mentioned above, assuming it is even possible?

If there are any other considerations that would affect using one over the other, please note so.
It might also be a good idea to add such a section to the documentation

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

In embedded mode there is no much difference, actually the SQL also uses high level APIs, so the performance is the same.

In remote the thing is a bit different, because using the Java API typically involves multiple accesses to the physical data, that require multiple network round-trips. With SQL you avoid all this, because the whole execution is done on the server and you only have network communication to obtain the final results.

For simple operations, like creating a record, the APIs are definitely OK; for complex operations I'd suggest to use SQL

Thanks

Luigi

**Comment by matanshukry** [comment]
Awesome Luigi, thanks!
I'm closing this as it's definitely solved, but I would also highly recommend adding that part of information you just wrote in the documentation, I think it would be very helpful.
