### ISSUE TITLE
[Security Question] Exposing ORID to users - security risk?

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#8934]
I'm designing an entity in my backend where I need an id. The options as far as I can tell are:
(a) Use a sequence to generate id
(b) use the ORID string repesentation (without colon) as a string identifier.

I was wondering if there are any security vulnerabilities (or other cons) to exposing the raw ORIDs to users?

**Comment by laa** [comment]
Hi @matanshukry I am not a security expert, but anyway because I know the internals of storage very well, I could tell that RIDs are absolutely random, so you can not infer which information is stored underneath of record just by knowing RID. Rid can only be inferred if you know about all actions performed on this cluster above and order of those actions which hardly possible. And still, that is not enough to infer which information is stored inside the record with given RID.  The only disadvantage I see is that if you export database in other format let say JSON and import again RIDs will be different which again is proof that they are quite secure. But RIDs cannot be used in an external system as a link to the record. It could be used only internal references inside the database. That is because they can be changed during the export/import procedure.

**Comment by matanshukry** [comment]
@laa Awesome detailed explanation, thanks! Should be added to the doc IMO btw, possibility to the auto increment and sequences ( https://orientdb.com/docs/3.0.x/sql/Sequences-and-auto-increment.html ), or to a more general 'generated id' page. Either way awesome, thanks! :)

For other people looking for this: 
Although this does mean the RID is secure enough to be exposed to users, the fact that it's not constant and be changed on import/export, and (as far as I know) we can't decide the RIDs when importing - make it 'unstable' to be used as an identifier. Hence I'll be using Sequences
