### ISSUE TITLE
How to select and export database in windows 10？

### ISSUE THREAD

**Issue by daisy-qwer** [orientechnologies/orientdb#8970]
## Expected behavior  
Export the database in localhost by console

## Actual behavior  
Error occurred during export

## Steps to reproduce  
<Here are the command lines in cmd:
1. cd c:\orientdb-3.0.20\bin
2. console.bat--- OK
3. connect remote:localhost:mydb root password--- OK
4. export database mydb.zip
<Error: com.orientechnologies.common.exception.OSsystemexception: Database not selected. Use 'connect <url> <user><password>' to connect to a database.>
>  

Any help would be appreciated!

**Comment by TianCangWu** [comment]
Solved:
Orientdb would not report an error in Step 3 even for a nonexistent database. To correctly export database,  Step 3 should be corrected into: 
1. change "localhost" into the actual domain name (e.g. 127.0.0.1);
2. add "/"  before the database name;
Thus we get: connect remote: 127.0.0.1 :/ mydb root password

**Comment by x007007007** [comment]
Hi @TianChangWu
`connect remote:localhost:/mydb root password`  you should have a slash before database name. I have successfully connect server once I have slash which have a short echo on terminal like `orientdb {db=import_test}>`  rather than `orientdb {server=remote:localhost:import_test}>`. It seem that orientdb console haven't a friendly echo. I think change hostname is not necessary.
by a way, I don't think exported format is zipfile , `export database mydb.zip` imply zipfile

**Comment by TianCangWu** [comment]
@x007007007  Exactly!

**Comment by tglman** [comment]
Hi,

This seems solved, closing it.
