### ISSUE TITLE
Data loss after JVM crash 

### ISSUE THREAD

**Issue by jayaramcs** [orientechnologies/orientdb#8979]
## Expected behavior  
Insert / Update statements under a commit block are persisted even during JVM crash

## Actual behavior  
Data is lost. 

Our application behavior is as follows. 
- On initial boot, we run some update commands to a table. 
- During normal operation
-- Write heavy. Insert upwards of 500,000 to 1M+ records in a single "session". Can have up to 5 sessions running concurrently 
-- Read load - variable, but limited to under 100,000 records at any one time generally.  

In order to support this, based on the performance tuning recommendations, we have the following settings 
 - OGlobalConfiguration.USE_WAL.setValue(false);  
 - insert writes are groped into batches (50,000) inserts each
 - ODocument.reset() called instead of new Instance.
 
The issue we are running into is that with WAL set to FALSE, the orientdb does not seem to commit data to disk, even when under a transaction block. 
 
## Steps to reproduce  

Here is a simple version of the [program](https://gist.github.com/jayaramcs/d8a705f7c850adad5e672a932a9d9965 ) that illustrates the issue. 

To recreate, put a breakpoint at line number 101 and force terminate the JVM.

connect to the db with console and observe that a select * from info table yields no results. 

Please advice on the optimal settings to choose to have the best insert performance while maintaining some level of data protection.

**Comment by wolf4ood** [comment]
Hi @jayaramcs 

this is an expected behaviour. OrientDB does not write directly on disks when updating inserting values by disabling the WAL, there is no journal anymore, and OrientDB is not able to recover from crashes. 

The WAL disabled is advised only in massive insertion, where you have control of the ingestion process.

https://orientdb.org/docs/3.1.x/tuning/Performance-Tuning.html#massive-insertion

For production usage the WAL should be on.
