### ISSUE TITLE
Filtering by embedded map value now working for embedded map with embedded documents

### ISSUE THREAD

**Issue by vitalii-honchar** [orientechnologies/orientdb#8981]
## Steps to reproduce
1. `CREATE CLASS Test`
2. `CREATE PROPERTY Test.name STRING`
3. `CREATE PROPERTY Test.map EMBEDDEDMAP Test`
4. `INSERT INTO Test SET name = "test1", map ={"@type":"d","@version":0,"@class":"Test","name":"name1"}`
5. `INSERT INTO Test SET name = "test2", map ={"@type":"d","@version":0,"@class":"Test","name":"name2"}`
6. `SELECT FROM Test WHERE map CONTAINSVALUE {"@type":"d","@version":0,"@class":"Test","name":"name1"}` returns 0 records, but must returns first record

P.S. If try to query map with simple types (for example String) all works as expceted.
Example:
1. `CREATE PROPERTY Test.simpleMap EMBEDDEDMAP STRING`
2. `UPDATE Test SET simpleMap = {"key": "value"} WHERE name = "test1"`
3. `SELECT FROM Test WHERE simpleMap CONTAINSVALUE "value"` - returns first record, so problem is only with `EMBEDDEDMAP` with embedded documents

**Comment by luigidellaquila** [comment]
Hi @WeaxMe 

I think there are a couple of mistakes in your test (in particular Test.map should be `EMBEDDED Test` and not `EMBEDDEDMAP Test`). Apart from this, Containsvalue is designed to work on maps, not on embedded documents.

In this case, the following would make sense

```
SELECT FROM Test WHERE map = {"@type":"d","@version":0,"@class":"Test","name":"name1"}
```

but the comparison doesn't work because it's two different documents, so the equality fails.

Thanks

Luigi

**Comment by tglman** [comment]
Hi,

Replied a while ago, closing
Regards
