### ISSUE TITLE
Strange read behavior in restricted class

### ISSUE THREAD

**Issue by WeaxMe** [orientechnologies/orientdb#9126]
## Expected behavior  
Restricted user with rights on read user document can read his document.

## Actual behavior  
Restricted user with rights on read user document can't read his document.

## Steps to reproduce  
I created test which shows this behavior: https://github.com/WeaxMe/orienteer-test/blob/master/orientdb-restricted-test/src/main/java/com/weaxme/test/restricted/OrientDbRestrictedTest.java

Just run it

**Comment by WeaxMe** [comment]
Hello. Guys, can you please answer for my question? I really need to know about this, for migrate our project from OrientDB 2 to OrientDB 3

**Comment by WeaxMe** [comment]
Btw. Right now this is blocker, because our users in Orienteer not works properly

**Comment by luigidellaquila** [comment]
Hi @WeaxMe 

Ok, I got the problem, the new predicate security is kicking in and not allowing you to see the OUser.

I managed to fix the test case adding the following at the testerRole creation

```
testerRole.grant(ORule.ResourceGeneric.CLASS, "OSecurityPolicy", ORole.PERMISSION_READ);
```

and the following at the end of initData

```
db.command("alter role `tester-role` set policy default_2 on database.class.OUser");
```

This should allow you to proceed with the migration.

In the meantime, I'm checking if it makes sense to add these things by default at role creation, so that you do not have to specify them manually

Thanks

Luigi

**Comment by WeaxMe** [comment]
Thanks!
