### ISSUE TITLE
community.orientdb.org in "real only mode"?

### ISSUE THREAD

**Issue by Eric24** [orientechnologies/orientdb#9225]
Is there some reason why community.orientdb.org is in "real only mode"? It's been that way for several days.

**Comment by luigidellaquila** [comment]
Hi @Eric24 

Sorry for the inconvenience, we are migrating the platform to a different hosting, but it's taking a bit more than expected.
The new hosting is already on-line here discourse.orientdb.org but there are still some small problems that should be fixed in next few hours

Thanks for your patience

Luigi

**Comment by tglman** [comment]
Hi,

The new service is up and running, sorry for the hiccups, closing this.
