### ISSUE TITLE
[OVariableParser.resolveVariables] Error on resolving property

### ISSUE THREAD

**Issue by HuaC-Z** [orientechnologies/orientdb#9399]
"command": "create egde '${className}' from  (select from course where name='${input.course}') to (select from label where name='${input.label}') set name='${input.name}'"

show me :
"create '' from  (select from course where name=objiet) to (select from label where name='JAVA') set name=contain"
Error on resolving property: classNameException

**Comment by luigidellaquila** [comment]
Hi @HuaC-Z 

OVariableParser is an old API, almost unused nowadays.
Anyway, probably the problem here is just a missing `input.`, ie. `create '${input.className}` instead of `create '${className}`

This said, probably you should use query parameters instead of variables:

```
SELECT FROM ... WHERE name = ?
```

And the `CREATE` syntax is wrong, you probably mean `CREATE EDGE 

I hope it helps

Thanks

Luigi

**Comment by HuaC-Z** [comment]
>hi @Luigi
Thank you for helping me solve the problem.
I want to get variables from the configuration file instead of from the CSV. Do you have any suggestions on this point.

**Comment by lvca** [comment]
@HuaC-Z the solution is what @luigidellaquila suggested.
