### ISSUE TITLE
Performance issue of OrientDB 3.1.2? Vertex insertion is taking too much time

### ISSUE THREAD

**Issue by Vinay97** [orientechnologies/orientdb#9404]
### OS: Windows 10

I am new to OrientDB. For my Java project I am using OrientDB-3.1.2 for graph storage(as my project is based on Model driven architecture). So the issue I am facing is, while inserting a record with few vertices and edges orientdb is taking almost 15 minutes to complete the process. And in the case where vertices count is more, with n number of properties and edges. The time it takes for insertion is unbearable(around 1 hrs). I am using orient-graphdb libraray which contains tinkerpop-blueprint2.6.0 as compiled dependency for performing graph computation such as (getting vertex by Id, adding vertex, and other CRUD ops).

Can anyone suggest me, what could be the possible reason of this much time for record insertion.

**Comment by luigidellaquila** [comment]
Hi @Vinay97 

First of all, I'd suggest to use the native Multi-Model API instead of TinkerPop 2.6, that is deprecated. 
If you really need TinkerPop support, you can consider orientdb-gremlin module, that implements TinkerPop3

About the specific problem, we need a few more details, eg. how many vertices and edges are you creating? How do you do it? Can you share a code snippet?

Thanks

Luigi

**Comment by lvca** [comment]
No answer, closing the issue for now. In case, please comment on this very issue.
