### ISSUE TITLE
Massive update does not free memory once finished

### ISSUE THREAD

**Issue by florian-stoica-tlabs** [orientechnologies/orientdb#9581]
## Expected behavior  
After a massive update/operation finishes the memory should free or at least give a way of forcing it to free. the hotspots seems to be in read cache.

## Actual behavior  
The memory remains occupied for the whole duration of the server being up.

## Steps to reproduce  
Here is a simple spring boot app https://drive.google.com/file/d/12ypCgSS9j6MShmxxk-4Yb7cFq2Cc4rr8/view?usp=sharing
Calling this curl --location --request GET 'localhost:8080/api/break?flag=false' will start doing updates to the inserted vertices

Note: not even getFactory().close will not free the memory. For sure there must be any other solution to achieve this other than being forced to restart the orient server.....

**Comment by luigidellaquila** [comment]
Hi @florian-stoica-tlabs 

The problem here is that the read cache is supposed to be as warm as possible to keep the performance good, so it typically does not release data.
If the read cache size is comparable to the DB size, then I'd say it's an expected behaviour; if it's significantly bigger, there could be a problem (a memory leak?) but we have no evidence in this sense so far, so I tend to exclude it.

Unfortunately there is no way to force a cache flush, so the only thing I can suggest is to limit the disk cache size to an acceptable value for your environment

Thanks

Luigi

**Comment by florian-stoica-tlabs** [comment]
Hi @luigidellaquila ,
Thanks for your reply, I will try with a smaller disk cache and xmx bigger so it has the same heap space, since there is nothing more to this I'll close the task, but it sure would be nice to be able to flush the cache in the future.

BR,
Florian Stoica
